version: '3.7'
services:
  kjglass:
    ports:
      - 80:8080
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
