version: 2.1
jobs:
  build:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: latest
      - run: yarn run install --frozen-lockfile
      - run: yarn run build
workflows:
  build:
    jobs:
      - build