version: 2.1
jobs:
  build:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install-packages:
        pkg-manager: yarn
      - run:
          name: Install yarn packages
          command: yarn run install --frozen-lockfile
      - run:
          name: Build projects
          command: yarn run build
workflows:
  build:
    jobs:
      - build