version: 2.1
jobs:
  build:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - run:
        name: Install yarn packages
        command: yarn install --frozen-lockfile
      - run:
          name: Build projects
          command: yarn build
workflows:
  build:
    jobs:
      - build