version: 2.1
jobs:
  build:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - install
      - run:
          name: "build projects"
          command: yarn run build
workflows:
  build:
    jobs:
      - build