version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - install
      - run:
          command: yarn build
workflows:
  build:
    jobs:
      - build