version: 2.1
orbs:
  node: 'circleci/node:3.0'
jobs:
  build:
    executor:
      name: node/default
      tag: '13'
    steps:
      - checkout
      - node/install-packages:
        pkg-manager: yarn
      - run:
          name: Install yarn packages
          command: yarn run install --frozen-lockfile
      - run:
          name: Build projects
          command: yarn run build
workflows:
  build:
    jobs:
      - build