const items = [
    {
        type: 'expandable',
        id: '1',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/expandable%2F1.jpg?alt=media&token=f4420107-bfe1-48ef-b4b2-3c27ce252764',
        classify: '(주)고려에이스과학',
        title: 'Glass Filter Adapter (그라스 휠터 아답타)',
        content: [
            '■ 고무재질로 되어 있으며 그라스휠터에 부착시켜 여과병에 끼워서 진공을 걸어 사용합니다.',
        ],
        specification: [
            {
                id: '1',
                number: 'AKJ-11-44',
                selected: false,
                content: '고무',
            },
        ],
    },
    {
        type: 'expandable',
        id: '2',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/expandable%2F2.jpg?alt=media&token=239600e6-c462-48c2-a91e-06358d44ba43',
        classify: '(주)고려에이스과학',
        title: 'Adapter For Aspirator (아스피레타용 고무 아답타)',
        content: [
            '■ 실험실용 수도와 아스피레타를 보다 편리하게 부착시키기 위하여 고무로 만들어진 제품입니다.',
            '',
            '■ 사용법은 하단부는 아스피레타를 연결시키고 상단부는 수도부분과 연결하여 드라이버로 조이기만 하면 됩니다. ',
            '',
            '■ 아스피레타는 제외된 가격입니다.',
        ],
        specification: [
            {
                id: '1',
                number: 'AKJ-00-05',
                selected: false,
                content: '나사식 용',
            },
        ],
    },
    {
        type: 'expandable',
        id: '3',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/expandable%2F3.jpg?alt=media&token=2acf0aa7-24cb-4055-a35a-0102329c8c2e',
        classify: '(주)고려에이스과학',
        title: 'Aspirator (아스피레타) -JAPAN-',
        content: [],
        specification: [
            {
                id: '1',
                number: 'AKJ-00-04',
                selected: false,
                content: '일제',
            },
        ],
    },
    {
        type: 'expandable',
        id: '4',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/expandable%2F4.jpg?alt=media&token=208d42ba-030e-4d46-8651-5af7902b37bf',
        classify: '(주)고려에이스과학',
        title: 'Aspirators (아스피레타)',
        content: [
            '■ 본제품은 황동제질에 표면 폴리싱 처리후 크롬도금 처리를 했으며 일반 수도의 수압에서 설치 30초 경과후 최소 400 mm Hg까지 감압시킬 수 있습니다.',
        ],
        specification: [
            {
                id: '1',
                number: 'AKJ-00-01',
                selected: false,
                content: '소',
            },
            {
                id: '2',
                number: 'AKJ-00-02',
                selected: false,
                content: '대',
            },
            {
                id: '3',
                number: 'AKJ-00-03',
                selected: false,
                content: '신형(나사식)',
            },
        ],
    },
    {
        type: 'expandable',
        id: '5',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/expandable%2F5.jpg?alt=media&token=4736f08d-218a-4b10-8122-cf6059568cf4',
        classify: 'Kastech',
        title: 'Autoclave (고압 멸균기)',
        content: [
            '■ 안전성과 신뢰성을 추구한 마이크로 제어방식의 전자동 작동방식 ',
            '',
            '■ Touch Keypad 방식의 조절기를 설치하여 간편한 조작 및 우수한 작업 효율을 얻을 수 있습니다. ',
            '',
            '■ 좁은 공간에서 사용할 수 있는 Compact한 디자인 ',
            '',
            '■ 전원선, 안전핀, 자동밸브, 수동밸브가 한곳으로 매립되어 있어 조작이 간편합니다. ',
            '',
            '■ 1.2Kg 압력이상시 안전핀이 작동할 때 뜨거운 증기로부터 보호합니다. ',
            '',
            '■ 각 모서리를 Round 처리하여 디자인이 수려합니다. ',
            '',
            '■ 수동밸브 손잡이가 상판에 장착되어있어 손쉬운 압력해제가 가능하고 직접적인 밸브 조작이 아니여서 뜨거운 증기로부터 안전합니다.',
        ],
        specification: [
            {
                id: '1',
                number: 'AKJ-44-22',
                selected: false,
                content: 'AUTOCLAVABLE 60 L',
            },
            {
                id: '2',
                number: 'AKJ-44-22A',
                selected: false,
                content: 'AUTOCLAVABLE 80 L',
            },
        ],
    },
    {
        type: 'expandable',
        id: '6',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/expandable%2F6.jpg?alt=media&token=0c811b4c-61fe-4d99-8bab-a834deb4a040',
        classify: '(주)고려에이스과학',
        title: 'S/T AL-Lamp (스텐 알콜램프)',
        content: [
            '스테인레스 재질로 만들어져 유리재질과는 달리 파손으로 인한 위험이 없으며 보다 안정성과 내구성이 강화된 제품입니다',
        ],
        specification: [
            {
                id: '1',
                number: 'AKJ-22-75A',
                selected: false,
                content: '300ml',
            },
        ],
    },
    {
        type: 'expandable',
        id: '7',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/expandable%2F7.jpg?alt=media&token=66e39b13-55ba-413a-9dad-dcfda930118f',
        classify: '(주)고려에이스과학',
        title: 'Micro tube Brush (원심관 솔)',
        content: [],
        specification: [
            {
                id: '1',
                number: 'AKJ-00-36A',
                selected: false,
                content: '',
            },
        ],
    },
    {
        type: 'expandable',
        id: '8',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/expandable%2F8.jpg?alt=media&token=c729f2b4-6095-418d-ba1f-a9286d260f19',
        classify: '(주)고려에이스과학',
        title: 'Cylinder Brush (실린더 솔)',
        content: [
            '실린더용 세척솔',
        ],
        specification: [
            {
                id: '1',
                number: 'AKJ-00-40',
                selected: false,
                content: '대',
            },
            {
                id: '2',
                number: 'AKJ-00-40A',
                selected: false,
                content: '중',
            },
            {
                id: '3',
                number: 'AKJ-00-40B',
                selected: false,
                content: '소',
            },
        ],
    },
    {
        type: 'expandable',
        id: '9',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/expandable%2F9.jpg?alt=media&token=361fcb6a-d8bb-47df-9ec5-42867e53a45e',
        classify: '(주)고려에이스과학',
        title: 'Test tube Brush (시험관 솔)',
        content: [
            '시험관용 세척솔',
        ],
        specification: [
            {
                id: '1',
                number: 'AKJ-00-39',
                selected: false,
                content: '대',
            },
            {
                id: '2',
                number: 'AKJ-00-39A',
                selected: false,
                content: '중',
            },
            {
                id: '3',
                number: 'AKJ-00-39B',
                selected: false,
                content: '소',
            },
        ],
    },
    {
        type: 'expandable',
        id: '10',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/expandable%2F10.jpg?alt=media&token=8e67e4ae-7f17-402e-8b76-969efb850f22',
        classify: '(주)고려에이스과학',
        title: 'Pipet Brush (피펫 솔)',
        content: [
            '피펫용 세척솔',
        ],
        specification: [
            {
                id: '1',
                number: 'AKJ-00-38',
                selected: false,
                content: '대',
            },
        ],
    },
    {
        type: 'expandable',
        id: '11',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/expandable%2F11.jpg?alt=media&token=62eae342-b3b4-4727-8bb9-37e6530bee69',
        classify: '(주)고려에이스과학',
        title: 'Flask Brush (플라스크 솔)',
        content: [
            '플라스크용 세척솔',
        ],
        specification: [
            {
                id: '1',
                number: 'AKJ-00-37',
                selected: false,
                content: '대',
            },
            {
                id: '2',
                number: 'AKJ-00-37A',
                selected: false,
                content: '중',
            },
            {
                id: '3',
                number: 'AKJ-00-37B',
                selected: false,
                content: '소',
            },
        ],
    },
    {
        type: 'expandable',
        id: '12',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/expandable%2F12.jpg?alt=media&token=bd21e235-142e-4323-aeb1-e6d44f365857',
        classify: '(주)고려에이스과학',
        title: 'Buret Brush (뷰렛 솔)',
        content: [
            '뷰렛용 세척솔',
        ],
        specification: [
            {
                id: '1',
                number: 'AKJ-00-36',
                selected: false,
                content: '',
            },
        ],
    },
    {
        type: 'expandable',
        id: '13',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/expandable%2F13.jpg?alt=media&token=d0e9cb9d-cc45-4cc8-b668-3a8a61e3bf33',
        classify: '(주)고려에이스과학',
        title: 'Beaker Brushes (비이커 솔)',
        content: [
            '비이커용 세척솔',
        ],
        specification: [
            {
                id: '1',
                number: 'AKJ-00-35',
                selected: false,
                content: '대',
            },
            {
                id: '2',
                number: 'AKJ-00-35A',
                selected: false,
                content: '중',
            },
            {
                id: '3',
                number: 'AKJ-00-35B',
                selected: false,
                content: '소',
            },
        ],
    },
    {
        type: 'expandable',
        id: '14',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/expandable%2F14.jpg?alt=media&token=4d083f79-c807-446d-aad8-fe1279d4e6fc',
        classify: '(주)고려에이스과학',
        title: 'Blower (이연구)',
        content: [
            '간단한 Gas Sampling 및 Pumping 작업 ',
            '자동뷰렛에 사용합니다',
        ],
        specification: [
            {
                id: '1',
                number: 'AKJ-00-94',
                selected: false,
                content: '',
            },
        ],
    },
    {
        type: 'expandable',
        id: '15',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/expandable%2F15.jpg?alt=media&token=238cf6b9-b11a-494a-9a4c-b79d579aade6',
        classify: '(주)고려에이스과학',
        title: 'Carboy with spigots (증류수 보관통)',
        content: [
            '■ 증류수의 보관 및 일정량을 소분하여 사용할 때 쓰는 용기로써 사용시 편리함을 위하여 하단부에 콕크가 부착되어 있습니다. 본체는 폴리에칠렌 재질과 뚜껑과 콕크는 폴리프로필렌 재질로 구성되어 있습니다.',
        ],
        specification: [
            {
                id: '1',
                number: 'AKJ-00-06',
                selected: false,
                content: '10L',
            },
            {
                id: '2',
                number: 'AKJ-00-07',
                selected: false,
                content: '20L',
            },
            {
                id: '3',
                number: 'AKJ-00-08',
                selected: false,
                content: '40L',
            },
        ],
    },
    {
        type: 'expandable',
        id: '16',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/expandable%2F16.jpg?alt=media&token=e773bd6d-c3db-4f66-bf2c-7c796feb5154',
        classify: '(주)고려에이스과학',
        title: 'S/T Wire Wash Bottle Carrier (세척병운반대)',
        content: [
            '■ 가벼운 스텐 와이어 제품으로 6개의 세척병을 운반할 수 있으며 홀의 직경은 75mm입니다.',
            '',
            '■ 운반손잡이가 부착되어 이동이 용이합니다.',
            '',
            '■ BOD Bottle 운반대로도 사용가능 합니다',
        ],
        specification: [
            {
                id: '1',
                number: 'AKJ-22-88',
                selected: false,
                content: '6홀',
            },
        ],
    },
    {
        type: 'expandable',
        id: '17',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/expandable%2F17.jpg?alt=media&token=eb05fa4c-508f-4cb0-a95c-a3368ecfd6c5',
        classify: '(주)고려에이스과학',
        title: 'Labeled Wash Bottles (라벨 세척병)',
        content: [
            '■ 광구 타입 세척병에 구별이 용이하도록 인쇄를 한 제품입니다.',
            '',
            '■ 용매에도 잘 지워지지 않는 특수 인쇄를 하였습니다',
        ],
        specification: [
            {
                id: '1',
                number: 'AKJ-30-00A',
                selected: false,
                content: '500ml (Aeton)',
            },
            {
                id: '2',
                number: 'AKJ-30-00E',
                selected: false,
                content: '500ml (Ehanol)',
            },
            {
                id: '3',
                number: 'AKJ-30-00M',
                selected: false,
                content: '500ml (Methanol)',
            },
            {
                id: '4',
                number: 'AKJ-30-00W',
                selected: false,
                content: '500ml (Water)',
            },
        ],
    },
    {
        type: 'expandable',
        id: '18',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/expandable%2F18.jpg?alt=media&token=d9d76ab9-9840-487d-91ae-685bab3a3f1a',
        classify: '(주)고려에이스과학',
        title: 'Wide Mouth Wash Bottles (광구 세척병)',
        content: [
            '■ 몸체는 폴리에칠렌 그리고 캡부분은 폴리 프로필렌으로 제작되어 약품이나 용매에 영향을 받지 않고 사용 하실 수 있습니다.',
            '',
            '■ 캡부분은 일체형으로 제작되어 기밀이 유지되며 입구가 광구인 타입으로 액체의 주입이 쉽습니다.',
        ],
        specification: [
            {
                id: '1',
                number: 'AKJ-22-97',
                selected: false,
                content: '500ml',
            },
            {
                id: '2',
                number: 'AKJ-22-98',
                selected: false,
                content: '1000ml',
            },
        ],
    },
    {
        type: 'expandable',
        id: '19',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/expandable%2F19.jpg?alt=media&token=ae16fc45-2715-4347-86d1-fda1d84dc746',
        classify: '(주)고려에이스과학',
        title: 'Wash Bottles (세척병 신형)',
        content: [
            '■ 몸체에 분주기가 붙은 일체형 세척병으로 병안에 잔류액이 남지 않는것이 특징입니다.',
            '',
            '■ 분주용 팁은 원하는 양에 따라 팁 끝부분을 칼로 자르시면 편리하게 용량을 조절 하실 수 있습니다.',
        ],
        specification: [
            {
                id: '1',
                number: '561120',
                selected: false,
                content: '',
            },
        ],
    },
    {
        type: 'expandable',
        id: '20',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/expandable%2F20.jpg?alt=media&token=fe48b4e9-a304-47e5-b5ac-18aed5ac84ba',
        classify: '(주)고려에이스과학',
        title: 'Wash Bottles (세척병)',
        content: [],
        specification: [
            {
                id: '1',
                number: 'AKJ-22-85',
                selected: false,
                content: '250 ml',
            },
            {
                id: '2',
                number: 'AKJ-22-86',
                selected: false,
                content: '500 ml',
            },
            {
                id: '3',
                number: 'AKJ-22-87',
                selected: false,
                content: '1000 ml',
            },
        ],
    },
    {
        type: 'expandable',
        id: '21',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/expandable%2F21.jpg?alt=media&token=b0b83d41-ba9d-40de-960c-bab80a7a8016',
        classify: '(주)고려에이스과학',
        title: 'S/T Beakers (스텐 비이커)',
        content: [
            '■ 스테인레스 27종으로 제작되어 녹이 슬거나 부식이 잘 되지 않습니다.',
            '',
            '■ 내부와 외부는 폴리싱 처리를 하였으며 외부와 내부에도 몰드 눈금을 하여 용량의 표시를 볼 수 있게 만들었습니다.',
            '',
            '■ 사용시 편리를 위하여 500ml 이상은 손잡이가 부착되어 있는것과 없는것이 있습니다.',
        ],
        specification: [
            {
                id: '1',
                number: 'AKJ-23-08A',
                selected: false,
                content: '100ml',
            },
            {
                id: '2',
                number: 'AKJ-23-08B',
                selected: false,
                content: '200ml',
            },
            {
                id: '3',
                number: 'AKJ-23-08C',
                selected: false,
                content: '300ml',
            },
            {
                id: '4',
                number: 'AKJ-23-08',
                selected: false,
                content: '500ml',
            },
            {
                id: '5',
                number: 'AKJ-23-09',
                selected: false,
                content: '500ml (H)',
            },
            {
                id: '6',
                number: 'AKJ-23-10',
                selected: false,
                content: '1L (H)',
            },
            {
                id: '7',
                number: 'AKJ-23-10A',
                selected: false,
                content: '1L',
            },
            {
                id: '8',
                number: 'AKJ-23-11',
                selected: false,
                content: '2L (H)',
            },
            {
                id: '9',
                number: 'AKJ-23-11A',
                selected: false,
                content: '2L',
            },
            {
                id: '10',
                number: 'AKJ-23-12',
                selected: false,
                content: '3L (H)',
            },
            {
                id: '11',
                number: 'AKJ-23-12A',
                selected: false,
                content: '3L',
            },
        ],
    },
    {
        type: 'expandable',
        id: '22',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/expandable%2F22.jpg?alt=media&token=53a4c6af-2ba5-4373-8621-60f5a4e6926d',
        classify: '(주)고려에이스과학',
        title: 'Plastic Beakers (플라스틱 비이커)',
        content: [
            '■ 폴리프로필렌 재질로 내산, 내알카리 등 화학적 내성이 있으며 유기용매 사용시에도 제품에 별다른 영향을 받지 않습니다. ',
            '본 제품은 증기멸균기로 멸균이 가능하며 121℃ 이상의 온도 사용은 제품에 변형이 오므로 사용을 금합니다. ',
            '제품의 투명도를 개선하기 위하여 고급 소재인 투명 폴리프로필렌을 사용하였습니다.',
        ],
        specification: [
            {
                id: '1',
                number: 'AKJ-00-09B',
                selected: false,
                content: '30 ml',
            },
            {
                id: '2',
                number: 'AKJ-00-09A',
                selected: false,
                content: '50 ml',
            },
            {
                id: '3',
                number: 'AKJ-00-09',
                selected: false,
                content: '100 ml',
            },
            {
                id: '4',
                number: 'AKJ-00-10',
                selected: false,
                content: '250 ml',
            },
            {
                id: '5',
                number: 'AKJ-00-11',
                selected: false,
                content: '500 ml',
            },
            {
                id: '6',
                number: 'AKJ-00-12A',
                selected: false,
                content: '500 ml (H)',
            },
            {
                id: '7',
                number: 'AKJ-00-12',
                selected: false,
                content: '1000 ml (H)',
            },
            {
                id: '8',
                number: 'AKJ-00-13',
                selected: false,
                content: '2000 ml (H)',
            },
            {
                id: '9',
                number: 'AKJ-00-14',
                selected: false,
                content: '3000 ml (H)',
            },
            {
                id: '10',
                number: 'AKJ-00-15',
                selected: false,
                content: '5000 ml (H)',
            },
        ],
    },
    {
        type: 'expandable',
        id: '23',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/expandable%2F23.jpg?alt=media&token=c39ae19f-f505-46ef-a214-dd099c2b4e0e',
        classify: '(주)고려에이스과학',
        title: 'Water Baths (중탕전)',
        content: [
            '■ 동재질로 만들어진 중탕전은 직접가열이 아닌 간접으로 가열하는 중탕 시 사용되는 제품입니다.',
            '',
            '■ 윗부분의 뚜껑이 여러 개로 나누어져 있어서 크기에 맞게 사용하면 됩니다.',
        ],
        specification: [
            {
                id: '1',
                number: 'AKJ-22-81',
                selected: false,
                content: '지름 15cm',
            },
            {
                id: '2',
                number: 'AKJ-22-82',
                selected: false,
                content: '지름 18cm',
            },
            {
                id: '3',
                number: 'AKJ-22-83',
                selected: false,
                content: '지름 21cm',
            },
        ],
    },
    {
        type: 'expandable',
        id: '24',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/expandable%2F24.jpg?alt=media&token=494ba7bd-90a9-4cd4-9832-3e9d094c02a9',
        classify: '(주)고려에이스과학',
        title: 'Test Tube Baskets (스텐 시험관망)',
        content: [
            '■ 시험관의 세척 및 보관에 사용하며 초자류의 건조시 사용이 편리합니다.',
            '',
            '■ 스테인레스 재질로 만들어져 약품에 부식되지 않으며 견고하게 만들어져 파손의 우려가 적습니다.',
            '',
            '■ 규격외 제품도 제작이 가능합니다',
        ],
        specification: [
            {
                id: '1',
                number: 'AKJ-22-76',
                selected: false,
                content: '15 * 15 cm',
            },
            {
                id: '2',
                number: 'AKJ-22-77',
                selected: false,
                content: '18 * 18 cm',
            },
            {
                id: '3',
                number: 'AKJ-22-78',
                selected: false,
                content: '20 * 20 cm',
            },
            {
                id: '4',
                number: 'AKJ-22-79',
                selected: false,
                content: '25 * 25 cm',
            },
            {
                id: '5',
                number: 'AKJ-22-80',
                selected: false,
                content: '30 * 30 cm',
            },
        ],
    },
    {
        type: 'expandable',
        id: '25',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/expandable%2F25.jpg?alt=media&token=071b0879-c061-4694-908f-ded88b2e1760',
        classify: '(주)고려에이스과학',
        title: 'Teflon Gas Bags (테프론 가스 백)',
        content: [
            '■ 부식성 가스포집을 위해 테프론(PVDF)의 재질로 되어 있으며 ON&amp;OFF로 작동되는 테프론 콕크가 부착되어 보다 편리하게 가스의 포집과 분석을 위한 채집을 할 수 있습니다.',
            '',
            '■ 다양한 사이즈로 구성되어 작은 용량과 큰 용량을 위한 사이즈를 구비하고 있습니다. (500ml~20L)',
        ],
        specification: [
            {
                id: '1',
                number: 'AKJ-00-29A',
                selected: false,
                content: '500ml 15*18cm',
            },
            {
                id: '2',
                number: 'AKJ-00-29B',
                selected: false,
                content: '1L 15*25cm',
            },
            {
                id: '3',
                number: 'AKJ-00-32A',
                selected: false,
                content: '2L 20*25cm',
            },
            {
                id: '4',
                number: 'AKJ-00-32B',
                selected: false,
                content: '3L 25*30cm',
            },
            {
                id: '5',
                number: 'AKJ-00-32C',
                selected: false,
                content: '5L 25*40cm',
            },
            {
                id: '6',
                number: 'AKJ-00-32D',
                selected: false,
                content: '10L 35*50cm',
            },
            {
                id: '7',
                number: 'AKJ-00-32E',
                selected: false,
                content: '20L 50*50cm',
            },
        ],
    },
    {
        type: 'expandable',
        id: '26',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/expandable%2F26.jpg?alt=media&token=47f4753d-0acc-43d1-a3d2-01de98efce8b',
        classify: '(주)고려에이스과학',
        title: 'Biohazard Bag stands (백 스탠드)',
        content: [
            '■ 간단히 접고 펼칠 수 있도록 만들어진 이 제품은 백의 규격에 맞도록 제작되었고 부식되지 않도록 폴리에칠렌 코팅으로 처리하였으며 별도의 바닥 받침대 부분이 있어 사용이 편리합니다.',
        ],
        specification: [
            {
                id: '1',
                number: 'AKJ-00-28A',
                selected: false,
                content: '소',
            },
            {
                id: '2',
                number: 'AKJ-00-28B',
                selected: false,
                content: '중',
            },
            {
                id: '3',
                number: 'AKJ-00-28C',
                selected: false,
                content: '대',
            },
        ],
    },
    {
        type: 'expandable',
        id: '27',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/expandable%2F27.jpg?alt=media&token=f02bae96-21f8-4c5f-983e-4a5371722625',
        classify: '(주)고려에이스과학',
        title: 'Biohazard Bags (멸균 비닐백) -Korea-',
        content: [
            '■ 적색에 HDPE(고밀도 폴리에칠렌)로 만들어져 증기멸균(121℃)을 하여 사용합니다.',
            '',
            '■ 검정색의 바이오 헤저드 심블이 그려져 이쓰며 두께는 0.32mm 입니다.',
        ],
        specification: [
            {
                id: '1',
                number: 'AKJ-00-30A',
                selected: false,
                content: '36 * 48 cm (소)',
            },
            {
                id: '2',
                number: 'AKJ-00-30B',
                selected: false,
                content: '48 * 58 cm (중)',
            },
            {
                id: '3',
                number: 'AKJ-00-30C',
                selected: false,
                content: '64 * 89 cm (대)',
            },
        ],
    },
    {
        type: 'expandable',
        id: '28',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/expandable%2F28.jpg?alt=media&token=428bd439-463a-4d75-9ff8-242094e4a6eb',
        classify: 'Bel.Art Scienceware',
        title: 'Gas Sampling Bulbs (가스 샘플링 벌브) -USA-',
        content: [
            '■ 폴리프로필렌으로 성형된 이 채집병은 끝이 반구 모양으로 되어 있어 공기의 흐름이 용이하고 폴리프로필렌으로 된 콕크에는 테프론 마개가 들어있어 공기 기밀이 뛰어나다.',
            '',
            '■ 끝의 콕크에는 6.4mm에서 9.5mm까지 관을 꽂을 수 있다. 병의 몸체는 길이가 222mm, 외경이 51mm이고 권장 최대사용압력은 15PSI이다.',
            '',
            'A. 한쪽끝은 4mm의 구멍이 있는 콕크로 되어 있고 다른쪽으로 실리콘고무의 격막이 있는 나선형 콕크로 되어 있다. 격막은 여러 번 사용이 가능하며 6개의 격막이 포함되어 있다. 전체길이 29cm.',
            '',
            'B. 한쪽끝은 4mm의 구멍이 있는 콕크로 되어 있고 다른쪽은 4mm의 구멍이 있는 3방향 콕크로 되어있다. 3방향 콕크는 가스가 양쪽으로 나가게 할 수 있다. 전체길이는 32cm.',
            '',
            'C. 양쪽끝이 4mm의 구멍이 있는 콕크로 되어 있고 전체길이는 32cm.',
        ],
        specification: [
            {
                id: '1',
                number: 'AKJ-F19953',
                selected: false,
                content: '(A) - 2way Stopcocks',
            },
            {
                id: '2',
                number: 'AKJ-F19955',
                selected: false,
                content: '(B) - 3way Stopcocks',
            },
            {
                id: '3',
                number: 'AKJ-F19957',
                selected: false,
                content: '(C) - Rubber Septum-',
            },
        ],
    },
    {
        type: 'expandable',
        id: '29',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/expandable%2F29.jpg?alt=media&token=bdc9db31-ceb7-42a5-8554-f1cf928f474e',
        classify: 'Bel.Art Scienceware',
        title: 'Autoclavable Carboy with Spigots (증류수통-멸균가능) -USA-',
        content: [
            '■ Rugged polypropylene carboys with a molded-in bung fo accept the polypropylene spigot (included) that can be operated with one hand. The 83mm polypropylene buttress screw cap has a buitt in silicone gasket for positive seal. Large handles help with pouring. They have excellent chemical resistance and are ideal for storing sterile solutions or sterile water. Carboys also available without spigot. Steam autoclavable 121℃. When autoclaving, do not engage cap threads.',
        ],
        specification: [
            {
                id: '1',
                number: 'AKJ-F11846-0025',
                selected: false,
                content: '10L',
            },
            {
                id: '2',
                number: 'AKJ-F11846-0050',
                selected: false,
                content: '20L',
            },
        ],
    },
    {
        type: 'expandable',
        id: '30',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/expandable%2F30.jpg?alt=media&token=39bd1805-3395-4ea8-a6ef-befefdaea141',
        classify: 'Bel.Art Scienceware',
        title: 'Autoclavable Carboy with Spigots (증류수통-멸균가능) -USA-',
        content: [
            '■ This polypropylene carboy has a half-fum spigot and a folding mefal carrying handle. A molded fhread accepts the spigot. The large diameter screw cap has a silicone gasket for good sealing and provides a neck opening of 82.5mm(31/4"). Good chemical resisfance allows the carboy to be used to dispense sterile water, solutions and medla. Rectangular shape helps save shelf space. Dimensions are 19×21×36cm H (71/2×81/4×14" high). Steam autoclavable at 121℃(250℉). When autoclaving, do not engage cap threads.',
        ],
        specification: [
            {
                id: '1',
                number: 'AKJ-F11849-0025',
                selected: false,
                content: '10L',
            },
        ],
    },
    {
        type: 'expandable',
        id: '31',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/expandable%2F31.jpg?alt=media&token=8a82616e-f2ae-4d5e-8681-61d92da3feb1',
        classify: 'Bel.Art Scienceware',
        title: 'Dispensing Jug Rack (디스펜싱 저그 랙) -USA-',
        content: [
            '■ 디스펜싱 저그용 전용랙입니다. 조립형식으로 구성되어 설치 및 조립이 용이합니다.',
            '',
            '■ 사각형식으로 만들어져 공간절약을 할 수 있으며, 다단형식이라 원하는 숫자 만큼 조립하여 설치할 수 있습니다.',
            '',
            '■ 모두 다섯 개의 디스펜싱 저그를 설치할 수 있습니다.',
        ],
        specification: [
            {
                id: '1',
                number: 'AKJ-H11851 - 0000',
                selected: false,
                content: '4단',
            },
        ],
    },
    {
        type: 'expandable',
        id: '32',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/expandable%2F32.jpg?alt=media&token=6c2838ee-8320-47e1-bbd5-b9c8c1e9b5e8',
        classify: 'Bel.Art Scienceware',
        title: 'Dispensing Jug (디스펜싱 저그) -USA-',
        content: [
            '■ 몸체 및 콕크 그리고 뚜껑 부분이 모두 폴리프로필렌, 폴리에칠렌 재질로 만들어져 약품에 강합니다.',
            '',
            '■ 사각 몸체로 구성되어 설치시 안정적이며 전용 랙을 사용하면 여러 개를 포개어 사용할 수 있어 공간절약에 합리적입니다.',
        ],
        specification: [
            {
                id: '1',
                number: 'AKJ-H11850 - 0000',
                selected: false,
                content: '20L',
            },
        ],
    },
    {
        type: 'expandable',
        id: '33',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/expandable%2F33.jpg?alt=media&token=b7ecb2e1-45a7-4265-aa9f-86cf75eec2e7',
        classify: 'Bel.Art Scienceware',
        title: 'Emergency Eye Wash Bottles (아이워시 버틀) -USA-',
        content: [
            '■ 응급시 빠르고 정확하게 눈의 상처를 씻어줄 수 있게 만들어진 세척병으로 파손위험이 없고 쉽게 누를 수 있도록 폴리에틸렌으로 만들어져 있으며 EYECUP과 SNAPON CAP이 달려 있다.',
            '',
            '■ EYECUP에는 액체를 눈에 부드럽게 뿌릴 수 있도록 구멍이 뚫린 판이 달려 있으며, 환기구는 오염된 액체가 다시 병 속으로 들어가는 것을 방지해 준다.',
        ],
        specification: [
            {
                id: '1',
                number: 'AKJ-F24850',
                selected: false,
                content: '500ml',
            },
            {
                id: '2',
                number: 'AKJ-F24851',
                selected: false,
                content: '1000ml',
            },
        ],
    },
    {
        type: 'expandable',
        id: '35',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/expandable%2F35.jpg?alt=media&token=7aff524e-1716-48c1-9843-928d1d4c1064',
        classify: 'Bel.Art Scienceware',
        title: 'Wide Mouth Wash Bottles (광구 세척병) -USA-',
        content: [],
        specification: [
            {
                id: '1',
                number: 'AKJ-F11625-0500',
                selected: false,
                content: '500ml',
            },
            {
                id: '2',
                number: 'AKJ-F11625-1000',
                selected: false,
                content: '1000ml',
            },
        ],
    },
    {
        type: 'expandable',
        id: '36',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/expandable%2F36.jpg?alt=media&token=fe154b9e-8005-4f73-949d-37aa5b9548b0',
        classify: 'Bel.Art Scienceware',
        title: 'Narrow Mouth Wash Bottles (세구 세척병) -USA-',
        content: [
            '■ Red, Yellow, Green, Blue 등 4가지 색깔로 구성되어 있으며 저압 폴리에칠렌으로 만들어져 분주나 복원시 작업이 부드럽습니다.',
            '',
            '■ 몸체와 뚜껑부분에 나사는 견고하게 제작되어 공기가 새거나 액체의 누수가 일어나는 일이 없습니다.',
        ],
        specification: [
            {
                id: '1',
                number: 'AKJ-F11613-0250',
                selected: false,
                content: '250 ml',
            },
            {
                id: '2',
                number: 'AKJ-F11613-0500',
                selected: false,
                content: '500 ml',
            },
            {
                id: '3',
                number: 'AKJ-F11613-1000',
                selected: false,
                content: '1000 ml',
            },
        ],
    },
    {
        type: 'expandable',
        id: '37',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/expandable%2F37.jpg?alt=media&token=f6b25c0d-c004-4121-a4d2-ca011125f1ca',
        classify: 'Bel.Art Scienceware',
        title: 'Wash Bottle Carrier (세척병 운반대) -USA-',
        content: [
            '■ 가벼운 플라스틱 재질로 만들어져 있으며 상부는 손잡이가 부착되어 이동이 용이합니다.',
            '',
            '■ 부식에 강한 폴리프로필렌 재질이며 6개의 세척병을 운반 및 보관할 수 있습니다.',
        ],
        specification: [
            {
                id: '1',
                number: 'AKJ-F11640-0001',
                selected: false,
                content: '6 Hole',
            },
        ],
    },
    {
        type: 'expandable',
        id: '38',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/expandable%2F38.jpg?alt=media&token=289976b5-4f59-41bd-8186-013fa439b79b',
        classify: 'Bel.Art Scienceware',
        title: 'Dispensing Bottles (디스펜싱 버틀) -USA-',
        content: [
            '■ 폴리에칠렌 재질로 만들어져 용매 및 각종 약품에도 영향을 받지 않습니다.',
            '',
            '■ 적은 양을 드로핑할때 사용하며 사용 용도에 맞도록 여러가지 사이즈가 갖추어져 있습니다.',
            '',
            '■ 사용 후 보관을 위한 적색의 마개가 부착되어 있습니다.',
        ],
        specification: [
            {
                id: '1',
                number: 'AKJ-F11637-0001',
                selected: false,
                content: '30 ml',
            },
            {
                id: '2',
                number: 'AKJ-F11637-0002',
                selected: false,
                content: '60 ml',
            },
            {
                id: '3',
                number: 'AKJ-F11637-0004',
                selected: false,
                content: '125 ml',
            },
            {
                id: '4',
                number: 'AKJ-F11637-0006',
                selected: false,
                content: '185 ml',
            },
            {
                id: '5',
                number: 'AKJ-F11637-0008',
                selected: false,
                content: '250 ml',
            },
        ],
    },
    {
        type: 'expandable',
        id: '39',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/expandable%2F39.jpg?alt=media&token=4eaec911-03e0-4130-a41e-4d8aed57a20c',
        classify: 'Bel.Art Scienceware',
        title: 'Polystop Dropper Bottles (폴리스탑 드로퍼 버틀) -USA-',
        content: [
            '■ 유리 재질의 병과 플라스틱 스토퍼 그리고 PVC 재질의 스포이드로 구성되어 있습니다.',
            '',
            '■ 병 입구와 스토퍼 부분은 조인트로 처리되어 있으며, 부드러운 스포이드는 드로핑시 작업이 쉬우며 세척하기도 간편합니다.',
        ],
        specification: [
            {
                id: '1',
                number: 'AKJ-F11604-0030',
                selected: false,
                content: '30 ml',
            },
            {
                id: '2',
                number: 'AKJ-F11604-0060',
                selected: false,
                content: '60 ml',
            },
            {
                id: '3',
                number: 'AKJ-F11604-0125',
                selected: false,
                content: '125 ml',
            },
        ],
    },
    {
        type: 'expandable',
        id: '40',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/expandable%2F40.jpg?alt=media&token=70394264-e225-4d3e-b7c6-b274f66f4098',
        classify: 'Bel.Art Scienceware',
        title: 'Lab-Mat (랩매트)/Safety Red For Biohazard -USA-',
        content: [
            '■ 랩매트(Labmat) : 작업대 표면을 얼룩지는 것이나 쏟아지는 것 등으로부터 보호해주고 청소를 편하게 해준다. 매트의 뒷면은 탄력성있는 폴리에틸렌막으로 되어 있어 미끄럼을 방지해주고 용액으로 작업대가 젖는 것을 막아준다. ',
            '',
            '매트의 윗면은 매우 흡수성이 높아 물, 염료나 부식성있는 화학약품, 방사선약품 등의 사용시 유용하다. 매트는 사용후 말아서 버리면 된다. 매트는 50.8cm의 폭에 15M(50Feet) 길이의 두루마리로 되어 있으며 사용시는 통에서 필요한 길이만큼 빼서 가위 등으로 잘라 쓰면 된다.',
        ],
        specification: [
            {
                id: '1',
                number: 'AKJ-F24675-0000',
                selected: false,
                content: '50cm * 50ft',
            },
            {
                id: '2',
                number: 'AKJ-F24675-1000',
                selected: false,
                content: '50cm * 50ft (Red)',
            },
        ],
    },
    {
        type: 'expandable',
        id: '41',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/expandable%2F41.jpg?alt=media&token=25c43ac0-7119-47db-88ef-b544f7b86241',
        classify: 'Bel.Art Scienceware',
        title: 'TPX Handle Beakers (핸들 비이커) -USA-',
        content: [
            '■Graduated Pitchers (TPX)',
            '',
            '투명하고 화학적 내성이 있으며 섭씨 177℃까지 견딜 수 있습니다.',
        ],
        specification: [
            {
                id: '1',
                number: 'AKJ-F28982',
                selected: false,
                content: '500ml',
            },
            {
                id: '2',
                number: 'AKJ-F28983',
                selected: false,
                content: '1000ml',
            },
            {
                id: '3',
                number: 'AKJ-F28984',
                selected: false,
                content: '2000ml',
            },
        ],
    },
    {
        type: 'expandable',
        id: '42',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/expandable%2F42.jpg?alt=media&token=ca373e0f-da29-4a30-a540-10f4da681271',
        classify: 'Bel.Art Scienceware',
        title: 'Handle Beakers(PP) (핸들 비이커) -USA-',
        content: [
            '■Graduated Pitchers (PP)',
            '',
            '이 그리핀 타입의 비이커는 반투명하고 화학적 내성이 있으며 눈금의 오차는 약 5% 내외이며 멸균은 증기멸균기로 섭씨 121℃에서 할 수 있습니다.',
        ],
        specification: [
            {
                id: '1',
                number: 'AKJ-F28990',
                selected: false,
                content: '500ml',
            },
            {
                id: '2',
                number: 'AKJ-F28991',
                selected: false,
                content: '1000ml',
            },
            {
                id: '3',
                number: 'AKJ-F28992',
                selected: false,
                content: '2000ml',
            },
            {
                id: '4',
                number: 'AKJ-F28993',
                selected: false,
                content: '3000ml',
            },
        ],
    },
    {
        type: 'expandable',
        id: '43',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/expandable%2F43.jpg?alt=media&token=881b4805-1820-4fb3-8124-9c580ae11c2f',
        classify: 'Bel.Art Scienceware',
        title: 'Biohazard Autoclave Gloves (멸균 글로브) -USA-',
        content: [
            '■ 증기멸균기나 드라잉 오븐 등 뜨거운 실험용구를 꺼낼시 사용합니다.',
            '',
            '■ 100% 면으로 만들어져 착용감이 좋으며 사용온도는 232℃입니다.',
            '',
            '■ 사용 용도에 따라 멸균하여 사용하셔도 되며 길이는 33cm와 47cm 두가지로 공급되어집니다.',
        ],
        specification: [
            {
                id: '1',
                number: 'AKJ-H13201-0000',
                selected: false,
                content: '33cm',
            },
            {
                id: '2',
                number: 'AKJ-H13201-0001',
                selected: false,
                content: '47cm',
            },
        ],
    },
    {
        type: 'expandable',
        id: '44',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/expandable%2F44.jpg?alt=media&token=6aedb5ae-fae2-49cd-9319-2a22049e8d62',
        classify: 'Bel.Art Scienceware',
        title: 'Biohazard Disposable Bags (일회용 바이오헤저드 백) -USA_',
        content: [
            '■ 일회용으로 사용하는 멸균백이며 실험실에서 피펫이나 페트리디쉬, 컬쳐 플레이트 멤브라인 휠터 등 여러가지 품목들을 멸균하여 사용할 때 사용합니다.',
            '',
            '■ HMHD 폴리 에칠렌 재질로 만들어져 121℃ 증기 멸균하여 사용합니다.',
            '',
            '■ 적색 바탕에 검은색의 바이오해저드 로고가 새겨져 있으며 100장씩 포장되어 있습니다.',
        ],
        specification: [
            {
                id: '1',
                number: 'AKJ-F13164-1419',
                selected: false,
                content: '36 * 48 cm 100ea/Pack',
            },
            {
                id: '2',
                number: 'AKJ-F13164-1923',
                selected: false,
                content: '48 * 58 cm 100ea/Pack',
            },
            {
                id: '3',
                number: 'AKJ-F13164-2535',
                selected: false,
                content: '64 * 89 cm 100ea/Pack',
            },
            {
                id: '4',
                number: 'AKJ-F13164-3138',
                selected: false,
                content: '97 * 122 cm 100ea/Pack',
            },
        ],
    },
    {
        type: 'expandable',
        id: '45',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/expandable%2F45.jpg?alt=media&token=a4aa9c80-ab52-4abb-ac93-ab1d39120a5e',
        classify: 'Cowie',
        title: 'Teflon Bottles (테프론 버틀) -UK-',
        content: [],
        specification: [
            {
                id: '1',
                number: 'AKJ-CW 00-87',
                selected: false,
                content: 'Teflon Bottle 50ml',
            },
            {
                id: '2',
                number: 'AKJ-CW 00-88',
                selected: false,
                content: 'Teflon Bottle 100ml',
            },
            {
                id: '3',
                number: 'AKJ-CW 00-90',
                selected: false,
                content: 'Teflon Bottle 250ml',
            },
            {
                id: '4',
                number: 'AKJ-CW 00-91',
                selected: false,
                content: 'Teflon Bottle 500ml',
            },
            {
                id: '5',
                number: 'AKJ-CW 00-92',
                selected: false,
                content: 'Teflon Bottle 1000ml',
            },
        ],
    },
    {
        type: 'expandable',
        id: '46',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/expandable%2F46.jpg?alt=media&token=d49a9df5-45d5-4f9d-a4f5-87909f190343',
        classify: 'Cowie',
        title: 'Teflon Beakers Covers (테프론 비이커 커버) -UK-',
        content: [],
        specification: [
            {
                id: '1',
                number: 'AKJ-CW 00-76',
                selected: false,
                content: 'Teflon Beaker Cover Φ 30 mm',
            },
            {
                id: '2',
                number: 'AKJ-CW 00-77',
                selected: false,
                content: 'Teflon Beaker Cover Φ 40 mm',
            },
            {
                id: '3',
                number: 'AKJ-CW 00-78',
                selected: false,
                content: 'Teflon Beaker Cover Φ 50 mm',
            },
            {
                id: '4',
                number: 'AKJ-CW 00-79',
                selected: false,
                content: 'Teflon Beaker Cover Φ 65 mm',
            },
            {
                id: '5',
                number: 'AKJ-CW 00-80',
                selected: false,
                content: 'Teflon Beaker Cover Φ 75 mm',
            },
            {
                id: '6',
                number: 'AKJ-CW 00-81',
                selected: false,
                content: 'Teflon Beaker Cover Φ 80 mm',
            },
            {
                id: '7',
                number: 'AKJ-CW 00-82',
                selected: false,
                content: 'Teflon Beaker Cover Φ 100 mm',
            },
            {
                id: '8',
                number: 'AKJ-CW 00-83',
                selected: false,
                content: 'Teflon Beaker Cover Φ 125 mm',
            },
            {
                id: '9',
                number: 'AKJ-CW 00-84',
                selected: false,
                content: 'Teflon Beaker Cover Φ 150 mm',
            },
        ],
    },
    {
        type: 'expandable',
        id: '47',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/expandable%2F47.jpg?alt=media&token=ab134df7-46d0-479b-9d91-8c976105bf75',
        classify: 'Cowie',
        title: 'Teflon Beakers (테프론 비이커) -UK-',
        content: [
            'Isostatically molded in pure, FDA approved, PTFE',
            'Machined base for good heat transfer',
            '',
            'Molded-in pouring spout',
            '',
            'Totally chemically resistant and inert',
        ],
        specification: [
            {
                id: '1',
                number: 'AKJ-CW 00-68',
                selected: false,
                content: 'Teflon Bellows 10ml',
            },
            {
                id: '2',
                number: 'AKJ-CW 00-69',
                selected: false,
                content: 'Teflon Bellows 25ml',
            },
            {
                id: '3',
                number: 'AKJ-CW 00-70',
                selected: false,
                content: 'Teflon Bellows 50ml',
            },
            {
                id: '4',
                number: 'AKJ-CW 00-71',
                selected: false,
                content: 'Teflon Bellows 100ml',
            },
            {
                id: '5',
                number: 'AKJ-CW 00-72',
                selected: false,
                content: 'Teflon Bellows 250ml',
            },
            {
                id: '6',
                number: 'AKJ-CW 00-73',
                selected: false,
                content: 'Teflon Bellows 500ml',
            },
            {
                id: '7',
                number: 'AKJ-CW 00-74',
                selected: false,
                content: 'Teflon Bellows 1000ml',
            },
            {
                id: '8',
                number: 'AKJ-CW 00-75',
                selected: false,
                content: 'Teflon Bellows 2000ml',
            },
        ],
    },
    {
        type: 'expandable',
        id: '48',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/expandable%2F48.jpg?alt=media&token=d1724bef-6ca5-4db3-b996-f3ea06e39e40',
        classify: 'etc',
        title: 'Wonder Blender (고속분쇄기) -JAPAN-',
        content: [
            '■ 25000 rpm의 초고속 회전과 750W의 강력한 파워 모터는 곡물, 약재, 정제, 광물, 도자기, 목재 등 연질의 시료나 경도가 높은 시료도 분쇄가 가능합니다.',
            '',
            '■ 본체는 견고한 금속으로 만들어 졌으며 용기부는 부식에 강한 스테인레스 재질로 만들어 졌습니다.',
            '',
            '■ 광물, 세라믹, 유리 등의 분쇄는 경화 처리된 커터를 사용하셔야 합니다.',
            '',
            '■ 용기부의 용량은 150ml이며 50g의 시료의 분쇄에 사용되는 시간은 30초가 소요됩니다.',
            '',
            '■ 110V / 50/60Hz, 3.6kg, 134mm×270mm (d×H)',
        ],
        specification: [],
    },
    {
        type: 'expandable',
        id: '49',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/expandable%2F49.jpg?alt=media&token=47454904-ff0a-48d0-882d-94d250e51c34',
        classify: 'etc',
        title: 'Weighing Bottles (플라스틱 평량병) -ITALY-',
        content: [],
        specification: [],
    },
    {
        type: 'expandable',
        id: '50',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/expandable%2F50.jpg?alt=media&token=ffa7a3f0-f4c3-4e7a-9586-4aa6b9871810',
        classify: 'etc',
        title: 'Glass Bead (유리 구슬)',
        content: [
            '■ 사용하기 간편하고 파손방지를 위하여 버틀에 담겨 있습니다.',
            '',
            '■ Sodalime Glass로 제조',
        ],
        specification: [],
    },
    {
        type: 'expandable',
        id: '51',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/expandable%2F51.jpg?alt=media&token=3ba52b20-38d7-4781-b773-0578368098e7',
        classify: 'etc',
        title: 'Tedlar Gas Bags (테드라 가스 백) -USA-',
        content: [
            '■ ON &amp; OFF 밸브가 부착되어 있으며 실리콘 셉터가 있어 샘플채취가 용이합니다.',
            '',
            '■ 사용 가능온도 Max 204도',
        ],
        specification: [],
    },
    {
        type: 'expandable',
        id: '52',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/expandable%2F52.jpg?alt=media&token=35303c1e-7bba-4d36-b1a2-9df981e2fc28',
        classify: 'Kastech',
        title: 'Clean Benchs (안전 작업대)',
        content: [
            '■ 실험실에 무균 상태의 작업 공간 필요시 적합한 장비입니다.',
            '',
            '■ 청정 작업이 필요한 배양실, 의학 제약, 식품, 농업, 신소재 및 전자 산업용 등에 다양하게 사용됩니다.',
            '',
            '■ 99.97% (입자크기 0.3㎛)의 집진 효과를 확보하는 HEPA filfer를 장착하였습니다.',
            '',
            '■ 유해균, 유해물질 취급시 사용자의 안전을 위하여 근본적으로 예방 차단 할수 있는 구조로 설계 제작',
        ],
        specification: [
            {
                id: '1',
                number: 'AKJ-44-21A',
                selected: false,
                content: 'W:1000 D;840 H;1,850',
            },
            {
                id: '2',
                number: 'AKJ-44-21B',
                selected: false,
                content: 'W:1,300 D;840 H;1,850',
            },
            {
                id: '3',
                number: 'AKJ-44-21C',
                selected: false,
                content: 'W:1,600 D;840 H;1,850',
            },
        ],
    },
    {
        type: 'expandable',
        id: '53',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/expandable%2F53.jpg?alt=media&token=11ca92b2-e1ac-4f54-8911-3b17d17f59e3',
        classify: 'Kimble-Kontes',
        title: 'Buret Automatic (자동 뷰렛)',
        content: [
            'Automatic, Serialized and Certified, Three Way PTFE Stopcock, with Reservoir Bottle, Class A',
            '',
            'KIMAX precision bore buret is permanently marked with an individual serial number. Supplied with a Certificate of Graduation Accuracy. Packed complete with a reservoir bottle, U-shaped drying tube, vented connecting tube, rubber squeeze bulb, # 1 one-holed rubber stopper and 1/4 inch I.D. rubber tubing. Stopcock for all sizes is 2. Scale is durable black ceramic enamel. Calibrated to the accuracy requirements found in ASTM Specification E694.',
        ],
        specification: [
            {
                id: '1',
                number: 'AKJ-17124F-10',
                selected: false,
                content: 'Automatic Buret 10 ml',
            },
            {
                id: '2',
                number: 'AKJ-17124F-25',
                selected: false,
                content: 'Automatic Buret 25 ml',
            },
            {
                id: '3',
                number: 'AKJ-17124F-50',
                selected: false,
                content: 'Automatic Buret 50 ml',
            },
        ],
    },
    {
        type: 'expandable',
        id: '54',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/expandable%2F54.jpg?alt=media&token=7bd1a09d-bd77-40a8-8a0c-0870c36a7207',
        classify: 'Kimble-Kontes',
        title: 'Burets KIMMAX (뷰렛)',
        content: [
            'Straight Bore PTFE Stopcock, with Dust Cap',
            '',
            'KIMAX buret with a size 2 PTFE plug. KIM-KAP dust cap is included. Scale is durable black ceramic enamel. Designed from ASTM Specification E287.',
        ],
        specification: [
            {
                id: '1',
                number: 'AKJ-17026F-10',
                selected: false,
                content: 'KIMMAX Burets PTFE Stopcock 10ml',
            },
            {
                id: '2',
                number: 'AKJ-17026F-25',
                selected: false,
                content: 'KIMMAX Burets PTFE Stopcock 25ml',
            },
            {
                id: '3',
                number: 'AKJ-17026F-50',
                selected: false,
                content: 'KIMMAX Burets PTFE Stopcock 50 ml',
            },
        ],
    },
    {
        type: 'expandable',
        id: '55',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/expandable%2F55.jpg?alt=media&token=8aa78a9a-b17c-419c-ba94-4501fe6b1993',
        classify: 'Kimble-Kontes',
        title: 'Media Bottle (메디아 버틀)',
        content: [
            'KIMAX? bottles have enhanced graduations and marking spot are permanent white enamel. This general use bottle is provided with wide opening (approx. 30 mm ID) GL 45 screw thread and supplied with linerless autoclavable (140°C max) polypropylene blue cap. Bottle design includes a clear (natural) drip free polypropylene pour ring which is replaceable.',
        ],
        specification: [
            {
                id: '1',
                number: 'AKJ-14395-100',
                selected: false,
                content: 'GL 45 Media / Storage with Blue Cap 100ml',
            },
            {
                id: '2',
                number: 'AKJ-14395-250',
                selected: false,
                content: 'GL 45 Media / Storage with Blue Cap 250ml',
            },
            {
                id: '3',
                number: 'AKJ-14395-500',
                selected: false,
                content: 'GL 45 Media / Storage with Blue Cap 500ml',
            },
            {
                id: '4',
                number: 'AKJ-14395-1000',
                selected: false,
                content: 'GL 45 Media / Storage with Blue Cap 1000ml',
            },
            {
                id: '5',
                number: 'AKJ-14395-2000',
                selected: false,
                content: 'GL 45 Media / Storage with Blue Cap 2000ml',
            },
            {
                id: '6',
                number: 'AKJ-14395-5000',
                selected: false,
                content: 'GL 45 Media / Storage with Blue e Cap 5000ml',
            },
            {
                id: '7',
                number: 'AKJ-14395-10000',
                selected: false,
                content: 'GL 45 Media / Storage with Blue Cap 10000ml',
            },
        ],
    },
    {
        type: 'expandable',
        id: '56',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/expandable%2F56.jpg?alt=media&token=046f1565-cc04-457f-bc62-31abc7871757',
        classify: 'Kimble-Kontes',
        title: 'Bottle, Dropping',
        content: [
            'KIMAX bottle is provided with a medium length pipet dropper and rubber nipple. Bottle is suitable for use in determining the oil absorption of pigments (ASTM D281). The 125 mL size is KG-35 ASTM 438 Type 1 Class B glass whereas all others are KG-33 ASTM 438 Type 1 Class A. The 30 and 60 mL sizes are designed from Federal Specification NNN-B-1194, Type II, Class 2, Grade B requirements.',
        ],
        specification: [
            {
                id: '1',
                number: 'AKJ-15035 15',
                selected: false,
                content: 'Bottle, Dropping 15ml',
            },
            {
                id: '2',
                number: 'AKJ-15035 30',
                selected: false,
                content: 'Bottle, Dropping 30 ml',
            },
            {
                id: '3',
                number: 'AKJ-15035 60',
                selected: false,
                content: 'Bottle, Dropping 60 ml',
            },
            {
                id: '4',
                number: 'AKJ-15035 125',
                selected: false,
                content: 'Bottle, Dropping 125 ml',
            },
        ],
    },
    {
        type: 'expandable',
        id: '57',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/expandable%2F57.jpg?alt=media&token=4cf5774a-0fa6-4971-8a11-bc1b4e048819',
        classify: 'Kimble-Kontes',
        title: 'Kimble Low Form Beakers',
        content: [
            'Griffin, Low Form, Double Scale, Color',
            'Made of KIMAX KG-33 glass. All sizes have a durable, color, matte finish marking area for use with an ordinary pencil. An easy-to-read double scale in color is provided on all sizes. Designed from ASTM Specification E960, Type I requirements.',
        ],
        specification: [
            {
                id: '1',
                number: 'AKJ-14000 30',
                selected: false,
                content: 'Griffin, Low Form Beaker, 30 ml',
            },
            {
                id: '2',
                number: 'AKJ-14000 50',
                selected: false,
                content: 'Griffin, Low Form Beaker, 50 ml',
            },
            {
                id: '3',
                number: 'AKJ-14000 100',
                selected: false,
                content: 'Griffin, Low Form Beaker, 100 ml',
            },
            {
                id: '4',
                number: 'AKJ-14000 250',
                selected: false,
                content: 'Griffin, Low Form Beaker, 250 ml',
            },
            {
                id: '5',
                number: 'AKJ-14000 600',
                selected: false,
                content: 'Griffin, Low Form Beaker, 600 ml',
            },
            {
                id: '6',
                number: 'AKJ-14000 1000',
                selected: false,
                content: 'Griffin, Low Form Beaker, 1000 ml',
            },
            {
                id: '7',
                number: 'AKJ-14000 2000',
                selected: false,
                content: 'Griffin, Low Form Beaker, 2000 ml',
            },
            {
                id: '8',
                number: 'AKJ-14000 4000',
                selected: false,
                content: 'Griffin, Low Form Beaker, 4000 ml',
            },
        ],
    },
    {
        type: 'expandable',
        id: '58',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/expandable%2F58.jpg?alt=media&token=827edc96-f01c-4128-96d2-6c96dd051613',
        classify: 'Kimble-Kontes',
        title: 'KIMBLE BOD Bottles (비오디 버틀) -USA-',
        content: [
            '■ Method 5210-B, ASTM E438, TYPE I',
            '',
            '■ BOD 분석을 위한 샘플보관과 배양을 위한 최적의 제품',
            '',
            '■ KIMBLE 버틀은 Water Seal 방식으로 배양시 공기의 유입이 차단.',
            '',
            '[ 24ea / case ]',
        ],
        specification: [
            {
                id: '1',
                number: 'AKJ-15070 - 00',
                selected: false,
                content: '300 ml (Un-numbered)',
            },
            {
                id: '2',
                number: 'AKJ-15070 - 01',
                selected: false,
                content: '300 ml (NO. 01-24)',
            },
            {
                id: '3',
                number: 'AKJ-15070 - 25',
                selected: false,
                content: '300 ml (NO. 25-48)',
            },
            {
                id: '4',
                number: 'AKJ-15070 - 99',
                selected: false,
                content: 'PE BOD Cap (24ea)',
            },
        ],
    },
    {
        type: 'expandable',
        id: '59',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/expandable%2F59.jpg?alt=media&token=ebf23944-9950-418a-838b-cbb8fe85f8a3',
        classify: 'Magic Touch',
        title: 'Ice Pans (아이스 팬) -USA-',
        content: [
            '■ -96도 저온에서부터 93도 고온까지 사용 가능합니다.',
            '',
            '■ 얼음, 드라이 아이스, 알코올스러시, 액화질소등의 보관에 이상적입니다.',
            '',
            '■ 강산, 클로로 포롬, 알코올, 화공약품 등에 영향을 받지 않습니다.',
            '',
            '■ 온도차이에 의한 외부이슬맺힘 현상이 없습니다.',
            '',
            '■ Pan의 칼라색상은 Green, Black, Red, Yellow, Blue, Violet입니다.',
            '',
            '(제조사 : Magic Touch Iceware Intl.)',
        ],
        specification: [
            {
                id: '1',
                number: 'AKJ-UB 32-37',
                selected: false,
                content: '13*13*7cm (소)',
            },
            {
                id: '2',
                number: 'AKJ-UB 32-38',
                selected: false,
                content: '28*20*9cm (중)',
            },
            {
                id: '3',
                number: 'AKJ-UB 32-39',
                selected: false,
                content: '40*30*10cm (대)',
            },
        ],
    },
    {
        type: 'expandable',
        id: '60',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/expandable%2F60.jpg?alt=media&token=9c70da13-6a19-4c35-bd1b-b0c8295d6858',
        classify: 'Magic Touch',
        title: 'Ice Buckets (아이스 버켓) -USA-',
        content: [
            '■ -96도 저온에서부터 93도 고온까지 사용 가능합니다.',
            '',
            '■ 얼음, 드라이 아이스, 알코올스러시, 액화질소등의 보관에 이상적입니다.',
            '',
            '■ 강산, 클로로 포롬, 알코올, 화공약품 등에 영향을 받지 않습니다.',
            '',
            '■ 온도차이에 의한 외부이슬맺힘 현상이 없습니다.',
            '',
            '■ Bucket의 칼라색상은 Green, Black, Red, Yellow, Blue, Violet입니다.',
            '',
            '',
            '(제조사 : Magic Touch Iceware Intl.)',
        ],
        specification: [
            {
                id: '1',
                number: 'AKJ-UB32-35',
                selected: false,
                content: 'Ice Bucket 4 Liter with lid',
            },
            {
                id: '2',
                number: 'AKJ-UB32-36',
                selected: false,
                content: 'Ice Bucket 2.5 Liter with lid',
            },
        ],
    },
    {
        type: 'expandable',
        id: '61',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/expandable%2F61.jpg?alt=media&token=962e181b-af5d-4d9e-abf3-96ea029636af',
        classify: 'Saint-Gobain',
        title: 'BYTEC Protectors (바이텍 벤치커버) -USA-',
        content: [
            '■ 비접착성으로 오물 및 실험재료 제거가 용이합니다.',
            '',
            '■ 방사성 물질로부터 표면 보호',
            '',
            '■ 바이텍은 테프론에 비닐이나 알루미늄으로 보강한 제품으로 작업용 실험대 탁자 후드 임시테이블용 표면에 사용가능.',
            '',
            '■ 부식성 강한 화학제품이나 오일 구리스 등에 견디는 내화학성 우수.',
        ],
        specification: [
            {
                id: '1',
                number: 'AKJ-D9860004',
                selected: false,
                content: '100 mm * 33 M ( FEP 테프론 + Vinyl 비닐)',
            },
            {
                id: '2',
                number: 'AKJ-D9860005',
                selected: false,
                content: '320 mm * 4.6 M ( FEP 테프론 + Vinyl 비닐)',
            },
            {
                id: '3',
                number: 'AKJ-D1069324',
                selected: false,
                content: '635 mm * 4.6 M ( FEP 테프론 + Vinyl 비닐)',
            },
            {
                id: '4',
                number: 'AKJ-D9860011',
                selected: false,
                content: '100 mm * 33 M ( FEP 테프론 + Al foil 알룸미늄호일)',
            },
            {
                id: '5',
                number: 'AKJ-D9860012',
                selected: false,
                content: '320 mm * 4.6 M ( FEP 테프론 + Al foil 알룸미늄호일)',
            },
            {
                id: '6',
                number: 'AKJ-D1069329',
                selected: false,
                content: '635 mm * 4.6 M ( FEP 테프론 + Al foil 알룸미늄호일)',
            },
        ],
    },
    {
        type: 'expandable',
        id: '62',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/expandable%2F62.jpg?alt=media&token=deb6bcb9-010f-4297-962d-dab60ffe9328',
        classify: 'Sanplatec',
        title: 'Wash Bottles (세척병 신형)',
        content: [
            '■ 몸체에 분주기가 붙은 일체형 세척병으로 병안에 잔류액이 남지 않는것이 특징입니다.',
            '',
            '■ 분주용 팁은 원하는 양에 따라 팁 끝부분을 칼로 자르시면 편리하게 용량을 조절 하실 수 있습니다.',
        ],
        specification: [
            {
                id: '1',
                number: 'AKJ-SA2116',
                selected: false,
                content: '500ml(Japan)',
            },
        ],
    },
    {
        type: 'expandable',
        id: '63',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/expandable%2F63.jpg?alt=media&token=b84d1061-a0a2-4ce0-9037-dbc31a54b0a6',
        classify: 'Sanplatec',
        title: 'Carboy with spigots (외산 증류수통) -JAPAN-',
        content: [
            'Spigot',
            ': PP (Polypropylene)',
        ],
        specification: [
            {
                id: '1',
                number: 'AKJ-SA2097E',
                selected: false,
                content: '20L',
            },
            {
                id: '2',
                number: 'AKJ-SA6521E',
                selected: false,
                content: '5L ,손잡이 부착',
            },
            {
                id: '3',
                number: 'AKJ-SA6522E',
                selected: false,
                content: '10L ,손잡이 부착',
            },
        ],
    },
    {
        type: 'expandable',
        id: '64',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/expandable%2F64.jpg?alt=media&token=9ec05c8a-6dd0-472c-92bb-97d8afce45c6',
        classify: 'Sanplatec',
        title: 'Rectangular bottle with spigots (사각 증류수통) -JAPAN-',
        content: [
            '■ Book Type으로 손잡이가 있어 이동이 쉬우며 폭으로 여러 개를 놓을 수 있어 공간활용에 매우 효율적입니다.',
            '',
            '■ PP 재질로 만들어져 내화학성이 내부식성이 있습니다.',
        ],
        specification: [
            {
                id: '1',
                number: 'AKJ-SA2122E',
                selected: false,
                content: '5L',
            },
            {
                id: '2',
                number: 'AKJ-SA2123E',
                selected: false,
                content: 'SA2123E',
            },
        ],
    },
    {
        type: 'expandable',
        id: '65',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/expandable%2F65.jpg?alt=media&token=2d819236-a4ce-41e8-b834-62f640b1e2b4',
        classify: 'Sanplatec',
        title: 'PFA Beakers (반투명 테프론 비이커) -JAPAN-',
        content: [
            '■ 일반적 테프론재질은 불투명이나 PFA 재질은 투명하며 내식성 내화학성 내열성이 탁월합니다. ',
            '',
            '눈금이 그려져 있어 용량의 확인이 용이하며 큰 용량은 손잡이가 부착된 제품을 선택할 수 있어 용도에 맞게 사용하실 수 있습니다.',
            '',
            '***손잡이 부착***',
        ],
        specification: [
            {
                id: '1',
                number: 'AKJ-SA11110E',
                selected: false,
                content: '100 ml(H)',
            },
            {
                id: '2',
                number: 'AKJ-SA11111E',
                selected: false,
                content: '200 ml(H)',
            },
            {
                id: '3',
                number: 'AKJ-SA11112E',
                selected: false,
                content: '500 ml(H)',
            },
            {
                id: '4',
                number: 'AKJ-SA11113E',
                selected: false,
                content: '1000 ml(H)',
            },
            {
                id: '5',
                number: 'AKJ-SA11114E',
                selected: false,
                content: '2000 ml(H)',
            },
        ],
    },
    {
        type: 'expandable',
        id: '66',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/expandable%2F66.jpg?alt=media&token=8bfb5eb6-f3d9-4ad0-91e7-af6c4ebe3801',
        classify: 'Sanplatec',
        title: 'PFA Beakers (반투명 테프론 비이커) -JAPAN-',
        content: [
            '■ 일반적 테프론재질은 불투명이나 PFA 재질은 투명하며 내식성 내화학성 내열성이 탁월합니다.',
            '',
            '*손잡이 없슴',
        ],
        specification: [
            {
                id: '1',
                number: 'AKJ-SA11116E',
                selected: false,
                content: '50ml',
            },
            {
                id: '2',
                number: 'AKJ-SA11117E',
                selected: false,
                content: '100ml',
            },
            {
                id: '3',
                number: 'AKJ-SA11119E',
                selected: false,
                content: '300ml',
            },
            {
                id: '4',
                number: 'AKJ-SA11120E',
                selected: false,
                content: '500ml',
            },
            {
                id: '5',
                number: 'AKJ-SA11121E',
                selected: false,
                content: '1000ml',
            },
        ],
    },
    {
        type: 'expandable',
        id: '67',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/expandable%2F67.jpg?alt=media&token=6caa5149-18c2-447c-b1b7-5a0023c8e035',
        classify: 'Todays',
        title: 'Burnner (Dragon 220) 가스버너',
        content: [
            'Specification ：',
            '■ Max. Temp.: 1300℃',
            '■ Fuel capacity(g): 35',
            '■ Working time(min): 60',
            '■ Safety lock: Yes',
            '■ Dimension(mm): H92xW115xD79 ',
            'Features:',
            '1. Electronic instant ignition',
            '2. Hight temperature attainable: 1300℃',
            '3. Safety, cleaning',
            '4. Adjustable flame',
            '5. Refillable butane fuel tank',
            '',
            'Application:',
            '1. Sterilizing',
            '2. Welding',
            '3. Heating',
            '4. Brazing',
            '5. Digestion',
            '6. Cooking ',
            '',
            '주의사항!!',
            '이 제품에 쓸수 있는 충전 가스는 라이터 충전용 가스 입니다.',
            '보통 쓰이는 가스와는 주입구가 맞지 않습니다.',
        ],
        specification: [
            {
                id: '1',
                number: 'AKJ-177220-00',
                selected: false,
                content: 'Burnner (Dragon 220)',
            },
        ],
    },
    {
        type: 'expandable',
        id: '68',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/expandable%2F68.jpg?alt=media&token=81c1aa8e-dc14-4226-9dd4-c152c23265d4',
        classify: 'Todays',
        title: 'Burnner (Dragon 200) 가스버너',
        content: [
            'Dragon 200 ',
            '',
            'Specification ：',
            '',
            '■ Max. Temp.: 1300℃',
            '■ Fuel capacity(g): 35',
            '■ Working time(min): 60',
            '■ Dimension(mm): H92 ',
            'Features:',
            '1. Electronic instant ignition',
            '2. Hight temperature attainable: 1300℃',
            '3. Safety, cleaning',
            '4. Adjustable flame',
            '5. Refillable butane fuel tank',
            '',
            'Application:',
            '1. Sterilizing',
            '2. Welding',
            '3. Heating',
            '4. Brazing',
            '5. Digestion',
            '6. Cooking',
        ],
        specification: [
            {
                id: '1',
                number: 'AKJ-177200-00',
                selected: false,
                content: 'Burnner (Drygon 200)',
            },
        ],
    },
    {
        type: 'expandable',
        id: '69',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/expandable%2F69.jpg?alt=media&token=dc26aaa5-b8d5-4d12-9d08-8edfd1f1ac89',
        classify: 'Todays',
        title: 'Burnner (Dragon 100) 가스버너',
        content: [
            'Specification ：',
            '■ Max. Temp.: 1300℃',
            '■ Fuel capacity(g): 45',
            '■ Working time(min): 60',
            '■ Safety lock: Yes',
            '■ Dimension(mm): H161xW137xD79 ',
            'Features:',
            '1. Electronic instant ignition',
            '2. Hight temperature attainable: 1300℃',
            '3. Safety, cleaning',
            '4. Adjustable flame',
            '5. Refillable butane fuel tank',
            '',
            'Application:',
            '1. Sterilizing',
            '2. Welding',
            '3. Heating',
            '4. Brazing',
            '5. Digestion',
            '6. Cooking',
        ],
        specification: [
            {
                id: '1',
                number: 'AKJ-177100-00',
                selected: false,
                content: 'Gas Burnner (Dragon 100)',
            },
        ],
    },
    {
        type: 'expandable',
        id: '70',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/expandable%2F70.jpg?alt=media&token=a7b35552-15fb-4817-8139-dd8774dba42a',
        classify: 'Usbeck',
        title: 'Gas Burner (가스 버너) / Usbeck (Germany)',
        content: [
            '■ 독일규격(DIN)에 의한 안정성이 보장된 가스버너',
            '',
            '■ 가스량이 조절되는 니들밸브와 공기량을 조절하는 공기조절기가 부착',
            '',
            '■ 가스의 종류에 구애받지 않고 사용할 수 있는 가스버너입니다.',
        ],
        specification: [
            {
                id: '1',
                number: 'AKJ-1350',
                selected: false,
                content: 'All Gas (대)',
            },
        ],
    },
    {
        type: 'expandable',
        id: '71',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/expandable%2F71.jpg?alt=media&token=cc34bc1d-4be7-4a4c-82a2-fa143774edd7',
        classify: 'Usbeck',
        title: 'Gas Burner (가스 버너) / Usbeck (Germany)',
        content: [
            '■ 독일규격(DIN)에 의한 안정성이 보장된 가스버너',
            '',
            '■ 가스량이 조절되는 니들밸브와 공기량을 조절하는 공기조절기가 부착',
            '',
            '■ 도시가스용과 LPG용 2가지로 나누어져 있습니다.',
        ],
        specification: [
            {
                id: '1',
                number: 'AKJ-1220',
                selected: false,
                content: 'LNG (중)',
            },
            {
                id: '2',
                number: 'AKJ-1221',
                selected: false,
                content: 'LPG (중)',
            },
        ],
    },
    {
        type: 'expandable',
        id: '72',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/expandable%2F72.jpg?alt=media&token=2abad58b-5f3a-4865-99b0-891cc23d4a68',
        classify: 'Usbeck',
        title: 'Gas Burner (가스 버너) / Usbeck (Germany)',
        content: [
            '■ 독일규격(DIN)에 의한 안정성이 보장된 가스버너',
            '',
            '■ 가스량이 조절되는 니들밸브와 공기량을 조절하는 공기조절기가 부착',
            '',
            '■ 도시가스용과 LPG용 2가지로 나누어져 있습니다.',
        ],
        specification: [
            {
                id: '1',
                number: 'AKJ-1010',
                selected: false,
                content: 'LNG (소)',
            },
            {
                id: '2',
                number: 'AKJ-1011',
                selected: false,
                content: 'LPG (소)',
            },
        ],
    },
    {
        type: 'expandable',
        id: '73',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/expandable%2F73.jpg?alt=media&token=1cd16b6d-159c-46f9-a1ee-b0e6d6e0da4e',
        classify: 'Usbeck',
        title: 'Blower (이연구) -GERMANY-',
        content: [],
        specification: [
            {
                id: '1',
                number: 'AKJ11-43',
                selected: false,
                content: '고무',
            },
        ],
    },
    {
        type: 'expandable',
        id: '74',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/expandable%2F74.jpg?alt=media&token=bb56bb91-0397-4fa3-a19c-9c5efc27eedf',
        classify: 'Waring',
        title: '1-Liter Laboratory Blender',
        content: [
            '7009S/7009G',
            'Capacity: 1/1.2 Liter',
            'Switch Settings: Two Speed. Features jack to accept digital tachometer',
            'Base: Epoxy Coated Motor Housing',
            'Container: Stainless steel with handle and two piece vinyl and styrene lid 7009S. Heat resistant glass with handle and two piece vinyl and styrene lid 7009G.',
            'Overall Height: 16 inches',
            'Weight: 11/13 lbs.',
            'Listings: UL',
        ],
        specification: [
            {
                id: '1',
                number: 'AKJ-7009S',
                selected: false,
                content: 'S.S. CAC25 7.0 Amps 120 volts 50/60 Hz .70 HP Heavy Duty High 22,000 Low 18,000',
            },
            {
                id: '2',
                number: 'AKJ-7009G',
                selected: false,
                content: 'Glass CAC48 7.0 Amps 120 volts 50/60 Hz .70 HP Heavy Duty High 22,000 Low 18,000',
            },
        ],
    },
    {
        type: 'expandable',
        id: '75',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/expandable%2F75.jpg?alt=media&token=2f3723aa-f6ea-45bd-9b9c-38312b0098b5',
        classify: 'Waring',
        title: '1-Liter Laboratory Blender',
        content: [
            'Available in 240 volt ',
            '',
            'Capacity: 1 Liter',
            'Switch Settings: Two Speed',
            'Base: Epoxy Coated Motor Housing',
            'Container: Stainless steel with handle and two piece vinyl and styrene lid 7011S. Heat resistant glass with handle and two piece vinyl and styrene lid 7011G.',
            'Overall Height: 15 inches',
            'Weight: 11 lbs.',
            'Listings: UL',
        ],
        specification: [
            {
                id: '1',
                number: 'AKJ-7011S',
                selected: false,
                content: '.S. CAC33 3.6 Amps 120 volts 50/60 Hz .40 HP Standard High 22,000 Low 18,000',
            },
            {
                id: '2',
                number: 'AKJ-7011G',
                selected: false,
                content: 'Glass CAC32 3.6 Amps 120 volts 50/60 Hz .40 HP Standard High 22,000 Low 18,000',
            },
            {
                id: '3',
                number: 'AKJ-7011HS',
                selected: false,
                content: 'S.S. CAC25 7.0 Amps 120 volts 50/60 Hz .70 HP Heavy Duty High 22,000 Low 18,000',
            },
            {
                id: '4',
                number: 'AKJ-7011HG',
                selected: false,
                content: 'Glass CAC48 7.0 Amps 120 volts 50/60 Hz .70 HP Heavy Duty High 22,000 Low 18,000',
            },
        ],
    },
];

export default items;
