const items = [
    {
        classify: 'Ampule[앰플]',
        content: [
            '■ Borosilicate Glass 3.3 (USP Type 1)',
            '■ LukeGL®',
        ],
        id: '1',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/expendables%2F1.jpg?alt=media&token=d39ffa0c-a27f-4f4b-900f-d070bb7ddb2d',
        specification: [
            {
                id: '1',
                number: 'A09-256-117',
                model: '9400-01',
                content: 'Ampule Clear 1ml',
                isSelected: false,
            },
            {
                id: '2',
                number: 'A09-256-124',
                model: '9400-02',
                content: 'Ampule Clear 2ml',
                isSelected: false,
            },
            {
                id: '3',
                number: 'A09-256-131',
                model: '9400-05',
                content: 'Ampule Clear 5ml (Φ15*86)',
                isSelected: false,
            },
            {
                id: '4',
                number: 'A09-256-138',
                model: '9400-10',
                content: 'Ampule Clear 10ml',
                isSelected: false,
            },
            {
                id: '5',
                number: 'A09-256-145',
                model: '9400-20',
                content: 'Ampule Clear 20ml',
                isSelected: false,
            },
            {
                id: '6',
                number: 'A09-256-517',
                model: '9401-01',
                content: 'Ampule Amber 1ml',
                isSelected: false,
            },
            {
                id: '7',
                number: 'A09-256-524',
                model: '9401-02',
                content: 'Ampule Amber 2ml',
                isSelected: false,
            },
            {
                id: '8',
                number: 'A09-256-531',
                model: '9401-05',
                content: 'Ampule Amber 5ml',
                isSelected: false,
            },
            {
                id: '9',
                number: 'A09-256-538',
                model: '9401-10',
                content: 'Ampule Amber 10ml',
                isSelected: false,
            },
            {
                id: '10',
                number: 'A09-256-545',
                model: '9401-20',
                content: 'Ampule Amber 20ml',
                isSelected: false,
            },
        ],
        tableItems: [
            '   투명, Clear Ampule               <table summary="상세규격표" class="st-tablebox" cellpadding="0" cellspacing="0"><thead>                <tr>                 <th scope="row" width="200">Cat. No.</th>                 <th scope="row" width="200">Model</th>                 <th scope="row" width="200">용량</th>                 <th scope="row" width="200" class="tdfin">Size</th>               </tr>              </thead>              <tbody>                <tr>                  <td scope="row" class="trfinth4">A09-256-117</td>                  <td scope="row">9400-01</td>                  <td scope="row">1 ml</td>                  <td scope="row" class="tdfin">Ø10.0×h68 mm</td>                </tr>                <tr>                  <td scope="row" class="trfinth4">A09-256-124</td>                  <td scope="row">9400-02</td>                  <td scope="row">2 ml</td>                  <td scope="row" class="tdfin">Ø11.0×h75 mm</td>                </tr>                <tr>                  <td scope="row" class="trfinth4">A09-256-131</td>                  <td scope="row">9400-05</td>                  <td scope="row">5 ml</td>                  <td scope="row" class="tdfin">Ø15.0×h86 mm</td>                </tr>                <tr>                  <td scope="row" class="trfinth4">A09-256-138</td>                  <td scope="row">9400-10</td>                  <td scope="row">10 ml</td>                  <td scope="row" class="tdfin">Ø17.0×h110 mm</td>                </tr>                <tr>                  <td scope="row" class="trfinth">A09-256-145</td>                  <td class="trfin" scope="row">9400-20</td>                  <td class="trfin" scope="row">20 ml</td>                  <td scope="row" class="trfin2">Ø24.5×h115 mm</td>                </tr>                                              </tbody></table>     갈색, Amber Ampule   <table summary="상세규격표" class="st-tablebox" cellpadding="0" cellspacing="0"><thead>    <tr>      <th scope="row" width="200">Cat. No.</th>      <th scope="row" width="200">Model</th>      <th scope="row" width="200">용량</th>      <th scope="row" width="200" class="tdfin">Size</th>    </tr>  </thead>  <tbody>    <tr>      <td scope="row" class="trfinth4">A09-256-517</td>      <td scope="row">9401-01</td>      <td scope="row">1 ml</td>      <td scope="row" class="tdfin">Ø10.0×h68 mm</td>    </tr>    <tr>      <td scope="row" class="trfinth4">A09-256-524</td>      <td scope="row">9401-02</td>      <td scope="row">2 ml</td>      <td scope="row" class="tdfin">Ø11.0×h75 mm</td>    </tr>    <tr>      <td scope="row" class="trfinth4">A09-256-531</td>      <td scope="row">9401-05</td>      <td scope="row">5 ml</td>      <td scope="row" class="tdfin">Ø15.0×h86 mm</td>    </tr>    <tr>      <td scope="row" class="trfinth4">A09-256-538</td>      <td scope="row">9401-10</td>      <td scope="row">10 ml</td>      <td scope="row" class="tdfin">Ø17.0×h110 mm</td>    </tr>    <tr>      <td scope="row" class="trfinth">A09-256-545</td>      <td class="trfin" scope="row">9401-20</td>      <td class="trfin" scope="row">20 ml</td>      <td scope="row" class="trfin2" "="">Ø24.5×h115 mm</td>    </tr>  </tbody></table>',
        ],
        title: 'Ampule (앰플, 기본형, LukeGL®)',
        type: 'expendables',
    },
    {
        classify: 'Ampule[앰플]',
        content: [
            '■ Disposable PP (Polypropylene)',
            '■ LabPlasti®',
        ],
        id: '2',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/expendables%2F2.jpg?alt=media&token=74b09afc-d945-4e5d-ae9f-b02a1f836246',
        specification: [
            {
                id: '1',
                number: 'A09-20-911',
                model: 'AC0104',
                content: 'Ampule Cracker 1 ~ 4ml 용',
                isSelected: false,
            },
            {
                id: '2',
                number: 'A09-20-918',
                model: 'AC0510',
                content: 'Ampule Cracker 5 ~ 10ml 용',
                isSelected: false,
            },
        ],
        tableItems: [
            '<table summary="상세규격표" class="st-tablebox" cellpadding="0" cellspacing="0">  <thead>    <tr>      <th scope="row" width="200">Cat. No</th>      <th scope="row" width="200">Model</th>      <th scope="row" width="400" class="tdfin">규 격</th>    </tr>  </thead>  <tbody>    <tr>      <td scope="row" class="trfinth4">A09-20-911</td>      <td scope="row">AC0104</td>      <td scope="row" class="tdfin">1 ~ 4 ml 용</td>    </tr>    <tr>      <td scope="row" class="trfinth">A09-20-918</td>      <td class="trfin scope=" row"="">AC0510</td>      <td scope="row" class="trfin2">5 ~ 10 ml 용</td>    </tr>  </tbody></table>',
        ],
        title: 'Ampule Cracker (앰플 따개)',
        type: 'expendables',
    },
    {
        classify: 'Ampule[앰플]',
        content: [
            '■ Borosilicate Glass 3.3, USP Type I, ASTM E438, Type I, Class A',
            '■ Round Bottom, Cylindrical Drying Ampules with od10 mm Top Stem',
            '■ Chemglass',
        ],
        id: '3',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/expendables%2F3.jpg?alt=media&token=0b8c60a4-f6d1-4a96-a86b-2447c2edd97a',
        specification: [
            {
                id: '1',
                number: 'A09-132-223',
                model: 'AF0084-01',
                content: 'Drying Ampule Round Bottom 5 ml',
                isSelected: false,
            },
            {
                id: '2',
                number: 'A09-132-227',
                model: 'AF0084-02',
                content: 'Drying Ampule Round Bottom 10 ml',
                isSelected: false,
            },
            {
                id: '3',
                number: 'A09-132-231',
                model: 'AF0084-03',
                content: 'Drying Ampule Round Bottom 20 ml',
                isSelected: false,
            },
            {
                id: '4',
                number: 'A09-132-235',
                model: 'AF0084-04',
                content: 'Drying Ampule Round Bottom 50 ml',
                isSelected: false,
            },
            {
                id: '5',
                number: 'A09-132-239',
                model: 'AF0084-05',
                content: 'Drying Ampule Round Bottom 100 ml',
                isSelected: false,
            },
        ],
        tableItems: [
            '<table summary="상세규격표" class="st-tablebox" cellpadding="0" cellspacing="0">  <thead>    <tr>      <th width="133" align="center" scope="row">Cat. No</th>      <th width="132" align="center" scope="row">Model</th>      <th width="132" align="center" scope="row">용량</th>      <th width="132" align="center" class="tdfin" scope="row">Size</th>    </tr>      </thead>  <tbody>    <tr>      <td scope="row" class="trfinth4">A09-132-223</td>      <td scope="row">AF0084-01</td>      <td scope="row">5 ml</td>      <td scope="row" class="tdfin">Ø17×h147 mm</td>    </tr>    <tr>      <td scope="row" class="trfinth4">A09-132-227</td>      <td scope="row">AF0084-02</td>      <td scope="row">10 ml</td>      <td scope="row" class="tdfin">Ø17×h177 mm</td>    </tr>    <tr>      <td scope="row" class="trfinth4">A09-132-231</td>      <td scope="row">AF0084-03</td>      <td scope="row">20 ml</td>      <td scope="row" class="tdfin">Ø25×h178 mm</td>    </tr>    <tr>      <td scope="row" class="trfinth4">A09-132-235</td>      <td scope="row">AF0084-04</td>      <td scope="row">50 ml</td>      <td scope="row" class="tdfin">Ø35×h200 mm</td>    </tr>    <tr>      <td scope="row" class="trfinth">A09-132-239</td>      <td class="trfin" scope="row">AF0084-05</td>      <td class="trfin" scope="row">100 ml</td>      <td scope="row" class="trfin2">Ø41×h225 mm</td>    </tr>  </tbody></table>',
        ],
        title: 'Drying Ampule, Round Bottom (드라잉 앰플)',
        type: 'expendables',
    },
];

export default items;
