const items = [
    {
        classify: 'Ampule[앰플]',
        content: [
            '■ Borosilicate Glass 3.3 (USP Type 1)',
            '■ LukeGL®',
        ],
        id: '1',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/expendables%2F1.jpg?alt=media&token=fa9da03e-f668-4bd3-90c1-166c4a06ece1',
        specification: [
            {
                id: '1',
                number: 'A09-256-117',
                model: '9400-01',
                content: 'Ampule Clear 1ml',
                isSelected: false,
            },
            {
                id: '2',
                number: 'A09-256-124',
                model: '9400-02',
                content: 'Ampule Clear 2ml',
                isSelected: false,
            },
            {
                id: '3',
                number: 'A09-256-131',
                model: '9400-05',
                content: 'Ampule Clear 5ml (Φ15*86)',
                isSelected: false,
            },
            {
                id: '4',
                number: 'A09-256-138',
                model: '9400-10',
                content: 'Ampule Clear 10ml',
                isSelected: false,
            },
            {
                id: '5',
                number: 'A09-256-145',
                model: '9400-20',
                content: 'Ampule Clear 20ml',
                isSelected: false,
            },
            {
                id: '6',
                number: 'A09-256-517',
                model: '9401-01',
                content: 'Ampule Amber 1ml',
                isSelected: false,
            },
            {
                id: '7',
                number: 'A09-256-524',
                model: '9401-02',
                content: 'Ampule Amber 2ml',
                isSelected: false,
            },
            {
                id: '8',
                number: 'A09-256-531',
                model: '9401-05',
                content: 'Ampule Amber 5ml',
                isSelected: false,
            },
            {
                id: '9',
                number: 'A09-256-538',
                model: '9401-10',
                content: 'Ampule Amber 10ml',
                isSelected: false,
            },
            {
                id: '10',
                number: 'A09-256-545',
                model: '9401-20',
                content: 'Ampule Amber 20ml',
                isSelected: false,
            },
        ],
        tableItems: [
            '투명,ClearAmpule<tablesummary="상세규격표"class="st-tablebox"cellpadding="0"cellspacing="0"><thead><tr><thscope="row"width="200">Cat.No.</th><thscope="row"width="200">Model</th><thscope="row"width="200">용량</th><thscope="row"width="200"class="tdfin">Size</th></tr></thead><tbody><tr><tdscope="row"class="trfinth4">A09-256-117</td><tdscope="row">9400-01</td><tdscope="row">1ml</td><tdscope="row"class="tdfin">Ø10.0×h68mm</td></tr><tr><tdscope="row"class="trfinth4">A09-256-124</td><tdscope="row">9400-02</td><tdscope="row">2ml</td><tdscope="row"class="tdfin">Ø11.0×h75mm</td></tr><tr><tdscope="row"class="trfinth4">A09-256-131</td><tdscope="row">9400-05</td><tdscope="row">5ml</td><tdscope="row"class="tdfin">Ø15.0×h86mm</td></tr><tr><tdscope="row"class="trfinth4">A09-256-138</td><tdscope="row">9400-10</td><tdscope="row">10ml</td><tdscope="row"class="tdfin">Ø17.0×h110mm</td></tr><tr><tdscope="row"class="trfinth">A09-256-145</td><tdclass="trfin"scope="row">9400-20</td><tdclass="trfin"scope="row">20ml</td><tdscope="row"class="trfin2">Ø24.5×h115mm</td></tr></tbody></table>갈색,AmberAmpule<tablesummary="상세규격표"class="st-tablebox"cellpadding="0"cellspacing="0"><thead><tr><thscope="row"width="200">Cat.No.</th><thscope="row"width="200">Model</th><thscope="row"width="200">용량</th><thscope="row"width="200"class="tdfin">Size</th></tr></thead><tbody><tr><tdscope="row"class="trfinth4">A09-256-517</td><tdscope="row">9401-01</td><tdscope="row">1ml</td><tdscope="row"class="tdfin">Ø10.0×h68mm</td></tr><tr><tdscope="row"class="trfinth4">A09-256-524</td><tdscope="row">9401-02</td><tdscope="row">2ml</td><tdscope="row"class="tdfin">Ø11.0×h75mm</td></tr><tr><tdscope="row"class="trfinth4">A09-256-531</td><tdscope="row">9401-05</td><tdscope="row">5ml</td><tdscope="row"class="tdfin">Ø15.0×h86mm</td></tr><tr><tdscope="row"class="trfinth4">A09-256-538</td><tdscope="row">9401-10</td><tdscope="row">10ml</td><tdscope="row"class="tdfin">Ø17.0×h110mm</td></tr><tr><tdscope="row"class="trfinth">A09-256-545</td><tdclass="trfin"scope="row">9401-20</td><tdclass="trfin"scope="row">20ml</td><tdscope="row"class="trfin2""="">Ø24.5×h115mm</td></tr></tbody></table>',
        ],
        title: '앰플, 기본형, LukeGL® (Ampule)',
        type: 'expendables',
    },
    {
        classify: 'Ampule[앰플]',
        content: [
            '■ Disposable PP (Polypropylene)',
            '■ LabPlasti®',
        ],
        id: '2',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/expendables%2F2.jpg?alt=media&token=baef0ac7-4f14-40e5-9819-24c088005137',
        specification: [
            {
                id: '1',
                number: 'A09-20-911',
                model: 'AC0104',
                content: 'Ampule Cracker 1 ~ 4ml 용',
                isSelected: false,
            },
            {
                id: '2',
                number: 'A09-20-918',
                model: 'AC0510',
                content: 'Ampule Cracker 5 ~ 10ml 용',
                isSelected: false,
            },
        ],
        tableItems: [
            '<tablesummary="상세규격표"class="st-tablebox"cellpadding="0"cellspacing="0"><thead><tr><thscope="row"width="200">Cat.No</th><thscope="row"width="200">Model</th><thscope="row"width="400"class="tdfin">규격</th></tr></thead><tbody><tr><tdscope="row"class="trfinth4">A09-20-911</td><tdscope="row">AC0104</td><tdscope="row"class="tdfin">1~4ml용</td></tr><tr><tdscope="row"class="trfinth">A09-20-918</td><tdclass="trfinscope="row"="">AC0510</td><tdscope="row"class="trfin2">5~10ml용</td></tr></tbody></table>',
        ],
        title: '앰플 따개 (Ampule Cracker)',
        type: 'expendables',
    },
    {
        classify: 'Ampule[앰플]',
        content: [
            '■ Borosilicate Glass 3.3, USP Type I, ASTM E438, Type I, Class A',
            '■ Round Bottom, Cylindrical Drying Ampules with od10 mm Top Stem',
            '■ Chemglass',
        ],
        id: '3',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/expendables%2F3.jpg?alt=media&token=d2c727bc-e641-4146-8c4c-0067ed937c91',
        specification: [
            {
                id: '1',
                number: 'A09-132-223',
                model: 'AF0084-01',
                content: 'Drying Ampule Round Bottom 5 ml',
                isSelected: false,
            },
            {
                id: '2',
                number: 'A09-132-227',
                model: 'AF0084-02',
                content: 'Drying Ampule Round Bottom 10 ml',
                isSelected: false,
            },
            {
                id: '3',
                number: 'A09-132-231',
                model: 'AF0084-03',
                content: 'Drying Ampule Round Bottom 20 ml',
                isSelected: false,
            },
            {
                id: '4',
                number: 'A09-132-235',
                model: 'AF0084-04',
                content: 'Drying Ampule Round Bottom 50 ml',
                isSelected: false,
            },
            {
                id: '5',
                number: 'A09-132-239',
                model: 'AF0084-05',
                content: 'Drying Ampule Round Bottom 100 ml',
                isSelected: false,
            },
        ],
        tableItems: [
            '<tablesummary="상세규격표"class="st-tablebox"cellpadding="0"cellspacing="0"><thead><tr><thwidth="133"align="center"scope="row">Cat.No</th><thwidth="132"align="center"scope="row">Model</th><thwidth="132"align="center"scope="row">용량</th><thwidth="132"align="center"class="tdfin"scope="row">Size</th></tr></thead><tbody><tr><tdscope="row"class="trfinth4">A09-132-223</td><tdscope="row">AF0084-01</td><tdscope="row">5ml</td><tdscope="row"class="tdfin">Ø17×h147mm</td></tr><tr><tdscope="row"class="trfinth4">A09-132-227</td><tdscope="row">AF0084-02</td><tdscope="row">10ml</td><tdscope="row"class="tdfin">Ø17×h177mm</td></tr><tr><tdscope="row"class="trfinth4">A09-132-231</td><tdscope="row">AF0084-03</td><tdscope="row">20ml</td><tdscope="row"class="tdfin">Ø25×h178mm</td></tr><tr><tdscope="row"class="trfinth4">A09-132-235</td><tdscope="row">AF0084-04</td><tdscope="row">50ml</td><tdscope="row"class="tdfin">Ø35×h200mm</td></tr><tr><tdscope="row"class="trfinth">A09-132-239</td><tdclass="trfin"scope="row">AF0084-05</td><tdclass="trfin"scope="row">100ml</td><tdscope="row"class="trfin2">Ø41×h225mm</td></tr></tbody></table>',
        ],
        title: '드라잉 앰플 (Drying Ampule, Round Bottom)',
        type: 'expendables',
    },
];

export default items;
