const items = [
    {
        type: 'glass',
        id: '1',
        image: '',
        classify: 'Adapters',
        title: 'Bent distillation',
        content: [
            'bent 105˚ angle with a outer joint at top',
        ],
        specification: [
            {
                id: '1',
                number: 'KJ-A1-1',
                selected: false,
                content: 'Adapter Bent Distillation 14/20',
            },
            {
                id: '2',
                number: 'KJ-A1-2',
                selected: false,
                content: 'Adapter Bent Distillation 24/40',
            },
            {
                id: '3',
                number: 'KJ-A1-3',
                selected: false,
                content: 'Adapter Bent Distillation 19/38',
            },
            {
                id: '4',
                number: 'KJ-A1-4',
                selected: false,
                content: 'Adapter Bent Distillation 29/42',
            },
            {
                id: '5',
                number: 'KJ-A1-5',
                selected: false,
                content: 'Adapter Bent Distillation 34/45',
            },
        ],
    },
    {
        type: 'glass',
        id: '2',
        image: '',
        classify: 'Adapters',
        title: 'Bent distillation',
        content: [
            'outer joint at 105˚ angle with inner joint at bottom',
        ],
        specification: [
            {
                id: '1',
                number: 'KJ-A2-1',
                selected: false,
                content: 'Adapter Bent Distillation 14/20',
            },
            {
                id: '2',
                number: '         KJ-A2-2',
                selected: false,
                content: 'Adapter Bent Distillation 24/40',
            },
            {
                id: '3',
                number: 'KJ-A2-3',
                selected: false,
                content: 'Adapter Bent Distillation 29/42',
            },
            {
                id: '4',
                number: 'KJ-A2-4',
                selected: false,
                content: 'Adapter Bent Distillation 34/45',
            },
            {
                id: '5',
                number: 'KJ-A2-5',
                selected: false,
                content: 'Adapter Bent Distillation 19/38',
            },
        ],
    },
    {
        type: 'glass',
        id: '3',
        image: '',
        classify: 'Adapters',
        title: 'Bent distillation',
        content: [
            '75˚ angle with inner joint each end',
        ],
        specification: [
            {
                id: '1',
                number: 'KJ-A3-1',
                selected: false,
                content: 'Adapter Bent Distillation 14/20',
            },
            {
                id: '2',
                number: '         KJ-A3-2',
                selected: false,
                content: 'Adapter Bent Distillation 24/40',
            },
            {
                id: '3',
                number: 'KJ-A3-3',
                selected: false,
                content: 'Adapter Bent Distillation 34/45',
            },
            {
                id: '4',
                number: '         KJ-A3-4',
                selected: false,
                content: 'Adapter Bent Distillation 19/38',
            },
            {
                id: '5',
                number: 'KJ-A3-5',
                selected: false,
                content: 'Adapter Bent Distillation 29/42',
            },
        ],
    },
    {
        type: 'glass',
        id: '4',
        image: '',
        classify: 'Adapters',
        title: 'Vent jacket',
        content: [],
        specification: [
            {
                id: '1',
                number: '         KJ-A4-1',
                selected: false,
                content: 'Adapter Bent Jacket 14/20',
            },
            {
                id: '2',
                number: '         KJ-A4-2',
                selected: false,
                content: 'Adapter Bent Jacket 24/40',
            },
            {
                id: '3',
                number: '         KJ-A4-3',
                selected: false,
                content: 'Adapter Bent Jacket 34/45',
            },
            {
                id: '4',
                number: 'KJ-A4-4',
                selected: false,
                content: 'Adapter Bent Jacket 19/38',
            },
            {
                id: '5',
                number: 'KJ-A4-5',
                selected: false,
                content: 'Adapter Bent Jacket 29/42',
            },
        ],
    },
    {
        type: 'glass',
        id: '5',
        image: '',
        classify: 'Adapters',
        title: 'Claisen',
        content: [],
        specification: [
            {
                id: '1',
                number: 'KJ-A5-1',
                selected: false,
                content: 'Adapter Claisen 14/20,14/20',
            },
            {
                id: '2',
                number: 'KJ-A5-2',
                selected: false,
                content: 'Adapter Claisen 24/40,14/20',
            },
            {
                id: '3',
                number: '         KJ-A5-3',
                selected: false,
                content: 'Adapter Claisen 14/20,10/20',
            },
            {
                id: '4',
                number: 'KJ-A5-4',
                selected: false,
                content: 'Adapter Claisen 24/40,10/20',
            },
            {
                id: '5',
                number: 'KJ-A5-5',
                selected: false,
                content: 'Adapter Claisen 19/28,10/20',
            },
            {
                id: '6',
                number: 'KJ-A5-6',
                selected: false,
                content: 'Adapter Claisen 29/42,10/20',
            },
            {
                id: '7',
                number: 'KJ-A5-7',
                selected: false,
                content: 'Adapter Claisen 34/45,10/20',
            },
        ],
    },
    {
        type: 'glass',
        id: '6',
        image: '',
        classify: 'Adapters',
        title: 'Claisen',
        content: [],
        specification: [
            {
                id: '1',
                number: '         KJ-A6-1',
                selected: false,
                content: 'ter Claisen 14/20',
            },
            {
                id: '2',
                number: '         KJ-A6-2',
                selected: false,
                content: 'Adapter Claisen 24/40',
            },
            {
                id: '3',
                number: 'KJ-A6-3',
                selected: false,
                content: 'Adapter Claisen 19/38',
            },
            {
                id: '4',
                number: '         KJ-A6-4',
                selected: false,
                content: 'Adapter Claisen 29/42',
            },
            {
                id: '5',
                number: '         KJ-A6-5',
                selected: false,
                content: 'Adapter Claisen 34/45',
            },
        ],
    },
    {
        type: 'glass',
        id: '7',
        image: '',
        classify: 'Adapters',
        title: 'Claisen',
        content: [],
        specification: [
            {
                id: '1',
                number: '         KJ-A7-1',
                selected: false,
                content: 'Adapter Claisen 14/20',
            },
            {
                id: '2',
                number: '         KJ-A7-2',
                selected: false,
                content: 'Adapter Claisen 24/40',
            },
            {
                id: '3',
                number: '         KJ-A7-3',
                selected: false,
                content: 'Adapter Claisen 19/38',
            },
            {
                id: '4',
                number: '         KJ-A7-4',
                selected: false,
                content: 'Adapter Claisen 29/42',
            },
            {
                id: '5',
                number: 'KJ-A7-5',
                selected: false,
                content: 'Adapter Claisen 34/45',
            },
        ],
    },
    {
        type: 'glass',
        id: '8',
        image: '',
        classify: 'Adapters',
        title: 'Claisen',
        content: [],
        specification: [
            {
                id: '1',
                number: '         KJ-A8-1',
                selected: false,
                content: 'Adapter Claisen 24/40,10/20,10/30',
            },
            {
                id: '2',
                number: '         KJ-A8-2',
                selected: false,
                content: 'Adapter Claisen 24/40,14/20',
            },
            {
                id: '3',
                number: '         KJ-A8-3',
                selected: false,
                content: 'Adapter Claisen 14/40,10/20',
            },
            {
                id: '4',
                number: '         KJ-A8-4',
                selected: false,
                content: 'Adapter Claisen 14/20,14/20',
            },
            {
                id: '5',
                number: '         KJ-A8-5',
                selected: false,
                content: 'Adapter Claisen 24/40,24/40',
            },
        ],
    },
    {
        type: 'glass',
        id: '9',
        image: '',
        classify: 'Adapters',
        title: 'Claisen',
        content: [],
        specification: [
            {
                id: '1',
                number: '         KJ-A9-1',
                selected: false,
                content: 'Adapter Claisen 14/20,10/20',
            },
            {
                id: '2',
                number: 'KJ-A9-2',
                selected: false,
                content: 'Adapter Claisen 14/20,14/20',
            },
            {
                id: '3',
                number: '         KJ-A9-3',
                selected: false,
                content: 'Adapter Claisen 24/40,10/20',
            },
            {
                id: '4',
                number: '         KJ-A9-4',
                selected: false,
                content: 'Adapter Claisen 24/40,14/20',
            },
            {
                id: '5',
                number: 'KJ-A9-5',
                selected: false,
                content: 'Adapter Claisen 24/40,24/40',
            },
        ],
    },
    {
        type: 'glass',
        id: '10',
        image: '',
        classify: 'Adapters',
        title: 'Connecting',
        content: [],
        specification: [
            {
                id: '1',
                number: '         KJ-A10-1',
                selected: false,
                content: 'Adapter Connecting 14/20',
            },
            {
                id: '2',
                number: 'KJ-A10-2',
                selected: false,
                content: 'Adapter Connecting 24/40',
            },
            {
                id: '3',
                number: 'KJ-A10-3',
                selected: false,
                content: 'Adapter Connecting 19/38',
            },
            {
                id: '4',
                number: '         KJ-A10-4',
                selected: false,
                content: 'Adapter Connecting 29/42',
            },
            {
                id: '5',
                number: 'KJ-A10-5',
                selected: false,
                content: 'Adapter Connecting 34/45',
            },
        ],
    },
    {
        type: 'glass',
        id: '11',
        image: '',
        classify: 'Adapters',
        title: 'Connecting',
        content: [],
        specification: [
            {
                id: '1',
                number: '         KJ-A11-1',
                selected: false,
                content: 'Adapter Connecting 10/30-14/20',
            },
            {
                id: '2',
                number: '         KJ-A11-2',
                selected: false,
                content: 'Adapter Connecting 10/30-24/40',
            },
            {
                id: '3',
                number: 'KJ-A11-3',
                selected: false,
                content: 'Adapter Connecting 14/20-10/30',
            },
            {
                id: '4',
                number: 'KJ-A11-4',
                selected: false,
                content: 'Adapter Connecting 14/20-24/40',
            },
            {
                id: '5',
                number: 'KJ-A11-5',
                selected: false,
                content: 'Adapter Connecting 24/40-14/20',
            },
            {
                id: '6',
                number: '         KJ-A11-6',
                selected: false,
                content: 'Adapter Connecting 24/40-34/45',
            },
            {
                id: '7',
                number: '         KJ-A11-7',
                selected: false,
                content: 'Adapter Connecting 24/40-45/50',
            },
            {
                id: '8',
                number: '         KJ-A11-8',
                selected: false,
                content: 'Adapter Connecting 24/40-50/50',
            },
            {
                id: '9',
                number: 'KJ-A11-9',
                selected: false,
                content: 'Adapter Connecting 34/45-24/40',
            },
            {
                id: '10',
                number: '         KJ-A11-10',
                selected: false,
                content: 'Adapter Connecting 45/50-24/40',
            },
            {
                id: '11',
                number: 'KJ-A11-11',
                selected: false,
                content: 'Adapter Connecting 14/20-19/38',
            },
            {
                id: '12',
                number: '         KJ-A11-12',
                selected: false,
                content: 'Adapter Connecting 19/38-14/20',
            },
            {
                id: '13',
                number: '         KJ-A11-13',
                selected: false,
                content: 'Adapter Connecting 24/40-29/42',
            },
            {
                id: '14',
                number: 'KJ-A11-14',
                selected: false,
                content: 'Adapter Connecting 29/42-24/40',
            },
            {
                id: '15',
                number: 'KJ-A11-15',
                selected: false,
                content: 'Adapter Connecting 34/40-45/50',
            },
            {
                id: '16',
                number: '         KJ-A11-16',
                selected: false,
                content: 'Adapter Connecting 34/45-50/50',
            },
        ],
    },
    {
        type: 'glass',
        id: '12',
        image: '',
        classify: 'Adapters',
        title: 'Connecting',
        content: [],
        specification: [
            {
                id: '1',
                number: '         KJ-A12-1',
                selected: false,
                content: 'Adapter Connecting 14/20,10/20',
            },
            {
                id: '2',
                number: 'KJ-A12-2',
                selected: false,
                content: 'Adapter Connecting 14/20,14/20',
            },
            {
                id: '3',
                number: '         KJ-A12-3',
                selected: false,
                content: 'Adapter Connecting 24/40,10/20',
            },
            {
                id: '4',
                number: 'KJ-A12-4',
                selected: false,
                content: 'Adapter Connecting 24/40,14/20',
            },
            {
                id: '5',
                number: '         KJ-A12-5',
                selected: false,
                content: 'Adapter Connecting 24/40,24/40',
            },
        ],
    },
    {
        type: 'glass',
        id: '13',
        image: '',
        classify: 'Adapters',
        title: 'Connecting',
        content: [],
        specification: [
            {
                id: '1',
                number: 'KJ-A13-1',
                selected: false,
                content: 'Adapter Connecting 14/20',
            },
            {
                id: '2',
                number: 'KJ-A13-2',
                selected: false,
                content: 'Adapter Connecting 24/40',
            },
            {
                id: '3',
                number: 'KJ-A13-3',
                selected: false,
                content: 'Adapter Connecting 19/38',
            },
            {
                id: '4',
                number: 'KJ-A13-4',
                selected: false,
                content: 'apter Connecting 29/42',
            },
            {
                id: '5',
                number: 'KJ-A13-5',
                selected: false,
                content: 'Adapter Connecting 34/45',
            },
        ],
    },
    {
        type: 'glass',
        id: '14',
        image: '',
        classify: 'Adapters',
        title: 'Distilling',
        content: [],
        specification: [
            {
                id: '1',
                number: '         KJ-A14-1',
                selected: false,
                content: 'Adapter Distillating 14/20',
            },
            {
                id: '2',
                number: 'KJ-A14-2',
                selected: false,
                content: 'Adapter Distillating 24/40',
            },
            {
                id: '3',
                number: '         KJ-A14-3',
                selected: false,
                content: 'Adapter Distillating 29/42',
            },
            {
                id: '4',
                number: '         KJ-A14-4',
                selected: false,
                content: 'Adapter Distillating 34/45',
            },
        ],
    },
    {
        type: 'glass',
        id: '15',
        image: '',
        classify: 'Adapters',
        title: 'Distilling',
        content: [],
        specification: [
            {
                id: '1',
                number: 'KJ-A15-1',
                selected: false,
                content: 'Adapter Distillating 14/20',
            },
            {
                id: '2',
                number: 'KJ-A15-2',
                selected: false,
                content: 'Adapter Distillating 24/40',
            },
            {
                id: '3',
                number: 'KJ-A15-3',
                selected: false,
                content: 'Adapter Distillating 29/42',
            },
            {
                id: '4',
                number: '         KJ-A15-4',
                selected: false,
                content: 'Adapter Distillating 34/45',
            },
        ],
    },
    {
        type: 'glass',
        id: '16',
        image: '',
        classify: 'Adapters',
        title: 'Distilling',
        content: [],
        specification: [
            {
                id: '1',
                number: '         KJ-A16-1',
                selected: false,
                content: 'Adapter Distillating 14/20,10/20',
            },
            {
                id: '2',
                number: 'KJ-A16-2',
                selected: false,
                content: 'Adapter Distillating 14/20,14/20',
            },
            {
                id: '3',
                number: '         KJ-A16-3',
                selected: false,
                content: 'Adapter Distillating 24/40,10/20',
            },
            {
                id: '4',
                number: 'KJ-A16-4',
                selected: false,
                content: 'Adapter Distillating 24/40,14/20',
            },
        ],
    },
    {
        type: 'glass',
        id: '17',
        image: '',
        classify: 'Adapters',
        title: 'Vacuum filtration',
        content: [],
        specification: [
            {
                id: '1',
                number: '         KJ-A17-1',
                selected: false,
                content: 'Adapter Vacuum Filteration 14/20',
            },
            {
                id: '2',
                number: 'KJ-A17-2',
                selected: false,
                content: 'Adapter Vacuum Filteration 24/40',
            },
        ],
    },
    {
        type: 'glass',
        id: '18',
        image: '',
        classify: 'Adapters',
        title: 'Flow control, Glass Plug',
        content: [],
        specification: [
            {
                id: '1',
                number: '         KJ-A18-1',
                selected: false,
                content: 'Adapter Flow Control 14/20 G/C',
            },
            {
                id: '2',
                number: 'KJ-A18-2',
                selected: false,
                content: 'Adapter Flow Control 24/40 G/C',
            },
            {
                id: '3',
                number: '         KJ-A18-3',
                selected: false,
                content: 'Adapter Flow Control 14/20 외산G/C',
            },
            {
                id: '4',
                number: 'KJ-A18-4',
                selected: false,
                content: 'Adapter Flow Control 24/40 외산G/C',
            },
        ],
    },
    {
        type: 'glass',
        id: '19',
        image: '',
        classify: 'Adapters',
        title: 'Flow control, PTFE Plug',
        content: [],
        specification: [
            {
                id: '1',
                number: '         KJ-A19-1',
                selected: false,
                content: 'Adapter Flow Control 14/20 T/C',
            },
            {
                id: '2',
                number: 'KJ-A19-2',
                selected: false,
                content: 'Adapter Flow Control 24/40 T/C',
            },
            {
                id: '3',
                number: '         KJ-A19-3',
                selected: false,
                content: 'Adapter Flow Control 14/20 외산T/C',
            },
            {
                id: '4',
                number: '         KJ-A19-4',
                selected: false,
                content: 'Adapter Flow Control 24/40 외산T/C',
            },
        ],
    },
    {
        type: 'glass',
        id: '20',
        image: '',
        classify: 'Adapters',
        title: 'Flow control',
        content: [],
        specification: [
            {
                id: '1',
                number: '         KJ-A20-1',
                selected: false,
                content: 'Adapter Flow Control 14/20 G/C',
            },
            {
                id: '2',
                number: '         KJ-A20-2',
                selected: false,
                content: 'Adapter Flow Control 24/40 G/C',
            },
            {
                id: '3',
                number: '         KJ-A20-3',
                selected: false,
                content: 'Adapter Flow Control 14/20 T/C',
            },
            {
                id: '4',
                number: 'KJ-A20-4',
                selected: false,
                content: 'Adapter Flow Control 24/40 T/C',
            },
            {
                id: '5',
                number: '         KJ-A20-5',
                selected: false,
                content: 'Adapter Flow Control 14/20 외산G/C',
            },
            {
                id: '6',
                number: '         KJ-A20-6',
                selected: false,
                content: 'Adapter Flow Control 24/40 외산G/C',
            },
            {
                id: '7',
                number: '         KJ-A20-7',
                selected: false,
                content: 'Adapter Flow Control 14/20 외산T/C',
            },
            {
                id: '8',
                number: '         KJ-A20-8',
                selected: false,
                content: 'Adapter Flow Control 24/40 외산T/C',
            },
        ],
    },
    {
        type: 'glass',
        id: '21',
        image: '',
        classify: 'Adapters',
        title: 'Innet',
        content: [],
        specification: [
            {
                id: '1',
                number: 'KJ-A21-1',
                selected: false,
                content: 'Adapter Inlet 14/20',
            },
            {
                id: '2',
                number: '         KJ-A21-2',
                selected: false,
                content: 'Adapter Inlet 24/40',
            },
        ],
    },
    {
        type: 'glass',
        id: '22',
        image: '',
        classify: 'Adapters',
        title: 'Innet',
        content: [],
        specification: [
            {
                id: '1',
                number: '         KJ-A22-1',
                selected: false,
                content: 'Adapter Inlet 14/20',
            },
            {
                id: '2',
                number: '         KJ-A22-2',
                selected: false,
                content: 'Adapter Inlet 24/40',
            },
        ],
    },
    {
        type: 'glass',
        id: '23',
        image: '',
        classify: 'Adapters',
        title: 'Innet',
        content: [],
        specification: [
            {
                id: '1',
                number: '         KJ-A23-1',
                selected: false,
                content: 'pter Inlet 14/20',
            },
            {
                id: '2',
                number: '         KJ-A23-2',
                selected: false,
                content: 'Adapter Inlet 24/40',
            },
        ],
    },
    {
        type: 'glass',
        id: '24',
        image: '',
        classify: 'Adapters',
        title: 'Innet',
        content: [],
        specification: [
            {
                id: '1',
                number: 'KJ-A24-1',
                selected: false,
                content: 'Adapter Inlet 14/20',
            },
            {
                id: '2',
                number: '         KJ-A24-2',
                selected: false,
                content: 'Adapter Inlet 24/40',
            },
        ],
    },
    {
        type: 'glass',
        id: '25',
        image: '',
        classify: 'Adapters',
        title: 'Innet',
        content: [],
        specification: [
            {
                id: '1',
                number: '         KJ-A25-1',
                selected: false,
                content: 'Adapter Inlet 14/20',
            },
            {
                id: '2',
                number: 'KJ-A25-2',
                selected: false,
                content: 'Adapter Inlet 24/40',
            },
        ],
    },
    {
        type: 'glass',
        id: '26',
        image: '',
        classify: 'Adapters',
        title: 'Innet',
        content: [],
        specification: [
            {
                id: '1',
                number: 'KJ-A26-1',
                selected: false,
                content: 'Adapter R:7mm',
            },
        ],
    },
    {
        type: 'glass',
        id: '27',
        image: '',
        classify: 'Adapters',
        title: 'Innet',
        content: [],
        specification: [
            {
                id: '1',
                number: '         KJ-A27-1',
                selected: false,
                content: 'Adapter Inlet 10/20',
            },
            {
                id: '2',
                number: '         KJ-A27-2',
                selected: false,
                content: 'Adapter Inlet 10/30',
            },
            {
                id: '3',
                number: '         KJ-A27-3',
                selected: false,
                content: 'Adapter Inlet 14/20',
            },
            {
                id: '4',
                number: '         KJ-A27-4',
                selected: false,
                content: 'Adapter Inlet 24/40',
            },
        ],
    },
    {
        type: 'glass',
        id: '28',
        image: '',
        classify: 'Adapters',
        title: 'Innet',
        content: [],
        specification: [
            {
                id: '1',
                number: 'KJ-A29-1',
                selected: false,
                content: 'apter Inlet 14/20',
            },
            {
                id: '2',
                number: 'KJ-A29-2',
                selected: false,
                content: 'Adapter Inlet 24/40',
            },
        ],
    },
    {
        type: 'glass',
        id: '29',
        image: '',
        classify: 'Adapters',
        title: 'Innet 3way stop cock',
        content: [],
        specification: [
            {
                id: '1',
                number: '         KJ-A30N-1',
                selected: false,
                content: 'Adapter Gas Inlet,3Way Stop Cock 14/20 G/C',
            },
            {
                id: '2',
                number: '         KJ-A30N-2',
                selected: false,
                content: 'Adapter Gas Inlet,3Way Stop Cock 24/40 G/C',
            },
            {
                id: '3',
                number: '         KJ-A30N-3',
                selected: false,
                content: 'Adapter Gas Inlet,3Way Stop Cock 14/20 T/C',
            },
            {
                id: '4',
                number: '         KJ-A30N-4',
                selected: false,
                content: 'Adapter Gas Inlet,3Way Stop Cock 24/40 T/C',
            },
            {
                id: '5',
                number: '         KJ-A30N-5',
                selected: false,
                content: 'Adapter Gas Inlet,3Way Stop Cock 14/20 외산G/C',
            },
            {
                id: '6',
                number: '         KJ-A30N-6',
                selected: false,
                content: 'Adapter Gas Inlet,3Way Stop Cock 24/40 외산G/C',
            },
            {
                id: '7',
                number: '         KJ-A30N-7',
                selected: false,
                content: 'Adapter Gas Inlet,3Way Stop Cock 14/20 외산T/C',
            },
            {
                id: '8',
                number: '         KJ-A30N-8',
                selected: false,
                content: 'Adapter Gas Inlet,3Way Stop Cock 24/40 외산T/C',
            },
        ],
    },
    {
        type: 'glass',
        id: '30',
        image: '',
        classify: 'Adapters',
        title: 'Septum inlet',
        content: [],
        specification: [
            {
                id: '1',
                number: '         KJ-A32-1',
                selected: false,
                content: 'Adapter Septum Inlet 14/20 T/C',
            },
            {
                id: '2',
                number: 'KJ-A32-2',
                selected: false,
                content: 'Adapter Septum Inlet 24/40 T/C',
            },
            {
                id: '3',
                number: '         KJ-A32-3',
                selected: false,
                content: 'Adapter Septum Inlet 34/45 T/C',
            },
            {
                id: '4',
                number: 'KJ-A32-4',
                selected: false,
                content: 'Adapter Septum Inlet 14/20 G/C',
            },
            {
                id: '5',
                number: '         KJ-A32-5',
                selected: false,
                content: 'Adapter Septum Inlet 24/40 G/C',
            },
            {
                id: '6',
                number: '         KJ-A32-6',
                selected: false,
                content: 'Adapter Septum Inlet 34/45 G/C',
            },
            {
                id: '7',
                number: '         KJ-A32-11',
                selected: false,
                content: 'Adapter Septum Inlet 14/20 외산T/C',
            },
            {
                id: '8',
                number: '         KJ-A32-12',
                selected: false,
                content: 'Adapter Septum Inlet 24/40 외산T/C',
            },
            {
                id: '9',
                number: '         KJ-A32-13',
                selected: false,
                content: 'Adapter Septum Inlet 34/45 외산T/C',
            },
            {
                id: '10',
                number: 'KJ-A32-15',
                selected: false,
                content: 'Adapter Septum Inlet 14/20 외산G/C',
            },
            {
                id: '11',
                number: '         KJ-A32-16',
                selected: false,
                content: 'Adapter Septum Inlet 24/40 외산G/C',
            },
            {
                id: '12',
                number: '         KJ-A32-17',
                selected: false,
                content: 'Adapter Septum Inlet 34/45 외산G/C',
            },
        ],
    },
];

export default items;
