const items = [
    {
        type: 'glass',
        id: '1',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F1.jpg?alt=media&token=bdf7b40f-70b1-48d3-bc75-0b2f82339e18',
        classify: 'Adapters',
        title: 'Bent distillation',
        content: [
            'bent 105˚ angle with a outer joint at top',
        ],
        specification: [
            {
                id: '1',
                number: 'KJ-A1-1',
                selected: false,
                content: 'Adapter Bent Distillation 14/20',
            },
            {
                id: '2',
                number: 'KJ-A1-2',
                selected: false,
                content: 'Adapter Bent Distillation 24/40',
            },
            {
                id: '3',
                number: 'KJ-A1-3',
                selected: false,
                content: 'Adapter Bent Distillation 19/38',
            },
            {
                id: '4',
                number: 'KJ-A1-4',
                selected: false,
                content: 'Adapter Bent Distillation 29/42',
            },
            {
                id: '5',
                number: 'KJ-A1-5',
                selected: false,
                content: 'Adapter Bent Distillation 34/45',
            },
        ],
    },
    {
        type: 'glass',
        id: '2',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F2.jpg?alt=media&token=ae470811-de2e-46f2-9c0b-f0706df13fcb',
        classify: 'Adapters',
        title: 'Bent distillation',
        content: [
            'outer joint at 105˚ angle with inner joint at bottom',
        ],
        specification: [
            {
                id: '1',
                number: 'KJ-A2-1',
                selected: false,
                content: 'Adapter Bent Distillation 14/20',
            },
            {
                id: '2',
                number: '         KJ-A2-2',
                selected: false,
                content: 'Adapter Bent Distillation 24/40',
            },
            {
                id: '3',
                number: 'KJ-A2-3',
                selected: false,
                content: 'Adapter Bent Distillation 29/42',
            },
            {
                id: '4',
                number: 'KJ-A2-4',
                selected: false,
                content: 'Adapter Bent Distillation 34/45',
            },
            {
                id: '5',
                number: 'KJ-A2-5',
                selected: false,
                content: 'Adapter Bent Distillation 19/38',
            },
        ],
    },
    {
        type: 'glass',
        id: '3',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F3.jpg?alt=media&token=26a3b7c6-810d-4c19-af20-03a1a9b675a5',
        classify: 'Adapters',
        title: 'Bent distillation',
        content: [
            '75˚ angle with inner joint each end',
        ],
        specification: [
            {
                id: '1',
                number: 'KJ-A3-1',
                selected: false,
                content: 'Adapter Bent Distillation 14/20',
            },
            {
                id: '2',
                number: '         KJ-A3-2',
                selected: false,
                content: 'Adapter Bent Distillation 24/40',
            },
            {
                id: '3',
                number: 'KJ-A3-3',
                selected: false,
                content: 'Adapter Bent Distillation 34/45',
            },
            {
                id: '4',
                number: '         KJ-A3-4',
                selected: false,
                content: 'Adapter Bent Distillation 19/38',
            },
            {
                id: '5',
                number: 'KJ-A3-5',
                selected: false,
                content: 'Adapter Bent Distillation 29/42',
            },
        ],
    },
    {
        type: 'glass',
        id: '4',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F4.jpg?alt=media&token=05082d9e-4d98-4730-9143-27168342d592',
        classify: 'Adapters',
        title: 'Vent jacket',
        content: [],
        specification: [
            {
                id: '1',
                number: '         KJ-A4-1',
                selected: false,
                content: 'Adapter Bent Jacket 14/20',
            },
            {
                id: '2',
                number: '         KJ-A4-2',
                selected: false,
                content: 'Adapter Bent Jacket 24/40',
            },
            {
                id: '3',
                number: '         KJ-A4-3',
                selected: false,
                content: 'Adapter Bent Jacket 34/45',
            },
            {
                id: '4',
                number: 'KJ-A4-4',
                selected: false,
                content: 'Adapter Bent Jacket 19/38',
            },
            {
                id: '5',
                number: 'KJ-A4-5',
                selected: false,
                content: 'Adapter Bent Jacket 29/42',
            },
        ],
    },
    {
        type: 'glass',
        id: '5',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F5.jpg?alt=media&token=e112acee-7bc2-4156-9469-41705accdd6f',
        classify: 'Adapters',
        title: 'Claisen',
        content: [],
        specification: [
            {
                id: '1',
                number: 'KJ-A5-1',
                selected: false,
                content: 'Adapter Claisen 14/20,14/20',
            },
            {
                id: '2',
                number: 'KJ-A5-2',
                selected: false,
                content: 'Adapter Claisen 24/40,14/20',
            },
            {
                id: '3',
                number: '         KJ-A5-3',
                selected: false,
                content: 'Adapter Claisen 14/20,10/20',
            },
            {
                id: '4',
                number: 'KJ-A5-4',
                selected: false,
                content: 'Adapter Claisen 24/40,10/20',
            },
            {
                id: '5',
                number: 'KJ-A5-5',
                selected: false,
                content: 'Adapter Claisen 19/28,10/20',
            },
            {
                id: '6',
                number: 'KJ-A5-6',
                selected: false,
                content: 'Adapter Claisen 29/42,10/20',
            },
            {
                id: '7',
                number: 'KJ-A5-7',
                selected: false,
                content: 'Adapter Claisen 34/45,10/20',
            },
        ],
    },
    {
        type: 'glass',
        id: '6',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F6.jpg?alt=media&token=48180d99-f1a9-4e9e-9578-84a3db7d187f',
        classify: 'Adapters',
        title: 'Claisen',
        content: [],
        specification: [
            {
                id: '1',
                number: '         KJ-A6-1',
                selected: false,
                content: 'ter Claisen 14/20',
            },
            {
                id: '2',
                number: '         KJ-A6-2',
                selected: false,
                content: 'Adapter Claisen 24/40',
            },
            {
                id: '3',
                number: 'KJ-A6-3',
                selected: false,
                content: 'Adapter Claisen 19/38',
            },
            {
                id: '4',
                number: '         KJ-A6-4',
                selected: false,
                content: 'Adapter Claisen 29/42',
            },
            {
                id: '5',
                number: '         KJ-A6-5',
                selected: false,
                content: 'Adapter Claisen 34/45',
            },
        ],
    },
    {
        type: 'glass',
        id: '7',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F7.jpg?alt=media&token=6f402208-54c2-405e-94e9-efde9f223def',
        classify: 'Adapters',
        title: 'Claisen',
        content: [],
        specification: [
            {
                id: '1',
                number: '         KJ-A7-1',
                selected: false,
                content: 'Adapter Claisen 14/20',
            },
            {
                id: '2',
                number: '         KJ-A7-2',
                selected: false,
                content: 'Adapter Claisen 24/40',
            },
            {
                id: '3',
                number: '         KJ-A7-3',
                selected: false,
                content: 'Adapter Claisen 19/38',
            },
            {
                id: '4',
                number: '         KJ-A7-4',
                selected: false,
                content: 'Adapter Claisen 29/42',
            },
            {
                id: '5',
                number: 'KJ-A7-5',
                selected: false,
                content: 'Adapter Claisen 34/45',
            },
        ],
    },
    {
        type: 'glass',
        id: '8',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F8.jpg?alt=media&token=485d2222-1fdc-4d0c-a996-57b625f2f0aa',
        classify: 'Adapters',
        title: 'Claisen',
        content: [],
        specification: [
            {
                id: '1',
                number: '         KJ-A8-1',
                selected: false,
                content: 'Adapter Claisen 24/40,10/20,10/30',
            },
            {
                id: '2',
                number: '         KJ-A8-2',
                selected: false,
                content: 'Adapter Claisen 24/40,14/20',
            },
            {
                id: '3',
                number: '         KJ-A8-3',
                selected: false,
                content: 'Adapter Claisen 14/40,10/20',
            },
            {
                id: '4',
                number: '         KJ-A8-4',
                selected: false,
                content: 'Adapter Claisen 14/20,14/20',
            },
            {
                id: '5',
                number: '         KJ-A8-5',
                selected: false,
                content: 'Adapter Claisen 24/40,24/40',
            },
        ],
    },
    {
        type: 'glass',
        id: '9',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F9.jpg?alt=media&token=d82f424f-fe46-4e6e-b249-68e2416be713',
        classify: 'Adapters',
        title: 'Claisen',
        content: [],
        specification: [
            {
                id: '1',
                number: '         KJ-A9-1',
                selected: false,
                content: 'Adapter Claisen 14/20,10/20',
            },
            {
                id: '2',
                number: 'KJ-A9-2',
                selected: false,
                content: 'Adapter Claisen 14/20,14/20',
            },
            {
                id: '3',
                number: '         KJ-A9-3',
                selected: false,
                content: 'Adapter Claisen 24/40,10/20',
            },
            {
                id: '4',
                number: '         KJ-A9-4',
                selected: false,
                content: 'Adapter Claisen 24/40,14/20',
            },
            {
                id: '5',
                number: 'KJ-A9-5',
                selected: false,
                content: 'Adapter Claisen 24/40,24/40',
            },
        ],
    },
    {
        type: 'glass',
        id: '10',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F10.jpg?alt=media&token=c6e867aa-0705-413f-b1c7-8cb97cfc48ef',
        classify: 'Adapters',
        title: 'Connecting',
        content: [],
        specification: [
            {
                id: '1',
                number: '         KJ-A10-1',
                selected: false,
                content: 'Adapter Connecting 14/20',
            },
            {
                id: '2',
                number: 'KJ-A10-2',
                selected: false,
                content: 'Adapter Connecting 24/40',
            },
            {
                id: '3',
                number: 'KJ-A10-3',
                selected: false,
                content: 'Adapter Connecting 19/38',
            },
            {
                id: '4',
                number: '         KJ-A10-4',
                selected: false,
                content: 'Adapter Connecting 29/42',
            },
            {
                id: '5',
                number: 'KJ-A10-5',
                selected: false,
                content: 'Adapter Connecting 34/45',
            },
        ],
    },
    {
        type: 'glass',
        id: '11',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F11.jpg?alt=media&token=ea5c4f38-6e57-412e-9ed4-59e4e9b36a99',
        classify: 'Adapters',
        title: 'Connecting',
        content: [],
        specification: [
            {
                id: '1',
                number: '         KJ-A11-1',
                selected: false,
                content: 'Adapter Connecting 10/30-14/20',
            },
            {
                id: '2',
                number: '         KJ-A11-2',
                selected: false,
                content: 'Adapter Connecting 10/30-24/40',
            },
            {
                id: '3',
                number: 'KJ-A11-3',
                selected: false,
                content: 'Adapter Connecting 14/20-10/30',
            },
            {
                id: '4',
                number: 'KJ-A11-4',
                selected: false,
                content: 'Adapter Connecting 14/20-24/40',
            },
            {
                id: '5',
                number: 'KJ-A11-5',
                selected: false,
                content: 'Adapter Connecting 24/40-14/20',
            },
            {
                id: '6',
                number: '         KJ-A11-6',
                selected: false,
                content: 'Adapter Connecting 24/40-34/45',
            },
            {
                id: '7',
                number: '         KJ-A11-7',
                selected: false,
                content: 'Adapter Connecting 24/40-45/50',
            },
            {
                id: '8',
                number: '         KJ-A11-8',
                selected: false,
                content: 'Adapter Connecting 24/40-50/50',
            },
            {
                id: '9',
                number: 'KJ-A11-9',
                selected: false,
                content: 'Adapter Connecting 34/45-24/40',
            },
            {
                id: '10',
                number: '         KJ-A11-10',
                selected: false,
                content: 'Adapter Connecting 45/50-24/40',
            },
            {
                id: '11',
                number: 'KJ-A11-11',
                selected: false,
                content: 'Adapter Connecting 14/20-19/38',
            },
            {
                id: '12',
                number: '         KJ-A11-12',
                selected: false,
                content: 'Adapter Connecting 19/38-14/20',
            },
            {
                id: '13',
                number: '         KJ-A11-13',
                selected: false,
                content: 'Adapter Connecting 24/40-29/42',
            },
            {
                id: '14',
                number: 'KJ-A11-14',
                selected: false,
                content: 'Adapter Connecting 29/42-24/40',
            },
            {
                id: '15',
                number: 'KJ-A11-15',
                selected: false,
                content: 'Adapter Connecting 34/40-45/50',
            },
            {
                id: '16',
                number: '         KJ-A11-16',
                selected: false,
                content: 'Adapter Connecting 34/45-50/50',
            },
        ],
    },
    {
        type: 'glass',
        id: '12',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F12.jpg?alt=media&token=91a285d5-e3e4-41e1-8707-d01095addee8',
        classify: 'Adapters',
        title: 'Connecting',
        content: [],
        specification: [
            {
                id: '1',
                number: '         KJ-A12-1',
                selected: false,
                content: 'Adapter Connecting 14/20,10/20',
            },
            {
                id: '2',
                number: 'KJ-A12-2',
                selected: false,
                content: 'Adapter Connecting 14/20,14/20',
            },
            {
                id: '3',
                number: '         KJ-A12-3',
                selected: false,
                content: 'Adapter Connecting 24/40,10/20',
            },
            {
                id: '4',
                number: 'KJ-A12-4',
                selected: false,
                content: 'Adapter Connecting 24/40,14/20',
            },
            {
                id: '5',
                number: '         KJ-A12-5',
                selected: false,
                content: 'Adapter Connecting 24/40,24/40',
            },
        ],
    },
    {
        type: 'glass',
        id: '13',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F13.jpg?alt=media&token=651f0441-21e9-4aea-855c-64ed7075f618',
        classify: 'Adapters',
        title: 'Connecting',
        content: [],
        specification: [
            {
                id: '1',
                number: 'KJ-A13-1',
                selected: false,
                content: 'Adapter Connecting 14/20',
            },
            {
                id: '2',
                number: 'KJ-A13-2',
                selected: false,
                content: 'Adapter Connecting 24/40',
            },
            {
                id: '3',
                number: 'KJ-A13-3',
                selected: false,
                content: 'Adapter Connecting 19/38',
            },
            {
                id: '4',
                number: 'KJ-A13-4',
                selected: false,
                content: 'apter Connecting 29/42',
            },
            {
                id: '5',
                number: 'KJ-A13-5',
                selected: false,
                content: 'Adapter Connecting 34/45',
            },
        ],
    },
    {
        type: 'glass',
        id: '14',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F14.jpg?alt=media&token=609b33b6-512a-446a-9014-57a1d6c2147e',
        classify: 'Adapters',
        title: 'Distilling',
        content: [],
        specification: [
            {
                id: '1',
                number: '         KJ-A14-1',
                selected: false,
                content: 'Adapter Distillating 14/20',
            },
            {
                id: '2',
                number: 'KJ-A14-2',
                selected: false,
                content: 'Adapter Distillating 24/40',
            },
            {
                id: '3',
                number: '         KJ-A14-3',
                selected: false,
                content: 'Adapter Distillating 29/42',
            },
            {
                id: '4',
                number: '         KJ-A14-4',
                selected: false,
                content: 'Adapter Distillating 34/45',
            },
        ],
    },
    {
        type: 'glass',
        id: '15',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F15.jpg?alt=media&token=0b9018c0-878a-4e6a-bec6-afc165eac792',
        classify: 'Adapters',
        title: 'Distilling',
        content: [],
        specification: [
            {
                id: '1',
                number: 'KJ-A15-1',
                selected: false,
                content: 'Adapter Distillating 14/20',
            },
            {
                id: '2',
                number: 'KJ-A15-2',
                selected: false,
                content: 'Adapter Distillating 24/40',
            },
            {
                id: '3',
                number: 'KJ-A15-3',
                selected: false,
                content: 'Adapter Distillating 29/42',
            },
            {
                id: '4',
                number: '         KJ-A15-4',
                selected: false,
                content: 'Adapter Distillating 34/45',
            },
        ],
    },
    {
        type: 'glass',
        id: '16',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F16.jpg?alt=media&token=b5b6d6f3-66c7-4a07-9102-00fe40f2acfb',
        classify: 'Adapters',
        title: 'Distilling',
        content: [],
        specification: [
            {
                id: '1',
                number: '         KJ-A16-1',
                selected: false,
                content: 'Adapter Distillating 14/20,10/20',
            },
            {
                id: '2',
                number: 'KJ-A16-2',
                selected: false,
                content: 'Adapter Distillating 14/20,14/20',
            },
            {
                id: '3',
                number: '         KJ-A16-3',
                selected: false,
                content: 'Adapter Distillating 24/40,10/20',
            },
            {
                id: '4',
                number: 'KJ-A16-4',
                selected: false,
                content: 'Adapter Distillating 24/40,14/20',
            },
        ],
    },
    {
        type: 'glass',
        id: '17',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F17.jpg?alt=media&token=cc3a9bad-ac1e-456c-ac56-3756a3b720a3',
        classify: 'Adapters',
        title: 'Vacuum filtration',
        content: [],
        specification: [
            {
                id: '1',
                number: '         KJ-A17-1',
                selected: false,
                content: 'Adapter Vacuum Filteration 14/20',
            },
            {
                id: '2',
                number: 'KJ-A17-2',
                selected: false,
                content: 'Adapter Vacuum Filteration 24/40',
            },
        ],
    },
    {
        type: 'glass',
        id: '18',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F18.jpg?alt=media&token=377e87bd-9429-479a-a144-5196a094ac86',
        classify: 'Adapters',
        title: 'Flow control, Glass Plug',
        content: [],
        specification: [
            {
                id: '1',
                number: '         KJ-A18-1',
                selected: false,
                content: 'Adapter Flow Control 14/20 G/C',
            },
            {
                id: '2',
                number: 'KJ-A18-2',
                selected: false,
                content: 'Adapter Flow Control 24/40 G/C',
            },
            {
                id: '3',
                number: '         KJ-A18-3',
                selected: false,
                content: 'Adapter Flow Control 14/20 외산G/C',
            },
            {
                id: '4',
                number: 'KJ-A18-4',
                selected: false,
                content: 'Adapter Flow Control 24/40 외산G/C',
            },
        ],
    },
    {
        type: 'glass',
        id: '19',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F19.jpg?alt=media&token=6c99400a-be00-41a6-82fb-e17356f42f31',
        classify: 'Adapters',
        title: 'Flow control, PTFE Plug',
        content: [],
        specification: [
            {
                id: '1',
                number: '         KJ-A19-1',
                selected: false,
                content: 'Adapter Flow Control 14/20 T/C',
            },
            {
                id: '2',
                number: 'KJ-A19-2',
                selected: false,
                content: 'Adapter Flow Control 24/40 T/C',
            },
            {
                id: '3',
                number: '         KJ-A19-3',
                selected: false,
                content: 'Adapter Flow Control 14/20 외산T/C',
            },
            {
                id: '4',
                number: '         KJ-A19-4',
                selected: false,
                content: 'Adapter Flow Control 24/40 외산T/C',
            },
        ],
    },
    {
        type: 'glass',
        id: '20',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F20.jpg?alt=media&token=70720ebc-d36e-4cda-9f1e-90650d71d230',
        classify: 'Adapters',
        title: 'Flow control',
        content: [],
        specification: [
            {
                id: '1',
                number: '         KJ-A20-1',
                selected: false,
                content: 'Adapter Flow Control 14/20 G/C',
            },
            {
                id: '2',
                number: '         KJ-A20-2',
                selected: false,
                content: 'Adapter Flow Control 24/40 G/C',
            },
            {
                id: '3',
                number: '         KJ-A20-3',
                selected: false,
                content: 'Adapter Flow Control 14/20 T/C',
            },
            {
                id: '4',
                number: 'KJ-A20-4',
                selected: false,
                content: 'Adapter Flow Control 24/40 T/C',
            },
            {
                id: '5',
                number: '         KJ-A20-5',
                selected: false,
                content: 'Adapter Flow Control 14/20 외산G/C',
            },
            {
                id: '6',
                number: '         KJ-A20-6',
                selected: false,
                content: 'Adapter Flow Control 24/40 외산G/C',
            },
            {
                id: '7',
                number: '         KJ-A20-7',
                selected: false,
                content: 'Adapter Flow Control 14/20 외산T/C',
            },
            {
                id: '8',
                number: '         KJ-A20-8',
                selected: false,
                content: 'Adapter Flow Control 24/40 외산T/C',
            },
        ],
    },
    {
        type: 'glass',
        id: '21',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F21.jpg?alt=media&token=0124e9c4-b6e5-4fd5-a451-a054f0247200',
        classify: 'Adapters',
        title: 'Innet',
        content: [],
        specification: [
            {
                id: '1',
                number: 'KJ-A21-1',
                selected: false,
                content: 'Adapter Inlet 14/20',
            },
            {
                id: '2',
                number: '         KJ-A21-2',
                selected: false,
                content: 'Adapter Inlet 24/40',
            },
        ],
    },
    {
        type: 'glass',
        id: '22',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F22.jpg?alt=media&token=830029d4-2d1a-432e-9301-d8752e228c28',
        classify: 'Adapters',
        title: 'Innet',
        content: [],
        specification: [
            {
                id: '1',
                number: '         KJ-A22-1',
                selected: false,
                content: 'Adapter Inlet 14/20',
            },
            {
                id: '2',
                number: '         KJ-A22-2',
                selected: false,
                content: 'Adapter Inlet 24/40',
            },
        ],
    },
    {
        type: 'glass',
        id: '23',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F23.jpg?alt=media&token=fcbde592-b58f-4ef4-a2b4-f1d9873e981f',
        classify: 'Adapters',
        title: 'Innet',
        content: [],
        specification: [
            {
                id: '1',
                number: '         KJ-A23-1',
                selected: false,
                content: 'pter Inlet 14/20',
            },
            {
                id: '2',
                number: '         KJ-A23-2',
                selected: false,
                content: 'Adapter Inlet 24/40',
            },
        ],
    },
    {
        type: 'glass',
        id: '24',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F24.jpg?alt=media&token=abe3cc57-293e-4356-b57b-51ff4e67816c',
        classify: 'Adapters',
        title: 'Innet',
        content: [],
        specification: [
            {
                id: '1',
                number: 'KJ-A24-1',
                selected: false,
                content: 'Adapter Inlet 14/20',
            },
            {
                id: '2',
                number: '         KJ-A24-2',
                selected: false,
                content: 'Adapter Inlet 24/40',
            },
        ],
    },
    {
        type: 'glass',
        id: '25',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F25.jpg?alt=media&token=1a4995a6-474f-4524-9a92-5d8b5678489f',
        classify: 'Adapters',
        title: 'Innet',
        content: [],
        specification: [
            {
                id: '1',
                number: '         KJ-A25-1',
                selected: false,
                content: 'Adapter Inlet 14/20',
            },
            {
                id: '2',
                number: 'KJ-A25-2',
                selected: false,
                content: 'Adapter Inlet 24/40',
            },
        ],
    },
    {
        type: 'glass',
        id: '26',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F26.jpg?alt=media&token=94fd4a36-3de2-4d0c-989d-523b77df1324',
        classify: 'Adapters',
        title: 'Innet',
        content: [],
        specification: [
            {
                id: '1',
                number: 'KJ-A26-1',
                selected: false,
                content: 'Adapter R:7mm',
            },
        ],
    },
    {
        type: 'glass',
        id: '27',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F27.jpg?alt=media&token=71903781-b041-4159-862a-105517dedccf',
        classify: 'Adapters',
        title: 'Innet',
        content: [],
        specification: [
            {
                id: '1',
                number: '         KJ-A27-1',
                selected: false,
                content: 'Adapter Inlet 10/20',
            },
            {
                id: '2',
                number: '         KJ-A27-2',
                selected: false,
                content: 'Adapter Inlet 10/30',
            },
            {
                id: '3',
                number: '         KJ-A27-3',
                selected: false,
                content: 'Adapter Inlet 14/20',
            },
            {
                id: '4',
                number: '         KJ-A27-4',
                selected: false,
                content: 'Adapter Inlet 24/40',
            },
        ],
    },
    {
        type: 'glass',
        id: '28',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F28.jpg?alt=media&token=10159d9b-c676-4f75-9299-f23a42a84a81',
        classify: 'Adapters',
        title: 'Innet',
        content: [],
        specification: [
            {
                id: '1',
                number: 'KJ-A29-1',
                selected: false,
                content: 'apter Inlet 14/20',
            },
            {
                id: '2',
                number: 'KJ-A29-2',
                selected: false,
                content: 'Adapter Inlet 24/40',
            },
        ],
    },
    {
        type: 'glass',
        id: '29',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F29.jpg?alt=media&token=73b2c0d7-f653-40a0-9956-bff0e5f0bd27',
        classify: 'Adapters',
        title: 'Innet 3way stop cock',
        content: [],
        specification: [
            {
                id: '1',
                number: '         KJ-A30N-1',
                selected: false,
                content: 'Adapter Gas Inlet,3Way Stop Cock 14/20 G/C',
            },
            {
                id: '2',
                number: '         KJ-A30N-2',
                selected: false,
                content: 'Adapter Gas Inlet,3Way Stop Cock 24/40 G/C',
            },
            {
                id: '3',
                number: '         KJ-A30N-3',
                selected: false,
                content: 'Adapter Gas Inlet,3Way Stop Cock 14/20 T/C',
            },
            {
                id: '4',
                number: '         KJ-A30N-4',
                selected: false,
                content: 'Adapter Gas Inlet,3Way Stop Cock 24/40 T/C',
            },
            {
                id: '5',
                number: '         KJ-A30N-5',
                selected: false,
                content: 'Adapter Gas Inlet,3Way Stop Cock 14/20 외산G/C',
            },
            {
                id: '6',
                number: '         KJ-A30N-6',
                selected: false,
                content: 'Adapter Gas Inlet,3Way Stop Cock 24/40 외산G/C',
            },
            {
                id: '7',
                number: '         KJ-A30N-7',
                selected: false,
                content: 'Adapter Gas Inlet,3Way Stop Cock 14/20 외산T/C',
            },
            {
                id: '8',
                number: '         KJ-A30N-8',
                selected: false,
                content: 'Adapter Gas Inlet,3Way Stop Cock 24/40 외산T/C',
            },
        ],
    },
    {
        type: 'glass',
        id: '30',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F30.jpg?alt=media&token=b58ad6af-e480-4282-a0f9-9fc5e8e17bd7',
        classify: 'Adapters',
        title: 'Septum inlet',
        content: [],
        specification: [
            {
                id: '1',
                number: '         KJ-A32-1',
                selected: false,
                content: 'Adapter Septum Inlet 14/20 T/C',
            },
            {
                id: '2',
                number: 'KJ-A32-2',
                selected: false,
                content: 'Adapter Septum Inlet 24/40 T/C',
            },
            {
                id: '3',
                number: '         KJ-A32-3',
                selected: false,
                content: 'Adapter Septum Inlet 34/45 T/C',
            },
            {
                id: '4',
                number: 'KJ-A32-4',
                selected: false,
                content: 'Adapter Septum Inlet 14/20 G/C',
            },
            {
                id: '5',
                number: '         KJ-A32-5',
                selected: false,
                content: 'Adapter Septum Inlet 24/40 G/C',
            },
            {
                id: '6',
                number: '         KJ-A32-6',
                selected: false,
                content: 'Adapter Septum Inlet 34/45 G/C',
            },
            {
                id: '7',
                number: '         KJ-A32-11',
                selected: false,
                content: 'Adapter Septum Inlet 14/20 외산T/C',
            },
            {
                id: '8',
                number: '         KJ-A32-12',
                selected: false,
                content: 'Adapter Septum Inlet 24/40 외산T/C',
            },
            {
                id: '9',
                number: '         KJ-A32-13',
                selected: false,
                content: 'Adapter Septum Inlet 34/45 외산T/C',
            },
            {
                id: '10',
                number: 'KJ-A32-15',
                selected: false,
                content: 'Adapter Septum Inlet 14/20 외산G/C',
            },
            {
                id: '11',
                number: '         KJ-A32-16',
                selected: false,
                content: 'Adapter Septum Inlet 24/40 외산G/C',
            },
            {
                id: '12',
                number: '         KJ-A32-17',
                selected: false,
                content: 'Adapter Septum Inlet 34/45 외산G/C',
            },
        ],
    },
    {
        type: 'glass',
        id: '31',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F31.jpg?alt=media&token=0f5087ab-8957-435b-971c-a83c5dfbf21d',
        classify: 'Adapters',
        title: 'Vent',
        content: [],
        specification: [
            {
                id: '1',
                number: '         KJ-A33-1',
                selected: false,
                content: 'Adapter Vent 14/20',
            },
            {
                id: '2',
                number: '         KJ-A33-2',
                selected: false,
                content: 'Adapter Vent 24/40',
            },
            {
                id: '3',
                number: '         KJ-A33-3',
                selected: false,
                content: 'Adapter Vent 19/38',
            },
            {
                id: '4',
                number: '         KJ-A33-4',
                selected: false,
                content: 'Adapter Vent 29/42',
            },
            {
                id: '5',
                number: ' KJ-A33-5',
                selected: false,
                content: 'Adapter Vent 34/45',
            },
        ],
    },
    {
        type: 'glass',
        id: '32',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F32.jpg?alt=media&token=c4011476-a8a8-4c88-9364-a6b498e89964',
        classify: 'Adapters',
        title: 'Vent, inlet/outlet',
        content: [],
        specification: [
            {
                id: '1',
                number: '         KJ-A34-1',
                selected: false,
                content: 'Adapter Vent Inlet 14/20',
            },
            {
                id: '2',
                number: '         KJ-A34-2',
                selected: false,
                content: 'Adapter Vent Outer 14/20',
            },
            {
                id: '3',
                number: '         KJ-A34-3',
                selected: false,
                content: 'Adapter Vent Inlet 24/40',
            },
            {
                id: '4',
                number: '         KJ-A34-4',
                selected: false,
                content: 'Adapter Vent Outer 24/40',
            },
        ],
    },
    {
        type: 'glass',
        id: '33',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F33.jpg?alt=media&token=53ea6c4a-d617-4d8b-bc9f-48801a3e3bed',
        classify: 'Adapters',
        title: 'Offset',
        content: [],
        specification: [
            {
                id: '1',
                number: '         KJ-A35-1',
                selected: false,
                content: 'Adapter Offset 14/20',
            },
            {
                id: '2',
                number: '         KJ-A35-2',
                selected: false,
                content: 'Adapter Offset 24/40',
            },
        ],
    },
    {
        type: 'glass',
        id: '34',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F34.jpg?alt=media&token=79124b56-3654-4917-a7c9-07b8b5b9ef0f',
        classify: 'Adapters',
        title: 'Thermometer',
        content: [],
        specification: [
            {
                id: '1',
                number: 'KJ-A36-1',
                selected: false,
                content: 'Adapter Thermometer 24/40',
            },
            {
                id: '2',
                number: '         KJ-A36-2',
                selected: false,
                content: 'Adapter Thermometer 29/42',
            },
        ],
    },
    {
        type: 'glass',
        id: '35',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F35.jpg?alt=media&token=a3708c8d-afed-4f0c-b887-07c87589e856',
        classify: 'Adapters',
        title: 'Universal inlet/vacuum',
        content: [],
        specification: [
            {
                id: '1',
                number: '         KJ-A37-1',
                selected: false,
                content: 'Adapter Universal Inlet/Vacuum GL14번 14/20',
            },
            {
                id: '2',
                number: '         KJ-A37-2',
                selected: false,
                content: 'Adapter Universal Inlet/Vacuum GL14번 24/40',
            },
        ],
    },
    {
        type: 'glass',
        id: '36',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F36.jpg?alt=media&token=940f2c4a-4536-49e9-b2c9-3ea8f1fdf1b6',
        classify: 'Adapters',
        title: 'Universal offset',
        content: [],
        specification: [
            {
                id: '1',
                number: 'KJ-A38-1',
                selected: false,
                content: 'Adapter Universal Offset 14/20 GL14번',
            },
            {
                id: '2',
                number: '         KJ-A38-2',
                selected: false,
                content: 'Adapter Universal Offset 24/40 GL14번',
            },
        ],
    },
    {
        type: 'glass',
        id: '37',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F37.jpg?alt=media&token=e26f81f5-62f5-49d0-addd-e3a6bfda7700',
        classify: 'Adapters',
        title: 'Universal Double offset',
        content: [],
        specification: [
            {
                id: '1',
                number: '         KJ-A39-1',
                selected: false,
                content: 'Adapter Universal Double Offset 24/25',
            },
        ],
    },
    {
        type: 'glass',
        id: '38',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F38.jpg?alt=media&token=960d52d5-a35a-48d9-b12b-156270ffdb28',
        classify: 'Adapters',
        title: 'Vacuum',
        content: [],
        specification: [
            {
                id: '1',
                number: '         KJ-A40-1',
                selected: false,
                content: 'apter Vacuum 14/20',
            },
            {
                id: '2',
                number: '         KJ-A40-2',
                selected: false,
                content: 'Adapter Vacuum 24/40',
            },
            {
                id: '3',
                number: 'KJ-A40-3',
                selected: false,
                content: 'Adapter Vacuum 34/45',
            },
        ],
    },
    {
        type: 'glass',
        id: '39',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F39.jpg?alt=media&token=00fd8baf-b173-4fb7-a5bd-2c48732b7c05',
        classify: 'Adapters',
        title: 'Vacuum filtration',
        content: [],
        specification: [
            {
                id: '1',
                number: ' KJ-A49-1',
                selected: false,
                content: 'Adapter Filtering 14/20',
            },
            {
                id: '2',
                number: 'KJ-A49-2',
                selected: false,
                content: 'Adapter Filtering 24/40',
            },
            {
                id: '3',
                number: 'KJ-A49-3',
                selected: false,
                content: 'Adapter Filtering 29/32',
            },
            {
                id: '4',
                number: 'KJ-A49-4',
                selected: false,
                content: 'Adapter Filtering 34/45',
            },
        ],
    },
    {
        type: 'glass',
        id: '40',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F40.jpg?alt=media&token=2f06eb51-5e97-433b-be08-126b1a1d29ed',
        classify: 'Adapters',
        title: 'Vacuum filtration',
        content: [],
        specification: [
            {
                id: '1',
                number: 'KJ-A50-1',
                selected: false,
                content: 'Adapter Filtering 14/20',
            },
            {
                id: '2',
                number: 'KJ-A50-2',
                selected: false,
                content: 'Adapter Filtering 19/22',
            },
            {
                id: '3',
                number: 'KJ-A50-3',
                selected: false,
                content: 'Adapter Filtering 24/40',
            },
            {
                id: '4',
                number: 'KJ-A50-4',
                selected: false,
                content: 'Adapter Filtering 34/45',
            },
        ],
    },
    {
        type: 'glass',
        id: '41',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F41.jpg?alt=media&token=e7336da6-c0a6-4182-984f-0ce3dd07a5c0',
        classify: 'Adapters',
        title: 'Solid addition',
        content: [],
        specification: [
            {
                id: '1',
                number: 'KJ-A51-1',
                selected: false,
                content: 'Adapter Solid Addition 24/40',
            },
        ],
    },
    {
        type: 'glass',
        id: '42',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F42.jpg?alt=media&token=45be49e7-3741-4214-a6ac-1fb4c4ff8f68',
        classify: 'Adapters',
        title: 'Distillation collector',
        content: [],
        specification: [
            {
                id: '1',
                number: ' KJ-A52-1',
                selected: false,
                content: 'Adapter 14/20',
            },
            {
                id: '2',
                number: 'KJ-A52-2',
                selected: false,
                content: 'Adapter 24/20',
            },
        ],
    },
    {
        type: 'glass',
        id: '43',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F43.jpg?alt=media&token=24f57b22-92ea-49b0-a8dd-685521898a3d',
        classify: 'Adapters',
        title: 'Thermometer O-ring PTFE cotting',
        content: [],
        specification: [
            {
                id: '1',
                number: 'KJ-A53-1',
                selected: false,
                content: 'Adapter Thermometer O-ring PTFE Cotting 14/20,GL14',
            },
            {
                id: '2',
                number: ' KJ-A53-2',
                selected: false,
                content: 'Adapter Thermometer O-ring PTFE Cotting 24/40,GL14',
            },
            {
                id: '3',
                number: 'KJ-A53-3',
                selected: false,
                content: 'Adapter Thermometer O-ring PTFE Cotting 29/42,GL14',
            },
        ],
    },
    {
        type: 'glass',
        id: '44',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F44.jpg?alt=media&token=9b0684a8-692e-4f4d-afcf-b6189e2ff350',
        classify: 'Adapters',
        title: 'Connecting',
        content: [],
        specification: [
            {
                id: '1',
                number: 'KJ-A54-1',
                selected: false,
                content: 'Adapter Connecting 14/20,GL14',
            },
            {
                id: '2',
                number: 'KJ-A54-2',
                selected: false,
                content: 'Adapter Connecting 24/40,GL14',
            },
            {
                id: '3',
                number: 'KJ-A54-3',
                selected: false,
                content: 'Adapter Connecting 19/22,GL14',
            },
            {
                id: '4',
                number: 'KJ-A54-4',
                selected: false,
                content: 'Adapter Connecting 29/32,GL14',
            },
            {
                id: '5',
                number: 'KJ-A54-5',
                selected: false,
                content: 'Adapter Connecting 34/45,GL14',
            },
        ],
    },
    {
        type: 'glass',
        id: '45',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F45.jpg?alt=media&token=170fcd08-0b38-4e0e-9291-c4d43f2973c2',
        classify: 'Adapters',
        title: 'Claisen',
        content: [],
        specification: [
            {
                id: '1',
                number: 'KJ-A55-1',
                selected: false,
                content: 'Adapter Claisen 14/20,GL14',
            },
            {
                id: '2',
                number: 'KJ-A55-2',
                selected: false,
                content: 'Adapter Claisen 24/40,GL14',
            },
            {
                id: '3',
                number: 'KJ-A55-3',
                selected: false,
                content: 'Adapter Claisen 19/22,GL14',
            },
            {
                id: '4',
                number: 'KJ-A55-4',
                selected: false,
                content: 'Adapter Claisen 29/32,GL14',
            },
            {
                id: '5',
                number: ' KJ-A55-5',
                selected: false,
                content: 'Adapter Claisen 34/45,GL14',
            },
        ],
    },
    {
        type: 'glass',
        id: '46',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F46.jpg?alt=media&token=66d46356-c0a7-405c-aecd-24d8e4a266ac',
        classify: 'Adapters',
        title: 'Claisen',
        content: [],
        specification: [
            {
                id: '1',
                number: 'KJ-A56-1',
                selected: false,
                content: 'Adapter Claisen 14/20,GL14',
            },
            {
                id: '2',
                number: 'KJ-A56-2',
                selected: false,
                content: 'Adapter Claisen 24/40,GL14',
            },
            {
                id: '3',
                number: 'KJ-A56-3',
                selected: false,
                content: 'Adapter Claisen 19/22,GL14',
            },
            {
                id: '4',
                number: 'KJ-A56-4',
                selected: false,
                content: 'Adapter Claisen 29/32,GL14',
            },
            {
                id: '5',
                number: 'KJ-A56-5',
                selected: false,
                content: 'Adapter Claisen 34/45,GL14',
            },
        ],
    },
    {
        type: 'glass',
        id: '47',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F47.jpg?alt=media&token=446cc158-dc2f-4877-88ee-59966f79b29c',
        classify: 'Adapters',
        title: 'Distilling claisen',
        content: [],
        specification: [
            {
                id: '1',
                number: 'KJ-A57-1',
                selected: false,
                content: 'Adapter Distilling Claisen 10/20,14/20',
            },
            {
                id: '2',
                number: 'KJ-A57-2',
                selected: false,
                content: 'Adapter Distilling Claisen 10/20,24/40',
            },
            {
                id: '3',
                number: 'KJ-A57-3',
                selected: false,
                content: 'Adapter Distilling Claisen 10/20,29/32',
            },
            {
                id: '4',
                number: 'KJ-A57-4',
                selected: false,
                content: 'Adapter Distilling Claisen GL14,14/20',
            },
            {
                id: '5',
                number: 'KJ-A57-5',
                selected: false,
                content: 'Adapter Distilling Claisen GL14,24/40',
            },
            {
                id: '6',
                number: 'KJ-A57-6',
                selected: false,
                content: 'Adapter Distilling Claisen GL14,29/32',
            },
        ],
    },
    {
        type: 'glass',
        id: '48',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F48.jpg?alt=media&token=ac13ada3-5dcd-43bf-b6a0-ff7b476b0cb6',
        classify: 'Beaker',
        title: 'Griffin, low form',
        content: [],
        specification: [
            {
                id: '1',
                number: 'KJ-B1-1',
                selected: false,
                content: 'Beaker Griffin Form 50ML(IWAKI)',
            },
            {
                id: '2',
                number: 'KJ-B1-2',
                selected: false,
                content: 'Beaker Griffin Form 100ML(IWAKI)',
            },
            {
                id: '3',
                number: 'KJ-B1-3',
                selected: false,
                content: 'Beaker Griffin Form 250ML(IWAKI)',
            },
            {
                id: '4',
                number: 'KJ-B1-4',
                selected: false,
                content: 'Beaker Griffin Form 400ML(IWAKI)',
            },
            {
                id: '5',
                number: 'KJ-B1-5',
                selected: false,
                content: 'Beaker Griffin Form 500ML(IWAKI)',
            },
            {
                id: '6',
                number: 'KJ-B1-6',
                selected: false,
                content: 'Beaker Griffin Form 600ML(IWAKI)',
            },
            {
                id: '7',
                number: 'KJ-B1-7',
                selected: false,
                content: 'Beaker Griffin Form 1000ML(IWAKI)',
            },
            {
                id: '8',
                number: 'KJ-B1-8',
                selected: false,
                content: 'Beaker Griffin Form 2000ML(IWAKI)',
            },
            {
                id: '9',
                number: 'KJ-B1-9',
                selected: false,
                content: 'Beaker Griffin Form 3000ML(IWAKI)',
            },
            {
                id: '10',
                number: 'KJ-B1-10',
                selected: false,
                content: 'Beaker Griffin Form 5000ML(IWAKI)',
            },
        ],
    },
    {
        type: 'glass',
        id: '49',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F49.jpg?alt=media&token=93925363-70a8-4a6a-b94b-e6fff36a9400',
        classify: 'Burets',
        title: 'Buret',
        content: [],
        specification: [
            {
                id: '1',
                number: 'KJ-BU1-1C',
                selected: false,
                content: 'Buret Glass Plug , Clear 10ML (WITEG)',
            },
            {
                id: '2',
                number: 'KJ-BU1-1A',
                selected: false,
                content: 'Buret Glass Plug ,Amber 10ML (WITEG)',
            },
            {
                id: '3',
                number: 'KJ-BU1-2C',
                selected: false,
                content: 'Buret Glass Plug, Clear 25ML (WITEG)',
            },
            {
                id: '4',
                number: 'KJ-BU1-2A',
                selected: false,
                content: 'Buret Glass Plug, Amber 25ML (WITEG)',
            },
            {
                id: '5',
                number: 'KJ-BU1-3C',
                selected: false,
                content: 'Buret Glass Plug, Clear 50ML (WITEG)',
            },
            {
                id: '6',
                number: 'KJ-BU1-3A',
                selected: false,
                content: 'Buret Glass Plug, Amber 50ML (WITEG)',
            },
            {
                id: '7',
                number: 'KJ-BU1-4C',
                selected: false,
                content: 'Buret PTFE Plug , Clear 10ML (WITEG)',
            },
            {
                id: '8',
                number: 'KJ-BU1-4A',
                selected: false,
                content: 'Buret PTFE Plug ,Amber 10ML (WITEG)',
            },
            {
                id: '9',
                number: 'KJ-BU1-4S',
                selected: false,
                content: 'Buret Screw Cock , Clear 10ML (WITEG)',
            },
            {
                id: '10',
                number: 'KJ-BU1-4SA',
                selected: false,
                content: 'Buret Screw Cock , Amber 10ML (WITEG)',
            },
            {
                id: '11',
                number: 'KJ-BU1-5C',
                selected: false,
                content: 'Buret PTFE Plug , Clear 25ML (WITEG)',
            },
            {
                id: '12',
                number: 'KJ-BU1-5A',
                selected: false,
                content: 'Buret PTFE Plug ,Amber 25ML (WITEG)',
            },
            {
                id: '13',
                number: 'KJ-BU1-5S',
                selected: false,
                content: 'Buret Screw Cock , Clear 25ML (WITEG)',
            },
            {
                id: '14',
                number: 'KJ-BU1-5SA',
                selected: false,
                content: 'Buret Screw Cock , Amber 25ML (WITEG)',
            },
            {
                id: '15',
                number: 'KJ-BU1-6C',
                selected: false,
                content: 'Buret PTFE Plug , Clear 50ML (WITEG)',
            },
            {
                id: '16',
                number: 'KJ-BU1-6A',
                selected: false,
                content: 'Buret PTFE Plug ,Amber 50ML (WITEG)',
            },
            {
                id: '17',
                number: 'KJ-BU1-6S',
                selected: false,
                content: 'Buret Screw Cock , Clear 50ML (WITEG)',
            },
            {
                id: '18',
                number: 'KJ-BU1-6SA',
                selected: false,
                content: 'Buret Screw Cock , Amber 50ML (WITEG)',
            },
            {
                id: '19',
                number: 'KJ-BU1-7C',
                selected: false,
                content: 'Buret Glass Plug , Clear 5ML (WITEG)',
            },
            {
                id: '20',
                number: 'KJ-BU1-7A',
                selected: false,
                content: 'Buret Glass Plug ,Amber 5ML (WITEG)',
            },
            {
                id: '21',
                number: 'KJ-BU1-8C',
                selected: false,
                content: 'Buret PTFE Plug , Clear 5ML (WITEG)',
            },
            {
                id: '22',
                number: 'KJ-BU1-8A',
                selected: false,
                content: 'Buret PTFE Plug ,Amber 5ML (WITEG)',
            },
            {
                id: '23',
                number: 'KJ-BU1-9C',
                selected: false,
                content: 'Buret Glass Plug , Clear 100ML (WITEG)',
            },
            {
                id: '24',
                number: ' KJ-BU1-9A',
                selected: false,
                content: 'Buret Glass Plug ,Amber 100ML (WITEG)',
            },
            {
                id: '25',
                number: 'KJ-BU1-10C',
                selected: false,
                content: 'Buret PTFE Plug , Clear 100ML (WITEG)',
            },
            {
                id: '26',
                number: 'KJ-BU1-10A',
                selected: false,
                content: 'Buret PTFE Plug ,Amber 100ML (WITEG)',
            },
            {
                id: '27',
                number: 'KJ-BU1-10S',
                selected: false,
                content: 'Buret Screw Cock , Clear 100ML (WITEG)',
            },
            {
                id: '28',
                number: 'KJ-BU1-10SA',
                selected: false,
                content: 'Buret Screw Cock , Amber 100ML (WITEG)',
            },
        ],
    },
    {
        type: 'glass',
        id: '50',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F50.jpg?alt=media&token=9a1f9946-283e-4fb6-89f6-c69ef19d41d8',
        classify: 'Burets',
        title: 'Buret G/C',
        content: [],
        specification: [
            {
                id: '1',
                number: ' KJ-BU2-1',
                selected: false,
                content: 'Buret Glass Plug 250ML',
            },
            {
                id: '2',
                number: ' KJ-BU2-2',
                selected: false,
                content: 'Buret Glass Plug 500ML',
            },
            {
                id: '3',
                number: 'KJ-BU2-3',
                selected: false,
                content: 'Buret Glass Plug 1000ML',
            },
            {
                id: '4',
                number: 'KJ-BU2-4',
                selected: false,
                content: 'Buret Glass Plug 2000ML',
            },
        ],
    },
    {
        type: 'glass',
        id: '51',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F51.jpg?alt=media&token=75e22c64-ce31-45fb-94a1-aca65445adf2',
        classify: 'Burets',
        title: 'Buret T/C',
        content: [],
        specification: [
            {
                id: '1',
                number: 'KJ-BU3-1',
                selected: false,
                content: 'Buret PTFE 250ML',
            },
            {
                id: '2',
                number: 'KJ-BU3-2',
                selected: false,
                content: 'Buret PTFE 500ML',
            },
            {
                id: '3',
                number: 'KJ-BU3-3',
                selected: false,
                content: 'Buret PTFE 1000ML',
            },
            {
                id: '4',
                number: 'KJ-BU3-4',
                selected: false,
                content: 'Buret PTFE 2000ML',
            },
        ],
    },
    {
        type: 'glass',
        id: '52',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F52.jpg?alt=media&token=cd837d79-1e00-49bd-9494-5e6b1013acde',
        classify: 'Burets',
        title: 'Buret T/C',
        content: [],
        specification: [
            {
                id: '1',
                number: 'KJ-BU4-1',
                selected: false,
                content: 'Buret Clear 10ML',
            },
            {
                id: '2',
                number: 'KJ-BU4-1A',
                selected: false,
                content: 'Buret Amber 10ML',
            },
            {
                id: '3',
                number: 'KJ-BU4-2',
                selected: false,
                content: 'Buret Clear 25ML',
            },
            {
                id: '4',
                number: ' KJ-BU4-2A',
                selected: false,
                content: 'Buret Amber 25ML',
            },
            {
                id: '5',
                number: 'KJ-BU4-3',
                selected: false,
                content: 'Buret Clear 50ML',
            },
            {
                id: '6',
                number: 'KJ-BU4-3A',
                selected: false,
                content: 'Buret Amber 50ML',
            },
        ],
    },
    {
        type: 'glass',
        id: '53',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F53.jpg?alt=media&token=3286d22f-3c11-4b29-a625-27ccb770e219',
        classify: 'Adapters',
        title: 'Connecting',
        content: [],
        specification: [
            {
                id: '1',
                number: 'KJ-A43-1',
                selected: false,
                content: 'Adapter Connecting 14/20',
            },
            {
                id: '2',
                number: 'KJ-A43-2',
                selected: false,
                content: 'Adapter Connecting 24/40',
            },
        ],
    },
    {
        type: 'glass',
        id: '54',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F54.jpg?alt=media&token=44699f6b-2f37-476c-96f6-05120178c673',
        classify: 'Adapters',
        title: 'Connecting',
        content: [],
        specification: [
            {
                id: '1',
                number: 'KJ-A44-1',
                selected: false,
                content: 'Adapter Connecting 14/20',
            },
            {
                id: '2',
                number: 'KJ-A44-2',
                selected: false,
                content: 'Adapter Connecting 24/40',
            },
        ],
    },
    {
        type: 'glass',
        id: '55',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F55.jpg?alt=media&token=76584186-9276-491f-8468-146ad6b38992',
        classify: 'Adapters',
        title: 'Connecting',
        content: [],
        specification: [
            {
                id: '1',
                number: ' KJ-A45-1',
                selected: false,
                content: 'Adapter Connecting 14/20',
            },
            {
                id: '2',
                number: 'KJ-A45-2',
                selected: false,
                content: 'Adapter Connecting 24/40',
            },
        ],
    },
    {
        type: 'glass',
        id: '56',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F56.jpg?alt=media&token=40b23993-3e7b-478f-8eb7-6ee0df6f3b9e',
        classify: 'Adapters',
        title: 'Connecting',
        content: [],
        specification: [
            {
                id: '1',
                number: 'KJ-A46-1',
                selected: false,
                content: 'Adapter Connecting 14/20 G/C',
            },
            {
                id: '2',
                number: 'KJ-A46-2',
                selected: false,
                content: 'Adapter Connecting 24/40 G/C',
            },
            {
                id: '3',
                number: 'KJ-A46-3',
                selected: false,
                content: 'Adapter Connecting 34/45 G/C',
            },
            {
                id: '4',
                number: ' KJ-A46-4',
                selected: false,
                content: 'Adapter Connecting 14/20 T/C',
            },
            {
                id: '5',
                number: 'KJ-A46-5',
                selected: false,
                content: 'Adapter Connecting 24/40 T/C',
            },
            {
                id: '6',
                number: 'KJ-A46-6',
                selected: false,
                content: 'Adapter Connecting 34/45 T/C',
            },
            {
                id: '7',
                number: 'KJ-A46-7',
                selected: false,
                content: 'Adapter Connecting 14/20 외산G/C',
            },
            {
                id: '8',
                number: 'KJ-A46-8',
                selected: false,
                content: 'Adapter Connecting 24/40 외산G/C',
            },
            {
                id: '9',
                number: ' KJ-A46-9',
                selected: false,
                content: 'Adapter Connecting 34/45 외산G/C',
            },
            {
                id: '10',
                number: 'KJ-A46-10',
                selected: false,
                content: 'Adapter Connecting 14/20 외산T/C',
            },
            {
                id: '11',
                number: ' KJ-A46-11',
                selected: false,
                content: 'Adapter Connecting 24/40 외산T/C',
            },
            {
                id: '12',
                number: 'KJ-A46-12',
                selected: false,
                content: 'Adapter Connecting 34/45 외산T/C',
            },
        ],
    },
    {
        type: 'glass',
        id: '57',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F57.jpg?alt=media&token=76e94c99-d8dc-4e86-93cb-867d0c15719d',
        classify: 'Adapters',
        title: 'Connecting',
        content: [],
        specification: [
            {
                id: '1',
                number: 'KJ-A47-1',
                selected: false,
                content: 'Adapter Connecting 14/20',
            },
            {
                id: '2',
                number: 'KJ-A47-2',
                selected: false,
                content: 'Adapter Connecting 24/40',
            },
        ],
    },
    {
        type: 'glass',
        id: '58',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F58.jpg?alt=media&token=1f79799a-3876-4c04-abe1-325499cd24ec',
        classify: 'Condensers',
        title: 'Condenser, allihn',
        content: [
            'with drip joint and outer top',
        ],
        specification: [
            {
                id: '1',
                number: 'KJ-C1-1',
                selected: false,
                content: 'Condenser Allihn 24/40 200mm',
            },
            {
                id: '2',
                number: 'KJ-C1-2',
                selected: false,
                content: 'Condenser Allihn 24/40 250mm',
            },
            {
                id: '3',
                number: '         KJ-C1-3',
                selected: false,
                content: 'Condenser Allihn 24/40 300mm',
            },
            {
                id: '4',
                number: '         KJ-C1-4',
                selected: false,
                content: 'enser Allihn 24/40 400mm',
            },
            {
                id: '5',
                number: 'KJ-C1-5',
                selected: false,
                content: 'Condenser Allihn 29/42 400mm',
            },
            {
                id: '6',
                number: '         KJ-C1-6',
                selected: false,
                content: 'Condenser Allihn 34/45 400mm',
            },
        ],
    },
    {
        type: 'glass',
        id: '59',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F59.jpg?alt=media&token=73e16458-91e4-4438-8f49-5df9fd763af1',
        classify: 'Condensers',
        title: 'Condenser, allihn',
        content: [
            'with straight outlet tube at top and water cooled inner drip joint at bottom',
        ],
        specification: [
            {
                id: '1',
                number: 'KJ-C2-1',
                selected: false,
                content: 'Condenser Allihn 24/40',
            },
            {
                id: '2',
                number: 'KJ-C2-2',
                selected: false,
                content: 'Condenser Allihn 34/45',
            },
            {
                id: '3',
                number: 'KJ-C2-3',
                selected: false,
                content: 'Condenser Allihn 45/50',
            },
            {
                id: '4',
                number: '         KJ-C2-4',
                selected: false,
                content: 'Condenser Allihn 50/55',
            },
            {
                id: '5',
                number: '         KJ-C2-5',
                selected: false,
                content: 'Condenser Allihn 55/50',
            },
        ],
    },
    {
        type: 'glass',
        id: '60',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F60.jpg?alt=media&token=dae96898-6f06-4357-8176-072372006298',
        classify: 'Condensers',
        title: 'Condenser, allihn',
        content: [],
        specification: [
            {
                id: '1',
                number: '         KJ-C3-1',
                selected: false,
                content: 'Condenser Allihn 24/40',
            },
            {
                id: '2',
                number: 'KJ-C3-2',
                selected: false,
                content: 'nser Allihn 29/42',
            },
            {
                id: '3',
                number: '         KJ-C3-3',
                selected: false,
                content: 'Condenser Allihn 35/45',
            },
            {
                id: '4',
                number: '         KJ-C3-4',
                selected: false,
                content: 'Condenser Allihn 45/50',
            },
            {
                id: '5',
                number: '         KJ-C3-5',
                selected: false,
                content: 'Condenser Allihn 50/55',
            },
            {
                id: '6',
                number: 'KJ-C3-6',
                selected: false,
                content: 'Condenser Allihn 55/50',
            },
        ],
    },
    {
        type: 'glass',
        id: '61',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F61.jpg?alt=media&token=87088589-df75-4382-8997-e45387310413',
        classify: 'Condensers',
        title: 'Condenser, cold finger',
        content: [],
        specification: [
            {
                id: '1',
                number: '         KJ-C4-1',
                selected: false,
                content: 'Condenser Cold Finger 24/40',
            },
            {
                id: '2',
                number: 'KJ-C4-2',
                selected: false,
                content: 'Condenser Cold Finger 14/20',
            },
        ],
    },
    {
        type: 'glass',
        id: '62',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F62.jpg?alt=media&token=2695f97b-1a66-4460-b0ba-b02181a24bb9',
        classify: 'Condensers',
        title: 'Condenser, concentrator',
        content: [],
        specification: [
            {
                id: '1',
                number: '         KJ-C5-1',
                selected: false,
                content: 'Condenser Concentrator 24/40, 24/40',
            },
            {
                id: '2',
                number: 'KJ-C5-2',
                selected: false,
                content: 'Condenser Concentrator 34/45, 24/40',
            },
            {
                id: '3',
                number: '         KJ-C5-3',
                selected: false,
                content: 'Condenser Concentrator 24/40, 14/20',
            },
        ],
    },
    {
        type: 'glass',
        id: '63',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F63.jpg?alt=media&token=bfbdb442-17eb-4c70-ad9d-63b80bcb7d54',
        classify: 'Condensers',
        title: 'Condenser, dewar',
        content: [],
        specification: [
            {
                id: '1',
                number: '         KJ-C6-1',
                selected: false,
                content: 'Condenser Dewar 14/20,100ml',
            },
            {
                id: '2',
                number: '         KJ-C6-2',
                selected: false,
                content: 'Condenser Dewar 24/40,400ml',
            },
            {
                id: '3',
                number: '         KJ-C6-3',
                selected: false,
                content: 'Condenser Dewar 24/40,1000ml',
            },
        ],
    },
    {
        type: 'glass',
        id: '64',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F64.jpg?alt=media&token=bdd8550d-212c-4f55-93f7-7c1083c0cbb2',
        classify: 'Condensers',
        title: 'Condenser, friedrich',
        content: [
            'inclined outer joint on side and two hose connectors at top. Inner drip joint at bottom',
        ],
        specification: [
            {
                id: '1',
                number: '         KJ-C7-1',
                selected: false,
                content: 'Condenser Friedrich 24/40',
            },
            {
                id: '2',
                number: '         KJ-C7-2',
                selected: false,
                content: 'Condenser Friedrich 34/45',
            },
            {
                id: '3',
                number: '         KJ-C7-3',
                selected: false,
                content: 'nser Friedrich 45/50',
            },
        ],
    },
    {
        type: 'glass',
        id: '65',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F65.jpg?alt=media&token=217cce4c-6e50-4f94-8f1d-ad9f3a08da5f',
        classify: 'Condensers',
        title: 'Condenser, friedrich',
        content: [
            'water inlet and outer located above ring sealed inner condensing tube.)',
        ],
        specification: [
            {
                id: '1',
                number: '         KJ-C8-1',
                selected: false,
                content: 'er Friedrich 24/40',
            },
            {
                id: '2',
                number: '         KJ-C8-3',
                selected: false,
                content: 'Condenser Friedrich 34/45',
            },
            {
                id: '3',
                number: '         KJ-C8-4',
                selected: false,
                content: 'Condenser Friedrich 45/50',
            },
            {
                id: '4',
                number: 'KJ-C8-5',
                selected: false,
                content: 'Condenser Friedrich 55/50',
            },
            {
                id: '5',
                number: '         KJ-C8-6',
                selected: false,
                content: 'Condenser Friedrich 60/50',
            },
        ],
    },
    {
        type: 'glass',
        id: '66',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F66.jpg?alt=media&token=e547db11-2b55-40d1-a8d3-017cc21aa1b3',
        classify: 'Condensers',
        title: 'Condenser, graham',
        content: [],
        specification: [
            {
                id: '1',
                number: '         KJ-C9-1',
                selected: false,
                content: 'Condenser Graham 24/40 200mm',
            },
            {
                id: '2',
                number: '         KJ-C9-2',
                selected: false,
                content: 'Condenser Graham 24/40 250mm',
            },
            {
                id: '3',
                number: '         KJ-C9-3',
                selected: false,
                content: 'Condenser Graham 24/40 300mm',
            },
            {
                id: '4',
                number: '         KJ-C9-4',
                selected: false,
                content: 'Condenser Graham 24/40 400mm',
            },
            {
                id: '5',
                number: '         KJ-C9-5',
                selected: false,
                content: 'Condenser Graham 14/20 120mm',
            },
            {
                id: '6',
                number: 'KJ-C9-6',
                selected: false,
                content: 'Condenser Graham 19/38 180mm',
            },
            {
                id: '7',
                number: '         KJ-C9-7',
                selected: false,
                content: 'Condenser Graham 29/42 280mm',
            },
            {
                id: '8',
                number: '         KJ-C9-8',
                selected: false,
                content: 'Condenser Graham 34/45 350mm',
            },
        ],
    },
    {
        type: 'glass',
        id: '67',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F67.jpg?alt=media&token=fb85b459-4216-4039-9ac7-629def07c320',
        classify: 'Condensers',
        title: 'Condenser, liebig',
        content: [],
        specification: [
            {
                id: '1',
                number: '         KJ-C10-1',
                selected: false,
                content: 'Condenser Liebig 14/20',
            },
            {
                id: '2',
                number: '         KJ-C10-2',
                selected: false,
                content: 'Condenser Liebig 24/40',
            },
        ],
    },
    {
        type: 'glass',
        id: '68',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F68.jpg?alt=media&token=3b6d4055-f7ab-43aa-9ead-bda49908b6f6',
        classify: 'Condensers',
        title: 'Condenser, liebig',
        content: [],
        specification: [
            {
                id: '1',
                number: '         KJ-C11-1',
                selected: false,
                content: 'Condenser Liebig 24/40 100mm',
            },
            {
                id: '2',
                number: 'KJ-C11-2',
                selected: false,
                content: 'Condenser Liebig 24/40 200mm',
            },
            {
                id: '3',
                number: '         KJ-C11-3',
                selected: false,
                content: 'Condenser Liebig 24/40 250mm',
            },
            {
                id: '4',
                number: '         KJ-C11-4',
                selected: false,
                content: 'Condenser Liebig 24/40 300mm',
            },
            {
                id: '5',
                number: 'KJ-C11-5',
                selected: false,
                content: 'Condenser Liebig 24/40 400mm',
            },
            {
                id: '6',
                number: 'KJ-C11-6',
                selected: false,
                content: 'Condenser Liebig 34/45 400mm',
            },
        ],
    },
    {
        type: 'glass',
        id: '69',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F69.jpg?alt=media&token=2adff4f7-e021-4c1c-b3b7-122225962720',
        classify: 'Condensers',
        title: 'Condenser, liebig',
        content: [],
        specification: [
            {
                id: '1',
                number: '         KJ-C12-1',
                selected: false,
                content: 'Condenser Liebig 24/40 320mm',
            },
            {
                id: '2',
                number: 'KJ-C12-2',
                selected: false,
                content: 'Condenser Liebig 14/20 200mm',
            },
        ],
    },
    {
        type: 'glass',
        id: '70',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F70.jpg?alt=media&token=1ec1d2c8-b920-48b6-8e8b-d92c9849aff4',
        classify: 'Condensers',
        title: 'Condenser, reflux',
        content: [],
        specification: [
            {
                id: '1',
                number: '         KJ-C13-2',
                selected: false,
                content: 'Condenser Reflux 19/38',
            },
            {
                id: '2',
                number: 'KJ-C13-3',
                selected: false,
                content: 'Condenser Reflux 24/40',
            },
        ],
    },
    {
        type: 'glass',
        id: '71',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F71.jpg?alt=media&token=29c07f6c-6f8c-4cbc-8619-dbbb2f896c9c',
        classify: 'Condensers',
        title: 'Condenser, reflux',
        content: [],
        specification: [
            {
                id: '1',
                number: '         KJ-C14-1',
                selected: false,
                content: 'Condenser Reflux 14/20',
            },
            {
                id: '2',
                number: '         KJ-C14-2',
                selected: false,
                content: 'Condenser Reflux 24/40',
            },
        ],
    },
    {
        type: 'glass',
        id: '72',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F72.jpg?alt=media&token=ffca5d8e-efbb-43c0-888b-51be70b7bf0d',
        classify: 'Condensers',
        title: 'Condenser, reflux',
        content: [],
        specification: [
            {
                id: '1',
                number: '         KJ-C15-1',
                selected: false,
                content: 'Condenser Reflux 24/40 200mm',
            },
            {
                id: '2',
                number: '         KJ-C15-2',
                selected: false,
                content: 'Condenser Reflux 24/40 300mm',
            },
            {
                id: '3',
                number: 'KJ-C15-3',
                selected: false,
                content: 'Condenser Reflux 14/20 150mm',
            },
        ],
    },
    {
        type: 'glass',
        id: '73',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F73.jpg?alt=media&token=3fe25c52-3a69-4159-8388-945e3db5bdbd',
        classify: 'Condensers',
        title: 'Condenser, reflux Jacket',
        content: [],
        specification: [
            {
                id: '1',
                number: '         KJ-C16-1',
                selected: false,
                content: 'Condenser Reflux Jacket 24/40 225mm',
            },
            {
                id: '2',
                number: 'KJ-C16-2',
                selected: false,
                content: 'Condenser Reflux Jacket 34/45 280mm',
            },
            {
                id: '3',
                number: 'KJ-C16-3',
                selected: false,
                content: 'Condenser Reflux Jacket 24/40 350mm',
            },
        ],
    },
    {
        type: 'glass',
        id: '74',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F74.jpg?alt=media&token=f3637375-83f8-40aa-9378-518ed2b38454',
        classify: 'Condensers',
        title: 'Condenser, spiral reflux',
        content: [],
        specification: [
            {
                id: '1',
                number: '         KJ-C17-1',
                selected: false,
                content: 'Condenser Spiral Refluex 14/20 120mm',
            },
        ],
    },
    {
        type: 'glass',
        id: '75',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F75.jpg?alt=media&token=18c75500-0662-408d-ae61-933be7ab6b26',
        classify: 'Columns',
        title: 'Column, PTFE Plug',
        content: [],
        specification: [
            {
                id: '1',
                number: 'KJ-CO2-1',
                selected: false,
                content: 'Column Chromatography 11*200',
            },
            {
                id: '2',
                number: 'KJ-CO2-2',
                selected: false,
                content: 'Column Chromatography 15*250',
            },
            {
                id: '3',
                number: 'KJ-CO2-3',
                selected: false,
                content: 'Column Chromatography 19*300',
            },
            {
                id: '4',
                number: 'KJ-CO2-4',
                selected: false,
                content: 'Column Chromatography 22*350',
            },
            {
                id: '5',
                number: 'KJ-CO2-5',
                selected: false,
                content: 'Column Chromatography 30*400',
            },
            {
                id: '6',
                number: 'KJ-CO2-6',
                selected: false,
                content: 'Column Chromatography 41*500',
            },
            {
                id: '7',
                number: 'KJ-CO2-7',
                selected: false,
                content: 'Column Chromatography 49*700',
            },
            {
                id: '8',
                number: 'KJ-CO2-8',
                selected: false,
                content: 'Column Chromatography 60*700',
            },
            {
                id: '9',
                number: 'KJ-CO2-9',
                selected: false,
                content: 'Column Chromatography 70*700',
            },
            {
                id: '10',
                number: 'KJ-CO2-10',
                selected: false,
                content: 'Column Chromatography 80*700',
            },
            {
                id: '11',
                number: 'KJ-CO2-11',
                selected: false,
                content: 'Column Chromatography 90*800',
            },
        ],
    },
];

export default items;
