const items = [
    {
        type: 'glass',
        id: '1',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F1.jpg?alt=media&token=bdf7b40f-70b1-48d3-bc75-0b2f82339e18',
        classify: 'Adapters',
        title: 'Bent distillation',
        content: [
            'bent 105˚ angle with a outer joint at top',
        ],
        specification: [
            {
                id: '1',
                number: 'KJ-A1-1',
                selected: false,
                content: 'Adapter Bent Distillation 14/20',
            },
            {
                id: '2',
                number: 'KJ-A1-2',
                selected: false,
                content: 'Adapter Bent Distillation 24/40',
            },
            {
                id: '3',
                number: 'KJ-A1-3',
                selected: false,
                content: 'Adapter Bent Distillation 19/38',
            },
            {
                id: '4',
                number: 'KJ-A1-4',
                selected: false,
                content: 'Adapter Bent Distillation 29/42',
            },
            {
                id: '5',
                number: 'KJ-A1-5',
                selected: false,
                content: 'Adapter Bent Distillation 34/45',
            },
        ],
    },
    {
        type: 'glass',
        id: '2',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F2.jpg?alt=media&token=ae470811-de2e-46f2-9c0b-f0706df13fcb',
        classify: 'Adapters',
        title: 'Bent distillation',
        content: [
            'outer joint at 105˚ angle with inner joint at bottom',
        ],
        specification: [
            {
                id: '1',
                number: 'KJ-A2-1',
                selected: false,
                content: 'Adapter Bent Distillation 14/20',
            },
            {
                id: '2',
                number: '         KJ-A2-2',
                selected: false,
                content: 'Adapter Bent Distillation 24/40',
            },
            {
                id: '3',
                number: 'KJ-A2-3',
                selected: false,
                content: 'Adapter Bent Distillation 29/42',
            },
            {
                id: '4',
                number: 'KJ-A2-4',
                selected: false,
                content: 'Adapter Bent Distillation 34/45',
            },
            {
                id: '5',
                number: 'KJ-A2-5',
                selected: false,
                content: 'Adapter Bent Distillation 19/38',
            },
        ],
    },
    {
        type: 'glass',
        id: '3',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F3.jpg?alt=media&token=26a3b7c6-810d-4c19-af20-03a1a9b675a5',
        classify: 'Adapters',
        title: 'Bent distillation',
        content: [
            '75˚ angle with inner joint each end',
        ],
        specification: [
            {
                id: '1',
                number: 'KJ-A3-1',
                selected: false,
                content: 'Adapter Bent Distillation 14/20',
            },
            {
                id: '2',
                number: '         KJ-A3-2',
                selected: false,
                content: 'Adapter Bent Distillation 24/40',
            },
            {
                id: '3',
                number: 'KJ-A3-3',
                selected: false,
                content: 'Adapter Bent Distillation 34/45',
            },
            {
                id: '4',
                number: '         KJ-A3-4',
                selected: false,
                content: 'Adapter Bent Distillation 19/38',
            },
            {
                id: '5',
                number: 'KJ-A3-5',
                selected: false,
                content: 'Adapter Bent Distillation 29/42',
            },
        ],
    },
    {
        type: 'glass',
        id: '4',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F4.jpg?alt=media&token=05082d9e-4d98-4730-9143-27168342d592',
        classify: 'Adapters',
        title: 'Vent jacket',
        content: [],
        specification: [
            {
                id: '1',
                number: '         KJ-A4-1',
                selected: false,
                content: 'Adapter Bent Jacket 14/20',
            },
            {
                id: '2',
                number: '         KJ-A4-2',
                selected: false,
                content: 'Adapter Bent Jacket 24/40',
            },
            {
                id: '3',
                number: '         KJ-A4-3',
                selected: false,
                content: 'Adapter Bent Jacket 34/45',
            },
            {
                id: '4',
                number: 'KJ-A4-4',
                selected: false,
                content: 'Adapter Bent Jacket 19/38',
            },
            {
                id: '5',
                number: 'KJ-A4-5',
                selected: false,
                content: 'Adapter Bent Jacket 29/42',
            },
        ],
    },
    {
        type: 'glass',
        id: '5',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F5.jpg?alt=media&token=e112acee-7bc2-4156-9469-41705accdd6f',
        classify: 'Adapters',
        title: 'Claisen',
        content: [],
        specification: [
            {
                id: '1',
                number: 'KJ-A5-1',
                selected: false,
                content: 'Adapter Claisen 14/20,14/20',
            },
            {
                id: '2',
                number: 'KJ-A5-2',
                selected: false,
                content: 'Adapter Claisen 24/40,14/20',
            },
            {
                id: '3',
                number: '         KJ-A5-3',
                selected: false,
                content: 'Adapter Claisen 14/20,10/20',
            },
            {
                id: '4',
                number: 'KJ-A5-4',
                selected: false,
                content: 'Adapter Claisen 24/40,10/20',
            },
            {
                id: '5',
                number: 'KJ-A5-5',
                selected: false,
                content: 'Adapter Claisen 19/28,10/20',
            },
            {
                id: '6',
                number: 'KJ-A5-6',
                selected: false,
                content: 'Adapter Claisen 29/42,10/20',
            },
            {
                id: '7',
                number: 'KJ-A5-7',
                selected: false,
                content: 'Adapter Claisen 34/45,10/20',
            },
        ],
    },
    {
        type: 'glass',
        id: '6',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F6.jpg?alt=media&token=48180d99-f1a9-4e9e-9578-84a3db7d187f',
        classify: 'Adapters',
        title: 'Claisen',
        content: [],
        specification: [
            {
                id: '1',
                number: '         KJ-A6-1',
                selected: false,
                content: 'ter Claisen 14/20',
            },
            {
                id: '2',
                number: '         KJ-A6-2',
                selected: false,
                content: 'Adapter Claisen 24/40',
            },
            {
                id: '3',
                number: 'KJ-A6-3',
                selected: false,
                content: 'Adapter Claisen 19/38',
            },
            {
                id: '4',
                number: '         KJ-A6-4',
                selected: false,
                content: 'Adapter Claisen 29/42',
            },
            {
                id: '5',
                number: '         KJ-A6-5',
                selected: false,
                content: 'Adapter Claisen 34/45',
            },
        ],
    },
    {
        type: 'glass',
        id: '7',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F7.jpg?alt=media&token=6f402208-54c2-405e-94e9-efde9f223def',
        classify: 'Adapters',
        title: 'Claisen',
        content: [],
        specification: [
            {
                id: '1',
                number: '         KJ-A7-1',
                selected: false,
                content: 'Adapter Claisen 14/20',
            },
            {
                id: '2',
                number: '         KJ-A7-2',
                selected: false,
                content: 'Adapter Claisen 24/40',
            },
            {
                id: '3',
                number: '         KJ-A7-3',
                selected: false,
                content: 'Adapter Claisen 19/38',
            },
            {
                id: '4',
                number: '         KJ-A7-4',
                selected: false,
                content: 'Adapter Claisen 29/42',
            },
            {
                id: '5',
                number: 'KJ-A7-5',
                selected: false,
                content: 'Adapter Claisen 34/45',
            },
        ],
    },
    {
        type: 'glass',
        id: '8',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F8.jpg?alt=media&token=485d2222-1fdc-4d0c-a996-57b625f2f0aa',
        classify: 'Adapters',
        title: 'Claisen',
        content: [],
        specification: [
            {
                id: '1',
                number: '         KJ-A8-1',
                selected: false,
                content: 'Adapter Claisen 24/40,10/20,10/30',
            },
            {
                id: '2',
                number: '         KJ-A8-2',
                selected: false,
                content: 'Adapter Claisen 24/40,14/20',
            },
            {
                id: '3',
                number: '         KJ-A8-3',
                selected: false,
                content: 'Adapter Claisen 14/40,10/20',
            },
            {
                id: '4',
                number: '         KJ-A8-4',
                selected: false,
                content: 'Adapter Claisen 14/20,14/20',
            },
            {
                id: '5',
                number: '         KJ-A8-5',
                selected: false,
                content: 'Adapter Claisen 24/40,24/40',
            },
        ],
    },
    {
        type: 'glass',
        id: '9',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F9.jpg?alt=media&token=d82f424f-fe46-4e6e-b249-68e2416be713',
        classify: 'Adapters',
        title: 'Claisen',
        content: [],
        specification: [
            {
                id: '1',
                number: '         KJ-A9-1',
                selected: false,
                content: 'Adapter Claisen 14/20,10/20',
            },
            {
                id: '2',
                number: 'KJ-A9-2',
                selected: false,
                content: 'Adapter Claisen 14/20,14/20',
            },
            {
                id: '3',
                number: '         KJ-A9-3',
                selected: false,
                content: 'Adapter Claisen 24/40,10/20',
            },
            {
                id: '4',
                number: '         KJ-A9-4',
                selected: false,
                content: 'Adapter Claisen 24/40,14/20',
            },
            {
                id: '5',
                number: 'KJ-A9-5',
                selected: false,
                content: 'Adapter Claisen 24/40,24/40',
            },
        ],
    },
    {
        type: 'glass',
        id: '10',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F10.jpg?alt=media&token=c6e867aa-0705-413f-b1c7-8cb97cfc48ef',
        classify: 'Adapters',
        title: 'Connecting',
        content: [],
        specification: [
            {
                id: '1',
                number: '         KJ-A10-1',
                selected: false,
                content: 'Adapter Connecting 14/20',
            },
            {
                id: '2',
                number: 'KJ-A10-2',
                selected: false,
                content: 'Adapter Connecting 24/40',
            },
            {
                id: '3',
                number: 'KJ-A10-3',
                selected: false,
                content: 'Adapter Connecting 19/38',
            },
            {
                id: '4',
                number: '         KJ-A10-4',
                selected: false,
                content: 'Adapter Connecting 29/42',
            },
            {
                id: '5',
                number: 'KJ-A10-5',
                selected: false,
                content: 'Adapter Connecting 34/45',
            },
        ],
    },
    {
        type: 'glass',
        id: '11',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F11.jpg?alt=media&token=ea5c4f38-6e57-412e-9ed4-59e4e9b36a99',
        classify: 'Adapters',
        title: 'Connecting',
        content: [],
        specification: [
            {
                id: '1',
                number: '         KJ-A11-1',
                selected: false,
                content: 'Adapter Connecting 10/30-14/20',
            },
            {
                id: '2',
                number: '         KJ-A11-2',
                selected: false,
                content: 'Adapter Connecting 10/30-24/40',
            },
            {
                id: '3',
                number: 'KJ-A11-3',
                selected: false,
                content: 'Adapter Connecting 14/20-10/30',
            },
            {
                id: '4',
                number: 'KJ-A11-4',
                selected: false,
                content: 'Adapter Connecting 14/20-24/40',
            },
            {
                id: '5',
                number: 'KJ-A11-5',
                selected: false,
                content: 'Adapter Connecting 24/40-14/20',
            },
            {
                id: '6',
                number: '         KJ-A11-6',
                selected: false,
                content: 'Adapter Connecting 24/40-34/45',
            },
            {
                id: '7',
                number: '         KJ-A11-7',
                selected: false,
                content: 'Adapter Connecting 24/40-45/50',
            },
            {
                id: '8',
                number: '         KJ-A11-8',
                selected: false,
                content: 'Adapter Connecting 24/40-50/50',
            },
            {
                id: '9',
                number: 'KJ-A11-9',
                selected: false,
                content: 'Adapter Connecting 34/45-24/40',
            },
            {
                id: '10',
                number: '         KJ-A11-10',
                selected: false,
                content: 'Adapter Connecting 45/50-24/40',
            },
            {
                id: '11',
                number: 'KJ-A11-11',
                selected: false,
                content: 'Adapter Connecting 14/20-19/38',
            },
            {
                id: '12',
                number: '         KJ-A11-12',
                selected: false,
                content: 'Adapter Connecting 19/38-14/20',
            },
            {
                id: '13',
                number: '         KJ-A11-13',
                selected: false,
                content: 'Adapter Connecting 24/40-29/42',
            },
            {
                id: '14',
                number: 'KJ-A11-14',
                selected: false,
                content: 'Adapter Connecting 29/42-24/40',
            },
            {
                id: '15',
                number: 'KJ-A11-15',
                selected: false,
                content: 'Adapter Connecting 34/40-45/50',
            },
            {
                id: '16',
                number: '         KJ-A11-16',
                selected: false,
                content: 'Adapter Connecting 34/45-50/50',
            },
        ],
    },
    {
        type: 'glass',
        id: '12',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F12.jpg?alt=media&token=91a285d5-e3e4-41e1-8707-d01095addee8',
        classify: 'Adapters',
        title: 'Connecting',
        content: [],
        specification: [
            {
                id: '1',
                number: '         KJ-A12-1',
                selected: false,
                content: 'Adapter Connecting 14/20,10/20',
            },
            {
                id: '2',
                number: 'KJ-A12-2',
                selected: false,
                content: 'Adapter Connecting 14/20,14/20',
            },
            {
                id: '3',
                number: '         KJ-A12-3',
                selected: false,
                content: 'Adapter Connecting 24/40,10/20',
            },
            {
                id: '4',
                number: 'KJ-A12-4',
                selected: false,
                content: 'Adapter Connecting 24/40,14/20',
            },
            {
                id: '5',
                number: '         KJ-A12-5',
                selected: false,
                content: 'Adapter Connecting 24/40,24/40',
            },
        ],
    },
    {
        type: 'glass',
        id: '13',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F13.jpg?alt=media&token=651f0441-21e9-4aea-855c-64ed7075f618',
        classify: 'Adapters',
        title: 'Connecting',
        content: [],
        specification: [
            {
                id: '1',
                number: 'KJ-A13-1',
                selected: false,
                content: 'Adapter Connecting 14/20',
            },
            {
                id: '2',
                number: 'KJ-A13-2',
                selected: false,
                content: 'Adapter Connecting 24/40',
            },
            {
                id: '3',
                number: 'KJ-A13-3',
                selected: false,
                content: 'Adapter Connecting 19/38',
            },
            {
                id: '4',
                number: 'KJ-A13-4',
                selected: false,
                content: 'apter Connecting 29/42',
            },
            {
                id: '5',
                number: 'KJ-A13-5',
                selected: false,
                content: 'Adapter Connecting 34/45',
            },
        ],
    },
    {
        type: 'glass',
        id: '14',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F14.jpg?alt=media&token=609b33b6-512a-446a-9014-57a1d6c2147e',
        classify: 'Adapters',
        title: 'Distilling',
        content: [],
        specification: [
            {
                id: '1',
                number: '         KJ-A14-1',
                selected: false,
                content: 'Adapter Distillating 14/20',
            },
            {
                id: '2',
                number: 'KJ-A14-2',
                selected: false,
                content: 'Adapter Distillating 24/40',
            },
            {
                id: '3',
                number: '         KJ-A14-3',
                selected: false,
                content: 'Adapter Distillating 29/42',
            },
            {
                id: '4',
                number: '         KJ-A14-4',
                selected: false,
                content: 'Adapter Distillating 34/45',
            },
        ],
    },
    {
        type: 'glass',
        id: '15',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F15.jpg?alt=media&token=0b9018c0-878a-4e6a-bec6-afc165eac792',
        classify: 'Adapters',
        title: 'Distilling',
        content: [],
        specification: [
            {
                id: '1',
                number: 'KJ-A15-1',
                selected: false,
                content: 'Adapter Distillating 14/20',
            },
            {
                id: '2',
                number: 'KJ-A15-2',
                selected: false,
                content: 'Adapter Distillating 24/40',
            },
            {
                id: '3',
                number: 'KJ-A15-3',
                selected: false,
                content: 'Adapter Distillating 29/42',
            },
            {
                id: '4',
                number: '         KJ-A15-4',
                selected: false,
                content: 'Adapter Distillating 34/45',
            },
        ],
    },
    {
        type: 'glass',
        id: '16',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F16.jpg?alt=media&token=b5b6d6f3-66c7-4a07-9102-00fe40f2acfb',
        classify: 'Adapters',
        title: 'Distilling',
        content: [],
        specification: [
            {
                id: '1',
                number: '         KJ-A16-1',
                selected: false,
                content: 'Adapter Distillating 14/20,10/20',
            },
            {
                id: '2',
                number: 'KJ-A16-2',
                selected: false,
                content: 'Adapter Distillating 14/20,14/20',
            },
            {
                id: '3',
                number: '         KJ-A16-3',
                selected: false,
                content: 'Adapter Distillating 24/40,10/20',
            },
            {
                id: '4',
                number: 'KJ-A16-4',
                selected: false,
                content: 'Adapter Distillating 24/40,14/20',
            },
        ],
    },
    {
        type: 'glass',
        id: '17',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F17.jpg?alt=media&token=cc3a9bad-ac1e-456c-ac56-3756a3b720a3',
        classify: 'Adapters',
        title: 'Vacuum filtration',
        content: [],
        specification: [
            {
                id: '1',
                number: '         KJ-A17-1',
                selected: false,
                content: 'Adapter Vacuum Filteration 14/20',
            },
            {
                id: '2',
                number: 'KJ-A17-2',
                selected: false,
                content: 'Adapter Vacuum Filteration 24/40',
            },
        ],
    },
    {
        type: 'glass',
        id: '18',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F18.jpg?alt=media&token=377e87bd-9429-479a-a144-5196a094ac86',
        classify: 'Adapters',
        title: 'Flow control, Glass Plug',
        content: [],
        specification: [
            {
                id: '1',
                number: '         KJ-A18-1',
                selected: false,
                content: 'Adapter Flow Control 14/20 G/C',
            },
            {
                id: '2',
                number: 'KJ-A18-2',
                selected: false,
                content: 'Adapter Flow Control 24/40 G/C',
            },
            {
                id: '3',
                number: '         KJ-A18-3',
                selected: false,
                content: 'Adapter Flow Control 14/20 외산G/C',
            },
            {
                id: '4',
                number: 'KJ-A18-4',
                selected: false,
                content: 'Adapter Flow Control 24/40 외산G/C',
            },
        ],
    },
    {
        type: 'glass',
        id: '19',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F19.jpg?alt=media&token=6c99400a-be00-41a6-82fb-e17356f42f31',
        classify: 'Adapters',
        title: 'Flow control, PTFE Plug',
        content: [],
        specification: [
            {
                id: '1',
                number: '         KJ-A19-1',
                selected: false,
                content: 'Adapter Flow Control 14/20 T/C',
            },
            {
                id: '2',
                number: 'KJ-A19-2',
                selected: false,
                content: 'Adapter Flow Control 24/40 T/C',
            },
            {
                id: '3',
                number: '         KJ-A19-3',
                selected: false,
                content: 'Adapter Flow Control 14/20 외산T/C',
            },
            {
                id: '4',
                number: '         KJ-A19-4',
                selected: false,
                content: 'Adapter Flow Control 24/40 외산T/C',
            },
        ],
    },
    {
        type: 'glass',
        id: '20',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F20.jpg?alt=media&token=70720ebc-d36e-4cda-9f1e-90650d71d230',
        classify: 'Adapters',
        title: 'Flow control',
        content: [],
        specification: [
            {
                id: '1',
                number: '         KJ-A20-1',
                selected: false,
                content: 'Adapter Flow Control 14/20 G/C',
            },
            {
                id: '2',
                number: '         KJ-A20-2',
                selected: false,
                content: 'Adapter Flow Control 24/40 G/C',
            },
            {
                id: '3',
                number: '         KJ-A20-3',
                selected: false,
                content: 'Adapter Flow Control 14/20 T/C',
            },
            {
                id: '4',
                number: 'KJ-A20-4',
                selected: false,
                content: 'Adapter Flow Control 24/40 T/C',
            },
            {
                id: '5',
                number: '         KJ-A20-5',
                selected: false,
                content: 'Adapter Flow Control 14/20 외산G/C',
            },
            {
                id: '6',
                number: '         KJ-A20-6',
                selected: false,
                content: 'Adapter Flow Control 24/40 외산G/C',
            },
            {
                id: '7',
                number: '         KJ-A20-7',
                selected: false,
                content: 'Adapter Flow Control 14/20 외산T/C',
            },
            {
                id: '8',
                number: '         KJ-A20-8',
                selected: false,
                content: 'Adapter Flow Control 24/40 외산T/C',
            },
        ],
    },
    {
        type: 'glass',
        id: '21',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F21.jpg?alt=media&token=0124e9c4-b6e5-4fd5-a451-a054f0247200',
        classify: 'Adapters',
        title: 'Innet',
        content: [],
        specification: [
            {
                id: '1',
                number: 'KJ-A21-1',
                selected: false,
                content: 'Adapter Inlet 14/20',
            },
            {
                id: '2',
                number: '         KJ-A21-2',
                selected: false,
                content: 'Adapter Inlet 24/40',
            },
        ],
    },
    {
        type: 'glass',
        id: '22',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F22.jpg?alt=media&token=830029d4-2d1a-432e-9301-d8752e228c28',
        classify: 'Adapters',
        title: 'Innet',
        content: [],
        specification: [
            {
                id: '1',
                number: '         KJ-A22-1',
                selected: false,
                content: 'Adapter Inlet 14/20',
            },
            {
                id: '2',
                number: '         KJ-A22-2',
                selected: false,
                content: 'Adapter Inlet 24/40',
            },
        ],
    },
    {
        type: 'glass',
        id: '23',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F23.jpg?alt=media&token=fcbde592-b58f-4ef4-a2b4-f1d9873e981f',
        classify: 'Adapters',
        title: 'Innet',
        content: [],
        specification: [
            {
                id: '1',
                number: '         KJ-A23-1',
                selected: false,
                content: 'pter Inlet 14/20',
            },
            {
                id: '2',
                number: '         KJ-A23-2',
                selected: false,
                content: 'Adapter Inlet 24/40',
            },
        ],
    },
    {
        type: 'glass',
        id: '24',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F24.jpg?alt=media&token=abe3cc57-293e-4356-b57b-51ff4e67816c',
        classify: 'Adapters',
        title: 'Innet',
        content: [],
        specification: [
            {
                id: '1',
                number: 'KJ-A24-1',
                selected: false,
                content: 'Adapter Inlet 14/20',
            },
            {
                id: '2',
                number: '         KJ-A24-2',
                selected: false,
                content: 'Adapter Inlet 24/40',
            },
        ],
    },
    {
        type: 'glass',
        id: '25',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F25.jpg?alt=media&token=1a4995a6-474f-4524-9a92-5d8b5678489f',
        classify: 'Adapters',
        title: 'Innet',
        content: [],
        specification: [
            {
                id: '1',
                number: '         KJ-A25-1',
                selected: false,
                content: 'Adapter Inlet 14/20',
            },
            {
                id: '2',
                number: 'KJ-A25-2',
                selected: false,
                content: 'Adapter Inlet 24/40',
            },
        ],
    },
    {
        type: 'glass',
        id: '26',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F26.jpg?alt=media&token=94fd4a36-3de2-4d0c-989d-523b77df1324',
        classify: 'Adapters',
        title: 'Innet',
        content: [],
        specification: [
            {
                id: '1',
                number: 'KJ-A26-1',
                selected: false,
                content: 'Adapter R:7mm',
            },
        ],
    },
    {
        type: 'glass',
        id: '27',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F27.jpg?alt=media&token=71903781-b041-4159-862a-105517dedccf',
        classify: 'Adapters',
        title: 'Innet',
        content: [],
        specification: [
            {
                id: '1',
                number: '         KJ-A27-1',
                selected: false,
                content: 'Adapter Inlet 10/20',
            },
            {
                id: '2',
                number: '         KJ-A27-2',
                selected: false,
                content: 'Adapter Inlet 10/30',
            },
            {
                id: '3',
                number: '         KJ-A27-3',
                selected: false,
                content: 'Adapter Inlet 14/20',
            },
            {
                id: '4',
                number: '         KJ-A27-4',
                selected: false,
                content: 'Adapter Inlet 24/40',
            },
        ],
    },
    {
        type: 'glass',
        id: '28',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F28.jpg?alt=media&token=10159d9b-c676-4f75-9299-f23a42a84a81',
        classify: 'Adapters',
        title: 'Innet',
        content: [],
        specification: [
            {
                id: '1',
                number: 'KJ-A29-1',
                selected: false,
                content: 'apter Inlet 14/20',
            },
            {
                id: '2',
                number: 'KJ-A29-2',
                selected: false,
                content: 'Adapter Inlet 24/40',
            },
        ],
    },
    {
        type: 'glass',
        id: '29',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F29.jpg?alt=media&token=73b2c0d7-f653-40a0-9956-bff0e5f0bd27',
        classify: 'Adapters',
        title: 'Innet 3way stop cock',
        content: [],
        specification: [
            {
                id: '1',
                number: '         KJ-A30N-1',
                selected: false,
                content: 'Adapter Gas Inlet,3Way Stop Cock 14/20 G/C',
            },
            {
                id: '2',
                number: '         KJ-A30N-2',
                selected: false,
                content: 'Adapter Gas Inlet,3Way Stop Cock 24/40 G/C',
            },
            {
                id: '3',
                number: '         KJ-A30N-3',
                selected: false,
                content: 'Adapter Gas Inlet,3Way Stop Cock 14/20 T/C',
            },
            {
                id: '4',
                number: '         KJ-A30N-4',
                selected: false,
                content: 'Adapter Gas Inlet,3Way Stop Cock 24/40 T/C',
            },
            {
                id: '5',
                number: '         KJ-A30N-5',
                selected: false,
                content: 'Adapter Gas Inlet,3Way Stop Cock 14/20 외산G/C',
            },
            {
                id: '6',
                number: '         KJ-A30N-6',
                selected: false,
                content: 'Adapter Gas Inlet,3Way Stop Cock 24/40 외산G/C',
            },
            {
                id: '7',
                number: '         KJ-A30N-7',
                selected: false,
                content: 'Adapter Gas Inlet,3Way Stop Cock 14/20 외산T/C',
            },
            {
                id: '8',
                number: '         KJ-A30N-8',
                selected: false,
                content: 'Adapter Gas Inlet,3Way Stop Cock 24/40 외산T/C',
            },
        ],
    },
    {
        type: 'glass',
        id: '30',
        image: 'https://firebasestorage.googleapis.com/v0/b/kjglass-60495.appspot.com/o/glass%2F30.jpg?alt=media&token=b58ad6af-e480-4282-a0f9-9fc5e8e17bd7',
        classify: 'Adapters',
        title: 'Septum inlet',
        content: [],
        specification: [
            {
                id: '1',
                number: '         KJ-A32-1',
                selected: false,
                content: 'Adapter Septum Inlet 14/20 T/C',
            },
            {
                id: '2',
                number: 'KJ-A32-2',
                selected: false,
                content: 'Adapter Septum Inlet 24/40 T/C',
            },
            {
                id: '3',
                number: '         KJ-A32-3',
                selected: false,
                content: 'Adapter Septum Inlet 34/45 T/C',
            },
            {
                id: '4',
                number: 'KJ-A32-4',
                selected: false,
                content: 'Adapter Septum Inlet 14/20 G/C',
            },
            {
                id: '5',
                number: '         KJ-A32-5',
                selected: false,
                content: 'Adapter Septum Inlet 24/40 G/C',
            },
            {
                id: '6',
                number: '         KJ-A32-6',
                selected: false,
                content: 'Adapter Septum Inlet 34/45 G/C',
            },
            {
                id: '7',
                number: '         KJ-A32-11',
                selected: false,
                content: 'Adapter Septum Inlet 14/20 외산T/C',
            },
            {
                id: '8',
                number: '         KJ-A32-12',
                selected: false,
                content: 'Adapter Septum Inlet 24/40 외산T/C',
            },
            {
                id: '9',
                number: '         KJ-A32-13',
                selected: false,
                content: 'Adapter Septum Inlet 34/45 외산T/C',
            },
            {
                id: '10',
                number: 'KJ-A32-15',
                selected: false,
                content: 'Adapter Septum Inlet 14/20 외산G/C',
            },
            {
                id: '11',
                number: '         KJ-A32-16',
                selected: false,
                content: 'Adapter Septum Inlet 24/40 외산G/C',
            },
            {
                id: '12',
                number: '         KJ-A32-17',
                selected: false,
                content: 'Adapter Septum Inlet 34/45 외산G/C',
            },
        ],
    },
];

export default items;
